document.writeln('<object classid="clsid:8AD9C840-044E-11D1-B3E9-00805F499D93"');
document.writeln('      width= "250" height= "60" id="rup"');
document.writeln('      codebase="http://java.sun.com/update/1.5.0/jinstall-1_5-windows-i586.cab#version=1,4,1">');
document.writeln('<param name="archive" value="/ucmxe/common/ECS_BaseUtils/dndplus.jar">');
document.writeln('<param name="monitor.type" value="compact">');
document.writeln('<param name="monitor.embed" value="yes">');
document.writeln('<param name="external_redir" value="http://hera10gr3/ucmxe/idcplg?IdcService=GET_DOC_PAGE&Action=GetTemplatePage&Page=UPLOAD_SUCCESS">');
document.writeln('<param name="redirect_delay" value="1">');
document.writeln('<param name="browse" value="yes">');
document.writeln('<param name="code" value="com.radinks.dnd.DNDAppletPlus">');
document.writeln('<param name="name" value="ECS Upload Plus">');