
-- Table REF_PUBLIC_HOLIDAY
CREATE TABLE REF_PUBLIC_HOLIDAY(
  HOLIDAY_ID Number(15,0) NOT NULL,
  HOLIDAY_DATE Timestamp(6) NOT NULL,
  DESCRIPTION Varchar2(40 )
)
/
-- Add keys for table REF_PUBLIC_HOLIDAY
ALTER TABLE REF_PUBLIC_HOLIDAY ADD CONSTRAINT HOLIDAY_ID_PK PRIMARY KEY (HOLIDAY_ID)
/

-- holiday id sequence
CREATE SEQUENCE "CCLA"."SEQ_HOLIDAY_ID" MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;

-- holiday id trigger
create or replace
TRIGGER "REF_PUBLIC_HOLIDAY_TRIGGER" BEFORE
  INSERT ON REF_PUBLIC_HOLIDAY FOR EACH row WHEN(new.HOLIDAY_ID IS NULL) BEGIN
  SELECT SEQ_HOLIDAY_ID.nextval INTO :NEW.HOLIDAY_ID FROM dual;
END;
/

/* Synonym */
CREATE OR REPLACE PUBLIC SYNONYM REF_PUBLIC_HOLIDAY FOR CCLA.REF_PUBLIC_HOLIDAY;

/* Grant Access */
GRANT ALL ON REF_PUBLIC_HOLIDAY TO UCMADMIN;
GRANT ALL ON SEQUENCE SEQ_HOLIDAY_ID TO UCMADMIN
GRANT ALL ON REF_PUBLIC_HOLIDAY_TRIGGER TO UCMADMIN;