-- Find entries in the table less than 30 days old, clear up if possible
SELECT idocs.*, r.dInDate FROM TWITHINSTRUCTIONDOCS idocs
INNER JOIN Revisions r ON (idocs.dDOCNAME = r.dDocName) 
WHERE r.dInDate > (SYSDATE-30);

-- Rename table
ALTER TABLE TWITHINSTRUCTIONDOCS RENAME TO PENDING_CHILDDOCS;

ALTER TABLE PENDING_CHILDDOCS RENAME COLUMN DDOCNAME TO PARENT_DOCNAME;

-- Add new columns
ALTER TABLE PENDING_CHILDDOCS ADD (
  PENDING_CHILDDOC_ID NUMBER(15,0),
  DATE_ADDED TIMESTAMP(6),
  ADDED_BY VARCHAR(60 CHAR),
  DATE_GENERATED TIMESTAMP(6),
  GEN_DOCNAME VARCHAR2(50 CHAR)
);

CREATE SEQUENCE SEQ_PENDINGCHILDDOC START WITH 1;




