/*
Before running this script:

-Export all data in INVESTMENT_FUND_ALLOCATION into Excel sheet. This table
 will be dropped and replaced.
-Run everything as CCLA user!

*/



-- Drop indexes/FKs
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION DROP CONSTRAINT ELEMENT_DONTTLAALLOC_FK
/
DROP INDEX IX_ELEMENT_DONTTLAALLOC_FK
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION DROP CONSTRAINT DON_DONTTLAALLOC_FK
/
DROP INDEX IX_DON_DONTTLAALLOC_FK
/
ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION DROP CONSTRAINT FUND_INVESTFUNDALLOC_FK
/
DROP INDEX IX_FNDINVESTT_FNDALLOC_FK
/
ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION DROP CONSTRAINT INVEST_INVESTFUNDALLOC_FK
/
DROP INDEX IX_INVEST_INVESTFUNDALLOC_FK
/
ALTER TABLE CCLA.DONATION DROP CONSTRAINT ELEMENT_DONATION_FK
/
DROP INDEX IX_ELEMENT_DONATION_FK
/
ALTER TABLE CCLA.DONATION DROP CONSTRAINT INVESTMENT_DONATION_FK
/
DROP INDEX IX_INVESTMENT_DONATION_FK
/
ALTER TABLE CCLA.INVESTMENT DROP CONSTRAINT INVESTTYPE_INVEST_FK
/
DROP INDEX IX_INVESTTYPE_INVEST_FK
/
ALTER TABLE FORM DROP CONSTRAINT INVESTMENT_FORM_FK
/
DROP INDEX INVESTMENT_FORM_IX
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION DROP CONSTRAINT TTLAALLOC_UQ
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION DROP CONSTRAINT DONATIONTTLAALLOCATION_PK
/
/*
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION DROP CONSTRAINT INCOME_ALLOCATION_PERCENT_CK
/
DROP TABLE CCLA.DONATION_TTLA_ALLOCATION
/
*/

ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION DROP CONSTRAINT INVESTMENT_FUND_ALLOCATION_PK
/

/*
Ensure data is backed up first!!
*/
DROP TABLE CCLA.INVESTMENT_FUND_ALLOCATION
/

DROP INDEX CCLA.DONATION_UQ_I
/

-- Ensure this is the correct PK name
ALTER TABLE CCLA.DONATION DROP CONSTRAINT Key42
/

/*
DROP TABLE CCLA.DONATION
/
*/

-- Drop REF_INVESTMENT_TYPE table
ALTER TABLE CCLA.REF_INVESTMENT_TYPE DROP CONSTRAINT INVESTMENT_TYPE_PK
/
DROP TABLE CCLA.REF_INVESTMENT_TYPE
/
DROP INDEX CCLA.IX_INVEST_INVESTREF
/

ALTER TABLE CCLA.INVESTMENT DROP CONSTRAINT INVESTMENT_PK
/

ALTER TABLE CCLA.INVESTMENT DROP CONSTRAINT INVESTMENT_RPI_CK
/

ALTER TABLE FORM RENAME COLUMN INVESTMENT_ID TO SUBSCRIPTION_ID;

ALTER TABLE INVESTMENT RENAME TO SUBSCRIPTION;
ALTER TABLE SUBSCRIPTION RENAME COLUMN INVESTMENT_ID TO SUBSCRIPTION_ID;
ALTER TABLE SUBSCRIPTION RENAME COLUMN INVESTMENT_TYPE_ID TO SUBSCRIPTION_TYPE_ID;
ALTER TABLE SUBSCRIPTION RENAME COLUMN INVESTMENT_AMOUNT TO SUBSCRIPTION_AMOUNT;
ALTER TABLE SUBSCRIPTION RENAME COLUMN INVESTMENT_DATE TO SUBSCRIPTION_DATE;
ALTER TABLE SUBSCRIPTION RENAME COLUMN INVESTMENT_PAYMENT_REF TO SUBSCRIPTION_PAYMENT_REF;

/*
CREATE TABLE CCLA.SUBSCRIPTION(
  SUBSCRIPTION_ID Number(15,0) NOT NULL,
  ACCOUNT_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_TYPE_ID Number(15,0),
  SUBSCRIPTION_AMOUNT Float,
  RPI Number(7,4)
        CONSTRAINT INVESTMENT_RPI_CK CHECK (RPI BETWEEN 0 AND 100),
  SUBSCRIPTION_DATE Date,
  SUBSCRIPTION_PAYMENT_REF Char(18 ),
  DATE_ADDED Timestamp(6) CONSTRAINT INVEST_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT INVEST_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/
*/

CREATE UNIQUE INDEX CCLA.IX_SUB_SUBREF ON CCLA.SUBSCRIPTION (SUBSCRIPTION_PAYMENT_REF)
/
ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID)
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.SUBSCRIPTION_PAYMENT_REF IS 'A Subscription Reference number that can be used to identlfy an Orgs payments (e.g. 12 character OrgAccountCode plus a payment number, such as AWPF00123456-00010'
/
COMMENT ON COLUMN CCLA.SUBSCRIPTION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.SUBSCRIPTION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

CREATE TABLE CCLA.REF_SUBSCRIPTION_TYPE(
  SUBSCRIPTION_TYPE_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_NAME Varchar2(50 ) NOT NULL
)
/

ALTER TABLE CCLA.REF_SUBSCRIPTION_TYPE ADD CONSTRAINT INVESTMENT_TYPE_PK PRIMARY KEY (SUBSCRIPTION_TYPE_ID)
/

REM INSERTING into REF_SUBSCRIPTION_TYPE
Insert into REF_SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID,SUBSCRIPTION_NAME) values (1,'Qualifies for Gov. Match');
Insert into REF_SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID,SUBSCRIPTION_NAME) values (3,'Gift Aid (grants and social investments)');
Insert into REF_SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID,SUBSCRIPTION_NAME) values (2,'Gift Aid (added to endowment)');

ALTER TABLE DONATION RENAME TO CONTRIBUTION;
ALTER TABLE CONTRIBUTION RENAME COLUMN DONATION_ID TO CONTRIBUTION_ID;
ALTER TABLE CONTRIBUTION RENAME COLUMN INVESTMENT_ID TO SUBSCRIPTION_ID;
ALTER TABLE CONTRIBUTION RENAME COLUMN DONATION_AMOUNT TO CONTRIBUTION_AMOUNT;

/*
CREATE TABLE CCLA.CONTRIBUTION(
  CONTRIBUTION_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_ID Number(15,0) NOT NULL,
  DONOR_ID Number(15,0) NOT NULL,
  CONTRIBUTION_AMOUNT Float,
  GOV_RECOVERY_AMT_EXPECTED Float,
  GOV_RECOVERY_AMT_ACTUAL Float,
  DATE_ADDED Timestamp(6) CONSTRAINT DONATION_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT DONATION_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/
*/

CREATE UNIQUE INDEX CCLA.CONTRIBUTION_UQ_I ON CCLA.CONTRIBUTION (DONOR_ID,SUBSCRIPTION_ID)
/

ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CONTRIBUTION_PK PRIMARY KEY (CONTRIBUTION_ID)
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.CONTRIBUTION_AMOUNT IS 'The amount of the donation'
/
COMMENT ON COLUMN CCLA.CONTRIBUTION.GOV_RECOVERY_AMT_EXPECTED IS 'The expected amount the government will pay against the value of the investment - i.e. 100%'
/
COMMENT ON COLUMN CCLA.CONTRIBUTION.GOV_RECOVERY_AMT_ACTUAL IS 'The actual  amount the government has paid against the total value of the donation.'
/
COMMENT ON COLUMN CCLA.CONTRIBUTION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.CONTRIBUTION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/


CREATE TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION(
  CONTRIB_FUND_ALLOCATION_ID Number(15,0) NOT NULL,
  FUND_CODE Varchar2(2 CHAR) NOT NULL,
  CONTRIBUTION_FUND_AMOUNT Float NOT NULL,
  DATE_ADDED Timestamp(6) CONSTRAINT INVFNDALLOC_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT INVFNDALLOC_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL,
  CONTRIBUTION_ID Number(15,0) NOT NULL
)
/

-- Add keys for table CCLA.CONTRIBUTION_FUND_ALLOCATION

ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION ADD CONSTRAINT CONTRIBFUNDALLOC_PK PRIMARY KEY (CONTRIB_FUND_ALLOCATION_ID)
/
ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION ADD CONSTRAINT CONTRIBFUNDALLOC_UQ UNIQUE (CONTRIBUTION_ID,FUND_CODE)
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_FUND_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.CONTRIBUTION_FUND_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

ALTER TABLE DONATION_TTLA_ALLOCATION RENAME TO CONTRIBUTION_TTLA_ALLOCATION;
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION RENAME COLUMN DONATION_TTLA_ALLOCATION_ID TO CONTRIB_TTLA_ALLOCATION_ID;
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION RENAME COLUMN DONATION_ID TO CONTRIBUTION_ID;

ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT DONATIONTTLAALLOCATION_PK PRIMARY KEY (CONTRIB_TTLA_ALLOCATION_ID)
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT TTLAALLOC_UQ UNIQUE (CONTRIBUTION_ID,TTLA_ORG_ID)
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

CREATE INDEX IX_INVESTTYPE_INVEST_FK ON CCLA.SUBSCRIPTION (SUBSCRIPTION_TYPE_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT SUBTYPE_SUB_FK FOREIGN KEY (SUBSCRIPTION_TYPE_ID) REFERENCES CCLA.REF_SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID)
/
CREATE INDEX IX_INVESTMENT_DONATION_FK ON CCLA.CONTRIBUTION (SUBSCRIPTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT SUBSCRIPTION_DONATION_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES CCLA.SUBSCRIPTION (SUBSCRIPTION_ID)
/
CREATE INDEX IX_ELEMENT_DONATION_FK ON CCLA.CONTRIBUTION (DONOR_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT ELEMENT_CONTRIBUTION_FK FOREIGN KEY (DONOR_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/
CREATE INDEX IX_FNDINVESTT_FNDALLOC_FK ON CCLA.CONTRIBUTION_FUND_ALLOCATION (FUND_CODE) 
/
ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION ADD CONSTRAINT FUND_SUBFUNDALLOC_FK FOREIGN KEY (FUND_CODE) REFERENCES CCLA.FUND (FUND_CODE)
/
CREATE INDEX IX_DON_DONTTLAALLOC_FK ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (CONTRIBUTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT CONTR_CONTRTTLAALLOC_FK FOREIGN KEY (CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/
CREATE INDEX IX_ELEMENT_DONTTLAALLOC_FK ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (TTLA_ORG_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT ELEMENT_CONTRTTLAALLOC_FK FOREIGN KEY (TTLA_ORG_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/


/*
New index/FK for FORM.SUBSCRIPTION_ID column
*/
CREATE INDEX SUBSCRIPTION_FORM_IX ON FORM (SUBSCRIPTION_ID) 
/
ALTER TABLE FORM ADD CONSTRAINT SUBSCRIPTION_FORM_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES CCLA.SUBSCRIPTION (SUBSCRIPTION_ID)
/

-- Add keys for table CCLA.CONTRIBUTION_FUND_ALLOCATION

ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION ADD CONSTRAINT CONTRIBFUNDALLOC_PK PRIMARY KEY (CONTRIB_FUND_ALLOCATION_ID)
/
CREATE UNIQUE INDEX CONTRIBFUNDALLOC_UQ_I ON CCLA.CONTRIBUTION_FUND_ALLOCATION (CONTRIBUTION_ID,FUND_CODE)
/

-- FK between CONTRIBUTION and CONTRIBUTION_FUND_ALLOCATION
CREATE INDEX CONTRIB_CONTRIBFUNDALLOC_IX ON CCLA.CONTRIBUTION_FUND_ALLOCATION (CONTRIBUTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION ADD CONSTRAINT CONTRIB_CONTRIBFUNDALLOC_FK FOREIGN KEY (CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/

/* HERE
*/

DROP INDEX IX_DON_DONTTLAALLOC_FK;

-- FK between CONTRIBUTION and CONTRIBUTION_TTLA_ALLOCATION
CREATE INDEX CONTRIB_CONTRIBTTLAALLOC_IX ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (CONTRIBUTION_ID) 
/

-- Dropping previous public table synonyms, creating new ones and granting rights
DROP PUBLIC SYNONYM DONATION;
DROP PUBLIC SYNONYM INVESTMENT;
DROP PUBLIC SYNONYM INVESTMENT_FUND_ALLOCATION;
DROP PUBLIC SYNONYM DONATION_TTLA_ALLOCATION;
DROP PUBLIC SYNONYM REF_INVESTMENT_TYPE;

-- Dropping previous public table synonyms, creating new ones and granting rights
CREATE OR REPLACE PUBLIC SYNONYM CONTRIBUTION FOR CCLA.CONTRIBUTION;
CREATE OR REPLACE PUBLIC SYNONYM SUBSCRIPTION FOR CCLA.SUBSCRIPTION;
CREATE OR REPLACE PUBLIC SYNONYM CONTRIBUTION_FUND_ALLOCATION FOR CCLA.CONTRIBUTION_FUND_ALLOCATION;
CREATE OR REPLACE PUBLIC SYNONYM CONTRIBUTION_TTLA_ALLOCATION FOR CCLA.CONTRIBUTION_TTLA_ALLOCATION;
CREATE OR REPLACE PUBLIC SYNONYM REF_SUBSCRIPTION_TYPE FOR CCLA.REF_SUBSCRIPTION_TYPE;

GRANT ALL ON CONTRIBUTION TO UCMADMIN;
GRANT ALL ON SUBSCRIPTION TO UCMADMIN;
GRANT ALL ON CONTRIBUTION_FUND_ALLOCATION TO UCMADMIN;
GRANT ALL ON CONTRIBUTION_TTLA_ALLOCATION TO UCMADMIN;
GRANT ALL ON REF_SUBSCRIPTION_TYPE TO UCMADMIN;

-- Sequence renaming, dropping previous public synonyms, creating new ones and granting rights
RENAME SEQ_INVESTMENT TO SEQ_SUBSCRIPTION;
RENAME SEQ_DONATION TO SEQ_CONTRIBUTION;
RENAME SEQ_DONATION_TTLA_ALLOCATION TO SEQ_CONTRIB_TTLA_ALLOCATION;
RENAME SEQ_INVESTMENT_FUND_ALLOCATION TO SEQ_CONTRIB_FUND_ALLOCATION;

DROP PUBLIC SYNONYM SEQ_DONATION;
DROP PUBLIC SYNONYM SEQ_INVESTMENT;
DROP PUBLIC SYNONYM SEQ_INVESTMENT_FUND_ALLOCATION;
DROP PUBLIC SYNONYM SEQ_DONATION_TTLA_ALLOCATION;

CREATE OR REPLACE PUBLIC SYNONYM SEQ_CONTRIBUTION FOR CCLA.SEQ_CONTRIBUTION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SUBSCRIPTION  FOR CCLA.SEQ_SUBSCRIPTION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CONTRIB_FUND_ALLOCATION FOR CCLA.SEQ_CONTRIB_FUND_ALLOCATION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CONTRIB_TTLA_ALLOCATION FOR CCLA.SEQ_CONTRIB_TTLA_ALLOCATION;

GRANT ALL ON SEQ_CONTRIBUTION TO UCMADMIN;
GRANT ALL ON SEQ_SUBSCRIPTION TO UCMADMIN;
GRANT ALL ON SEQ_CONTRIB_FUND_ALLOCATION TO UCMADMIN;
GRANT ALL ON SEQ_CONTRIB_TTLA_ALLOCATION TO UCMADMIN;

/* Data fix for INCOME_ALLOCATION_PERCENT: changing precision on percentage column. */
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION ADD (
  INC2 number(12,10)
);

UPDATE CONTRIBUTION_TTLA_ALLOCATION SET INC2 = INCOME_ALLOCATION_PERCENT;
UPDATE CONTRIBUTION_TTLA_ALLOCATION SET INCOME_ALLOCATION_PERCENT = NULL;

ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION MODIFY (
  INCOME_ALLOCATION_PERCENT number(12,10)
);

UPDATE CONTRIBUTION_TTLA_ALLOCATION SET INCOME_ALLOCATION_PERCENT = INC2;
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION DROP COLUMN INC2;

-- New column: Allocation Amount
alter table contribution_ttla_allocation ADD (
  INCOME_ALLOCATION_AMOUNT number(15,2)
);

-- TODO: populate above new column


/* New constraint – forces both Percentage/Amount values to both be null or both non-null */
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION ADD (
  CONSTRAINT CONTRIBTTLAALLOC_CHQ CHECK (
    (INCOME_ALLOCATION_PERCENT IS NULL
    AND
    INCOME_ALLOCATION_AMOUNT IS NULL)
    
    OR 
    
    (INCOME_ALLOCATION_PERCENT IS NOT NULL
    AND
    INCOME_ALLOCATION_AMOUNT IS NOT NULL)
  )
);

-- New 'Payer' Instruction Data field
REM INSERTING into REF_INSTRUCTION_DATA
Insert into REF_INSTRUCTION_DATA (INSTRUCTION_DATA_ID,INSTRUCTION_DATA_NAME,INSTRUCTION_DATA_TYPE,INSTRUCTION_DATA_LABEL,INSTRUCTION_DATA_DESCRIPTION) values (61,'PAYER','INT','Payer','Source Organisation/Person who made the payment');

-- Fix subscription type names
UPDATE REF_SUBSCRIPTION_TYPE SET SUBSCRIPTION_NAME = 'Endowment (Eligible for Government Match)' WHERE SUBSCRIPTION_TYPE_ID = 1;
UPDATE REF_SUBSCRIPTION_TYPE SET SUBSCRIPTION_NAME = 'Endowment (Not Eligible for Government Match)' WHERE SUBSCRIPTION_TYPE_ID = 2;
UPDATE REF_SUBSCRIPTION_TYPE SET SUBSCRIPTION_NAME = 'Gift Aid (Grants and Social Investments)' WHERE SUBSCRIPTION_TYPE_ID = 3;


-- Table CCLA.REF_SUBSCRIPTION_STATUS

CREATE TABLE CCLA.REF_SUBSCRIPTION_STATUS(
  SUBSCRIPTION_STATUS_ID Number(15,0) CONSTRAINT SUBSTATUS_ID_NN NOT NULL,
  SUBSCRIPTION_STATUS_NAME Varchar2(100 ) CONSTRAINT SUBSTATUS_NAME_NN NOT NULL
)
/

-- Add keys for table CCLA.REF_SUBSCRIPTION_STATUS

ALTER TABLE CCLA.REF_SUBSCRIPTION_STATUS ADD CONSTRAINT SUBSTATUS_PK PRIMARY KEY (SUBSCRIPTION_STATUS_ID)
/

-- Table and Columns comments section
  
COMMENT ON TABLE CCLA.REF_SUBSCRIPTION_STATUS IS 'Subscription statuses.'
/

ALTER TABLE SUBSCRIPTION ADD (
  SUBSCRIPTION_STATUS_ID Number(15,0)
)
/

CREATE INDEX SUBSTATUS_SUBS_IX ON CCLA.SUBSCRIPTION (SUBSCRIPTION_STATUS_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT SUBSTATUS_SUBS_FK FOREIGN KEY (SUBSCRIPTION_STATUS_ID) REFERENCES CCLA.REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID)
/

-- Populate status table
REM INSERTING into REF_SUBSCRIPTION_STATUS
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (1,'New');
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (2,'Form generated');
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (3,'Form returned');
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (4,'Failed validation');
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (5,'Completed');
Insert into REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID,SUBSCRIPTION_STATUS_NAME) values (6,'Cancelled');

-- Populate status column

-- Set all to 'New' status initially
UPDATE SUBSCRIPTION SET SUBSCRIPTION_STATUS_ID = 1;

-- Set to 'Form generated' if a form exists with the Subscription ID
UPDATE SUBSCRIPTION SET SUBSCRIPTION_STATUS_ID = 2 WHERE SUBSCRIPTION_ID IN
(SELECT SUBSCRIPTION_ID FROM FORM);

-- Set to 'Form returned' if a returned form exists with the Subscription ID
UPDATE SUBSCRIPTION SET SUBSCRIPTION_STATUS_ID = 2 WHERE SUBSCRIPTION_ID IN
(SELECT SUBSCRIPTION_ID FROM FORM WHERE DATE_RETURNED IS NOT NULL);

-- Add NN constraint
ALTER TABLE SUBSCRIPTION MODIFY (
  SUBSCRIPTION_STATUS_ID Number(15,0) CONSTRAINT SUBS_SUBSTATUS_NN NOT NULL
)
/

CREATE OR REPLACE PUBLIC SYNONYM REF_SUBSCRIPTION_STATUS FOR CCLA.REF_SUBSCRIPTION_STATUS;
GRANT ALL ON REF_SUBSCRIPTION_STATUS TO UCMADMIN;

-- Alter table to allow 100% allocations.
ALTER TABLE CONTRIBUTION_TTLA_ALLOCATION
MODIFY INCOME_ALLOCATION_PERCENT NUMBER(13,10);
