
-- New Verification Source: Experian
REM INSERTING into REF_VERIFICATION_SOURCE
Insert into REF_VERIFICATION_SOURCE (VERIFICATION_SOURCE_ID,VER_SOURCE_NAME,VER_SOURCE_DESCRIPTION,SUPPORTING_DOC_REQUIRED,IS_OVERRIDE) values (20,'Experian','Experian Identity Authentication/Validation',0,0);
-- New Verification Source: AML Tracker
Insert into REF_VERIFICATION_SOURCE (VERIFICATION_SOURCE_ID,VER_SOURCE_NAME,VER_SOURCE_DESCRIPTION,SUPPORTING_DOC_REQUIRED,IS_OVERRIDE) values (21,'Legacy AML Tracker','Data from legacy AML Tracker system',0,0);
-- New Verification Source: SPP
Insert into REF_VERIFICATION_SOURCE (VERIFICATION_SOURCE_ID,VER_SOURCE_NAME,VER_SOURCE_DESCRIPTION,SUPPORTING_DOC_REQUIRED,IS_OVERRIDE) values (22,'Workflow','Data from Workflow/Total Agility system',0,0);

-- Associate new 'Experian' source with Person Identity Check attribute
UPDATE REF_ELEMENT_ATTRIBUTES SET VERIFICATION_SOURCE_ID = 20 WHERE ELEMENT_ATTRIBUTE_ID = 7;

-- Update existing verification attributes to point at new verification sources, instead of the
-- generic 'Legacy System' source.
UPDATE REF_ELEMENT_ATTRIBUTES SET VERIFICATION_SOURCE_ID = 21 WHERE ELEMENT_ATTRIBUTE_ID = 11;
UPDATE REF_ELEMENT_ATTRIBUTES SET VERIFICATION_SOURCE_ID = 22 WHERE ELEMENT_ATTRIBUTE_ID = 12;

-- Add new Element Attributes
REM INSERTING into REF_ELEMENT_ATTRIBUTES
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (49,'No Mandate since Oct 16th 2010',3,'No mandate document received for this account since October 16th, 2010',0,null,null,null,'BOOL',5);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (50,'Verified by AML',2,'Person was checked during legacy AML tracker exercise',0,21,null,null,'BOOL',1);

-- Update name/description for existing Element Attribute Type for Account-level IVS Checking
UPDATE REF_ELEMENT_ATTRIBUTE_TYPE SET ELEMENT_ATTRIBUTE_TYPE_NAME = 'Account IVS Checking', ELEMENT_ATTRIBUTE_TYPE_DESC = 'Used for overriding all IVS Checking at account level' WHERE ELEMENT_ATTRIBUTE_TYPE_ID = 3;

-- Add new Element Attribute Type for storing Person IVS attributes against.
REM INSERTING into REF_ELEMENT_ATTRIBUTE_TYPE
Insert into REF_ELEMENT_ATTRIBUTE_TYPE (ELEMENT_ATTRIBUTE_TYPE_ID,ELEMENT_ATTRIBUTE_TYPE_NAME,ELEMENT_ATTRIBUTE_TYPE_DESC) values (7,'IVS Checking','Person Identity Checking');

-- Update existing Person IVS attributes to use new Element Attribute Type above
UPDATE REF_ELEMENT_ATTRIBUTES SET ELEMENT_ATTRIBUTE_TYPE_ID = 7 WHERE ELEMENT_ATTRIBUTE_ID IN (7,8,50,37,39);

-- Add new Relation Property: Verified by Legacy AML Tracker
REM INSERTING into REF_PROPERTY
Insert into REF_PROPERTY (PROPERTY_ID,PROPERTY_NAME,VERIFICATION_SOURCE_ID,SET_BY_USER,PROPERTY_TYPE,IS_SINGLETON) values (14,'Verified by Legacy AML Tracker',21,0,'BOOL',0);

INSERT INTO REF_RELATION_PROPERTY (RELATION_PROPERTY_ID, RELATION_NAME_ID, PROPERTY_ID)
VALUES (28, 1, 14);

-- Add above property to Org-Person 'Authorising Person' relationship
INSERT INTO REF_RELATION_PROPERTY (RELATION_PROPERTY_ID, RELATION_NAME_ID, PROPERTY_ID)
VALUES (27, 2, 14);

-- Add properties to Account Corr/Auth person relationship
Insert into REF_RELATION_PROPERTY (RELATION_PROPERTY_ID,RELATION_NAME_ID,PROPERTY_ID) values (29,80,14);
Insert into REF_RELATION_PROPERTY (RELATION_PROPERTY_ID,RELATION_NAME_ID,PROPERTY_ID) values (30,81,14);

-- New Identity Check Lookup - Legacy AML Tracker checked
REM INSERTING into IDENTITY_CHECK_LOOKUP
Insert into IDENTITY_CHECK_LOOKUP (OUTCOME_ID,DESCRIPTION,EXPERIAN_RISK_CODE,EXPERIAN_DECISION_CODE,EXPERIAN_DECISION_TEXT,HAPPY_SCORE,UNHAPPY_SCORE,FAIL_CONDITION,PASS_CONDITION,AMBER_CONDITION) values (87,'Legacy AML Tracker checked',null,null,null,89,null,null,1,null);

-- Update names of IVS override attributes
UPDATE REF_ELEMENT_ATTRIBUTES SET ELEMENT_ATTRIBUTE_NAME = 'PEP Check Override', USER_GROUPS = 'CCLA-Compliance' WHERE ELEMENT_ATTRIBUTE_ID = 37;
UPDATE REF_ELEMENT_ATTRIBUTES SET ELEMENT_ATTRIBUTE_NAME = 'ID Check Override', USER_GROUPS = 'CCLA-Compliance' WHERE ELEMENT_ATTRIBUTE_ID = 39;

-- Set Compliance Dept. as Verification Source for above attribs
UPDATE REF_ELEMENT_ATTRIBUTES SET VERIFICATION_SOURCE_ID = 10 WHERE ELEMENT_ATTRIBUTE_ID IN (37,39);

-- Add new Element Attrib ID column to Identity Check Lookup table
-- TODO: add to Toad
ALTER TABLE IDENTITY_CHECK_LOOKUP ADD (
  ELEMENT_ATTRIBUTE_ID INTEGER
);

ALTER TABLE IDENTITY_CHECK_LOOKUP ADD (
  CONSTRAINT IDCHKLOOKUP_ELEMATTR_FK FOREIGN KEY (ELEMENT_ATTRIBUTE_ID) REFERENCES REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID)
);

-- Apply ID-Checked attribute to all eligible Pass outcomes
UPDATE IDENTITY_CHECK_LOOKUP SET ELEMENT_ATTRIBUTE_ID = 7
WHERE OUTCOME_ID IN (3, 6, 7, 8, 84);

-- Update caption used for 'expired' score
UPDATE IDENTITY_CHECK_LOOKUP SET DESCRIPTION = 'Identity Check expired' WHERE OUTCOME_ID = 23;

-- Force recalculation of Identity Check for all persons with the Legacy AML Tracker
-- attribute. Optionally, run the new CCLA_CS_RECALCULATE_ALL_IDENTITY_CHECKS service afterwards
-- to actually recalculate the statuses.
UPDATE IDENTITY_CHECK SET RECALCULATE_DATE  = (SYSDATE-1) WHERE PERSON_ID IN
 (SELECT ELEMENT_ID FROM ELEMENT_ATTRIBUTE_APPLIED WHERE ELEMENT_ATTRIBUTE_ID = 50); 

-- Add missing person attributes.
-- Already done by DH in live on 03/11/2011
/*
-- Adding new 'Identity Checked' attribute against persons who are authenticated and don't yet have the attribute set.
INSERT INTO ELEMENT_ATTRIBUTE_APPLIED 
(ATTRIBUTE_STATUS, ATTRIBUTE_VALUE, DATE_ADDED, ELEMENT_ATTRIBUTE_ID, ELEMENT_ID, LAST_UPDATED, LAST_UPDATED_BY, SUPPORTING_DOC_ID)
SELECT 1, NULL, SYSDATE, 7, PERSON_ID, SYSDATE, 'System', NULL
FROM IDENTITY_CHECK WHERE IS_AUTHENTICATED = 1 AND PERSON_ID NOT IN (
  SELECT ELEMENT_ID FROM ELEMENT_ATTRIBUTE_APPLIED WHERE ELEMENT_ATTRIBUTE_ID = 7
);

-- Adding new 'PEP Checked' attribute against persons who passed PEP check (authentication attempted, pass/fail doesn't
-- matter as long as it didn't come back with the PEP risk) and don't yet have the attribute set.
INSERT INTO ELEMENT_ATTRIBUTE_APPLIED 
(ATTRIBUTE_STATUS, ATTRIBUTE_VALUE, DATE_ADDED, ELEMENT_ATTRIBUTE_ID, ELEMENT_ID, LAST_UPDATED, LAST_UPDATED_BY, SUPPORTING_DOC_ID)
SELECT 1, NULL, SYSDATE, 8, PERSON_ID, SYSDATE, 'System', NULL
FROM IDENTITY_CHECK WHERE IS_AUTHENTICATED IN (0,1) AND AUTHENTICATION_INDEX > 0 AND PERSON_ID NOT IN (
  SELECT ELEMENT_ID FROM ELEMENT_ATTRIBUTE_APPLIED WHERE ELEMENT_ATTRIBUTE_ID = 8
);
*/
