-- New Form Statuses
INSERT INTO REF_FORM_STATUS VALUES (7, 'Cancelled', 'Form has been invalidated');
INSERT INTO REF_FORM_STATUS VALUES (8, 'Old', 'Form has been superseded by a newer version');

-- New sequences
CREATE SEQUENCE SEQ_PAYMENT;
CREATE SEQUENCE SEQ_SUBSCRIPTION_PAYMENT;
CREATE SEQUENCE SEQ_CONTRIBUTION_PAYMENT;

-- Sequence synonyms
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PAYMENT FOR CCLA.SEQ_PAYMENT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SUBSCRIPTION_PAYMENT FOR CCLA.SEQ_SUBSCRIPTION_PAYMENT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CONTRIBUTION_PAYMENT FOR CCLA.SEQ_CONTRIBUTION_PAYMENT;

-- Sequence grants
GRANT ALL ON SEQ_PAYMENT TO UCMADMIN;
GRANT ALL ON SEQ_SUBSCRIPTION_PAYMENT TO UCMADMIN;
GRANT ALL ON SEQ_CONTRIBUTION_PAYMENT TO UCMADMIN;
