INSERT INTO REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) 
VALUES (63,'CF Coll. Account Type',3,'Community First Collection Account Type',0,null,null,null,'STRING',5);

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189201,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189203,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189205,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189194,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189195,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189196,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189191,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189192,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189193,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189206,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189207,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189208,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189197,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189198,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189199,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189186,63,SYSDATE,null,SYSDATE,'System',null,'Endowment');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189187,63,SYSDATE,null,SYSDATE,'System',null,'Gift Aid');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189188,63,SYSDATE,null,SYSDATE,'System',null,'Government Match');

INSERT INTO ELEMENT_ATTRIBUTE_APPLIED (ELEMENT_ID,ELEMENT_ATTRIBUTE_ID,DATE_ADDED,ATTRIBUTE_STATUS,LAST_UPDATED,LAST_UPDATED_BY,SUPPORTING_DOC_ID,ATTRIBUTE_VALUE) 
VALUES (6189185,63,SYSDATE,null,SYSDATE,'System',null,'Income');
