-- New columns in Contribution table, used for gov. matched contribution refs
-- and determining when payment was processed
ALTER TABLE CONTRIBUTION ADD (
  MATCHED_CONTRIBUTION_ID Number(15,0),
  DATE_CASH_PROCESSED Timestamp(6)
)
/

-- TODO: Populate DATE_CASH_PROCESSED column.

COMMENT ON COLUMN CCLA.CONTRIBUTION.MATCHED_CONTRIBUTION_ID IS 'When a government Matched contribution payment is received the reference will be updated to show the original contribution'
/

-- Self-referencing FK
CREATE INDEX CONTRIB_MATCHED_CONTRIB_IX ON CCLA.CONTRIBUTION (MATCHED_CONTRIBUTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CONTRIB_MATCHED_CONTRIB_FK FOREIGN KEY (MATCHED_CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/


-- Table CCLA.REF_RPI

CREATE TABLE CCLA.REF_RPI(
  RPI_ID Number(15,0) NOT NULL,
  RPI_AMOUNT Number(7,4) NOT NULL,
  RPI_START_DATE Date NOT NULL,
  RPI_END_DATE Date NOT NULL
)
/

-- Add keys for table CCLA.REF_RPI

ALTER TABLE CCLA.REF_RPI ADD CONSTRAINT RPI_PK PRIMARY KEY (RPI_ID)
/

CREATE OR REPLACE PUBLIC SYNONYM REF_RPI FOR CCLA.REF_RPI;
GRANT ALL ON REF_RPI TO UCMADMIN;

ALTER TABLE CCLA.SUBSCRIPTION ADD (
	RPI_ID Number(15,0),
	DATE_FORM_RECEIVED Timestamp(6),
	DATE_CASH_PROCESSED Timestamp(6)
);


ALTER TABLE CCLA.SUBSCRIPTION DROP COLUMN RPI;

-- TODO: Populate RPI? No values in there ATM.

-- Key from RPI to Subscription table
CREATE INDEX RPI_SUBSCRIPTION_IX ON CCLA.SUBSCRIPTION (RPI_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT RPI_SUBSCRIPTION_FK FOREIGN KEY (RPI_ID) REFERENCES CCLA.REF_RPI (RPI_ID)
/

-- New Type/Status
INSERT INTO REF_SUBSCRIPTION_TYPE VALUES (4, 'Government Match');
INSERT INTO REF_SUBSCRIPTION_STATUS VALUES (7, 'Cash Received');

-- TODO: update subscriptions to reflect where cash has been processed.
-- Must be done manually for now, please consult Tina Gardner for this.

-- Query below SHOULD match subscriptions to their equivalent DEPBNK instruction,
-- but the matching is done based on Cash Amount.
SELECT subs.SUBSCRIPTION_ID, ins.INSTRUCTION_ID, ins.PROCESS_DATE FROM SUBSCRIPTION subs
INNER JOIN (
  SELECT ins.*, insDepBnk.DEPOSIT_AMOUNT FROM INSTRUCTION ins INNER JOIN (

    SELECT MAX(ins.INSTRUCTION_ID) AS INSTRUCTION_ID, insAmount.INSTRUCTION_NUM_VALUE AS DEPOSIT_AMOUNT 
    FROM INSTRUCTION ins
    
    -- Link where Org ID = 'CDF'
    INNER JOIN V_INSTRUCTION_DATA_VALUE insOrg ON (
      ins.INSTRUCTION_ID = insOrg.INSTRUCTION_ID
      AND
      insOrg.INSTRUCTION_DATA_ID = 9
      AND 
      insOrg.INSTRUCTION_NUM_VALUE = 6189184
    )
    
    INNER JOIN V_INSTRUCTION_DATA_VALUE insAcc ON (
      ins.INSTRUCTION_ID = insAcc.INSTRUCTION_ID
      AND
      insAcc.INSTRUCTION_DATA_ID = 1
      AND 
      insAcc.INSTRUCTION_NUM_VALUE = 6189186
    )
    
    INNER JOIN V_INSTRUCTION_DATA_VALUE insAmount ON (
      ins.INSTRUCTION_ID = insAmount.INSTRUCTION_ID
      AND
      insAmount.INSTRUCTION_DATA_ID = 3
    )
    
    WHERE ins.INSTRUCTION_TYPE_ID = 49 -- DEPBNK
    AND ins.INSTRUCTION_STATUS_ID = 10 -- 'Released to Workflow'
    
    GROUP BY insAmount.INSTRUCTION_NUM_VALUE
  ) insDepBnk ON (ins.INSTRUCTION_ID = insDepBnk.INSTRUCTION_ID)
  
) ins ON (ins.DEPOSIT_AMOUNT = subs.SUBSCRIPTION_AMOUNT);

-- TODO: update subscriptions to reflect date form was returned.
UPDATE CCLA.SUBSCRIPTION subs SET DATE_FORM_RECEIVED = (SELECT DATE_RETURNED
  FROM (
    SELECT FORM_ID, SUBSCRIPTION_ID, DATE_RETURNED FROM FORM WHERE FORM_ID IN (
      SELECT MAX(FORM_ID) FROM FORM frm
      WHERE SUBSCRIPTION_ID IS NOT NULL
      AND DATE_RETURNED IS NOT NULL
      GROUP BY SUBSCRIPTION_ID
    )
  ) frm WHERE frm.SUBSCRIPTION_ID = subs.SUBSCRIPTION_ID
);

-- New UCM metadata translation for xPaymentRef field
INSERT INTO REF_UCM_METADATA_TRANSLATION VALUES (35, 'xPaymentRef', NULL);

-- Add existing NARRATIVE instr data field as optional field for BUYBNK, 
-- DEPBNK, DICONDIN etc
INSERT INTO APPLICABLE_INSTRUCTION_DATA
SELECT SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 35, INSTRUCTION_TYPE_ID, 1 
FROM REF_INSTRUCTION_TYPE WHERE INSTRUCTION_TYPE_ID IN  (14,49,113,123,125);