/*
Created: 01/11/2010
Modified: 01/02/2012
Project: CCLA 
Model: Central Database
Company: Kainos Software
Author: Donna Hull
Version: 8.0
Database: Oracle 11g Release 1
*/

-- Create tables section -------------------------------------------------

-- Table CCLA.INVESTMENT

CREATE TABLE CCLA.INVESTMENT(
  INVESTMENT_ID Number(15,0) NOT NULL,
  ACCOUNT_ID Number(15,0) NOT NULL,
  INVESTMENT_TYPE_ID Number(15,0),
  INVESTMENT_AMOUNT Float,
  RPI Number(7,4)
        CONSTRAINT INVESTMENT_RPI_CK CHECK (RPI BETWEEN 0 AND 100),
  INVESTMENT_DATE Date,
  INVESTMENT_PAYMENT_REF Char(18 ),
  DATE_ADDED Timestamp(6) CONSTRAINT INVEST_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT INVEST_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/

-- Create indexes for table CCLA.INVESTMENT

CREATE UNIQUE INDEX CCLA.IX_INVEST_INVESTREF ON CCLA.INVESTMENT (INVESTMENT_PAYMENT_REF)
/

-- Add keys for table CCLA.INVESTMENT

ALTER TABLE CCLA.INVESTMENT ADD CONSTRAINT INVESTMENT_PK PRIMARY KEY (INVESTMENT_ID)
/

-- Table and Columns comments section
  
COMMENT ON COLUMN CCLA.INVESTMENT.INVESTMENT_PAYMENT_REF IS 'An Investment Reference number that can be used to identlfy an Orgs payments (e.g. 12 character OrgAccountCode plus a payment number, such as AWPF00123456-00010'
/
COMMENT ON COLUMN CCLA.INVESTMENT.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.INVESTMENT.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

-- Table CCLA.REF_INVESTMENT_TYPE

CREATE TABLE CCLA.REF_INVESTMENT_TYPE(
  INVESTMENT_TYPE_ID Number(15,0) NOT NULL,
  INVESTMENT_NAME Char(50 ) NOT NULL
)
/

-- Add keys for table CCLA.REF_INVESTMENT_TYPE

ALTER TABLE CCLA.REF_INVESTMENT_TYPE ADD CONSTRAINT INVESTMENT_TYPE_PK PRIMARY KEY (INVESTMENT_TYPE_ID)
/

-- Table CCLA.DONATION

CREATE TABLE CCLA.DONATION(
  DONATION_ID Number(15,0) NOT NULL,
  INVESTMENT_ID Number(15,0) NOT NULL,
  DONOR_ID Number(15,0) NOT NULL,
  DONATION_AMOUNT Float,
  GOV_RECOVERY_AMT_EXPECTED Float,
  GOV_RECOVERY_AMT_ACTUAL Float,
  DATE_ADDED Timestamp(6) CONSTRAINT DONATION_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT DONATION_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/

-- Create indexes for table CCLA.DONATION

CREATE UNIQUE INDEX CCLA.DONATION_UQ_I ON CCLA.DONATION (DONOR_ID,INVESTMENT_ID)
/

-- Add keys for table CCLA.DONATION

ALTER TABLE CCLA.DONATION ADD CONSTRAINT Key42 PRIMARY KEY (DONATION_ID)
/

-- Table and Columns comments section
  
COMMENT ON COLUMN CCLA.DONATION.DONATION_AMOUNT IS 'The amount of the donation'
/
COMMENT ON COLUMN CCLA.DONATION.GOV_RECOVERY_AMT_EXPECTED IS 'The expected amount the government will pay against the value of the investment - i.e. 100%'
/
COMMENT ON COLUMN CCLA.DONATION.GOV_RECOVERY_AMT_ACTUAL IS 'The actual  amount the government has paid against the total value of the donation.'
/
COMMENT ON COLUMN CCLA.DONATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.DONATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

-- Table CCLA.INVESTMENT_FUND_ALLOCATION

CREATE TABLE CCLA.INVESTMENT_FUND_ALLOCATION(
  INVESTMENT_FUND_ALLOCATION_ID Number(15,0) NOT NULL,
  INVESTMENT_ID Number(15,0) NOT NULL,
  FUND_CODE Varchar2(2 CHAR) NOT NULL,
  DONATION_FUND_AMOUNT Float NOT NULL,
  DATE_ADDED Timestamp(6) CONSTRAINT INVFNDALLOC_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT INVFNDALLOC_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/

-- Add keys for table CCLA.INVESTMENT_FUND_ALLOCATION

ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION ADD CONSTRAINT INVESTMENT_FUND_ALLOCATION_PK PRIMARY KEY (INVESTMENT_FUND_ALLOCATION_ID)
/

-- Table and Columns comments section
  
COMMENT ON COLUMN CCLA.INVESTMENT_FUND_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.INVESTMENT_FUND_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

-- Table CCLA.DONATION_TTLA_ALLOCATION

CREATE TABLE CCLA.DONATION_TTLA_ALLOCATION(
  DONATION_TTLA_ALLOCATION_ID Number(15,0) NOT NULL,
  DONATION_ID Number(15,0) NOT NULL,
  TTLA_ORG_ID Number(15,0),
  INCOME_ALLOCATION_PERCENT Number(7,4)
        CONSTRAINT INCOME_ALLOCATION_PERCENT_CK CHECK (INCOME_ALLOCATION_PERCENT BETWEEN 0 AND 100),
  DATE_ADDED Timestamp(6) CONSTRAINT DONTTLAALLOC_DATEADDED_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT DONTTLAALLOC_LASTUPDATED_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/

-- Add keys for table CCLA.DONATION_TTLA_ALLOCATION

ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION ADD CONSTRAINT DONATIONTTLAALLOCATION_PK PRIMARY KEY (DONATION_TTLA_ALLOCATION_ID)
/

-- Table and Columns comments section
  
COMMENT ON COLUMN CCLA.DONATION_TTLA_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/
COMMENT ON COLUMN CCLA.DONATION_TTLA_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

-- Create relationships section ------------------------------------------------- 

CREATE INDEX IX_ACCOUNT_INVESTMENT_FK ON CCLA.INVESTMENT (ACCOUNT_ID) 
/
ALTER TABLE CCLA.INVESTMENT ADD CONSTRAINT ACCOUNT_INVESTMENT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES CCLA.ACCOUNT (ACCOUNT_ID)
/

CREATE INDEX IX_INVESTTYPE_INVEST_FK ON CCLA.INVESTMENT (INVESTMENT_TYPE_ID) 
/
ALTER TABLE CCLA.INVESTMENT ADD CONSTRAINT INVESTTYPE_INVEST_FK FOREIGN KEY (INVESTMENT_TYPE_ID) REFERENCES CCLA.REF_INVESTMENT_TYPE (INVESTMENT_TYPE_ID)
/

CREATE INDEX IX_INVESTMENT_DONATION_FK ON CCLA.DONATION (INVESTMENT_ID) 
/
ALTER TABLE CCLA.DONATION ADD CONSTRAINT INVESTMENT_DONATION_FK FOREIGN KEY (INVESTMENT_ID) REFERENCES CCLA.INVESTMENT (INVESTMENT_ID)
/

CREATE INDEX IX_ELEMENT_DONATION_FK ON CCLA.DONATION (DONOR_ID) 
/
ALTER TABLE CCLA.DONATION ADD CONSTRAINT ELEMENT_DONATION_FK FOREIGN KEY (DONOR_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/

CREATE INDEX IX_USERS_INVESTMENT_FK ON CCLA.INVESTMENT (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.INVESTMENT ADD CONSTRAINT USERS_INVESTMENT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES UCMADMIN.USERS (DNAME)
/

CREATE INDEX IX_USERS_DONATION_FK ON CCLA.DONATION (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.DONATION ADD CONSTRAINT USERS_DONATION_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES UCMADMIN.USERS (DNAME)
/

CREATE INDEX IX_INVEST_INVESTFUNDALLOC_FK ON CCLA.INVESTMENT_FUND_ALLOCATION (INVESTMENT_ID) 
/
ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION ADD CONSTRAINT INVEST_INVESTFUNDALLOC_FK FOREIGN KEY (INVESTMENT_ID) REFERENCES CCLA.INVESTMENT (INVESTMENT_ID)
/

CREATE INDEX IX_FNDINVESTT_FNDALLOC_FK ON CCLA.INVESTMENT_FUND_ALLOCATION (FUND_CODE) 
/
ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION ADD CONSTRAINT FUND_INVESTFUNDALLOC_FK FOREIGN KEY (FUND_CODE) REFERENCES CCLA.FUND (FUND_CODE)
/

CREATE INDEX IX_USERS_INVESTFNDALLOC_FK ON CCLA.INVESTMENT_FUND_ALLOCATION (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.INVESTMENT_FUND_ALLOCATION ADD CONSTRAINT USERS_INVESTFUNDALLOC_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES UCMADMIN.USERS (DNAME)
/

CREATE INDEX IX_USERS_DONTTLAALLOC_FK ON CCLA.DONATION_TTLA_ALLOCATION (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION ADD CONSTRAINT USERS_DONtTLAALLOC_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES UCMADMIN.USERS (DNAME)
/

CREATE INDEX IX_DON_DONTTLAALLOC_FK ON CCLA.DONATION_TTLA_ALLOCATION (DONATION_ID) 
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION ADD CONSTRAINT DON_DONTTLAALLOC_FK FOREIGN KEY (DONATION_ID) REFERENCES CCLA.DONATION (DONATION_ID)
/

CREATE INDEX IX_ELEMENT_DONTTLAALLOC_FK ON CCLA.DONATION_TTLA_ALLOCATION (TTLA_ORG_ID) 
/
ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION ADD CONSTRAINT ELEMENT_DONTTLAALLOC_FK FOREIGN KEY (TTLA_ORG_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/

ALTER TABLE CCLA.DONATION_TTLA_ALLOCATION ADD CONSTRAINT TTLAALLOC_UQ UNIQUE (DONATION_ID,TTLA_ORG_ID)
/

-- Alter tables section -------------------------------------------------
--CCLA.FUND
ALTER TABLE CCLA.FUND ADD (COMMUNITY_FIRST_IS_ELIGIBLE Integer DEFAULT 0);

--CCLA.ACCOUNT
ALTER TABLE CCLA.ACCOUNT ADD CONSTRAINT ACCOUNT_FUND_CK CHECK 
    (FUND_CODE IS NOT NULL 
     OR 
    (FUND_CODE IS NULL AND ACCOUNT_STATUS_ID = 4));


COMMENT ON COLUMN CCLA.FUND.COMMUNITY_FIRST_IS_ELIGIBLE IS 'indicates if fund is available for community first investment.  (0 = Not eligible, 1 = Eligible, Default value is 0)'
/

CREATE SEQUENCE SEQ_INVESTMENT;
CREATE SEQUENCE SEQ_INVESTMENT_FUND_ALLOCATION;
CREATE SEQUENCE SEQ_DONATION;
CREATE SEQUENCE SEQ_DONATION_TTLA_ALLOCATION;

-- TM: Grants and synonyms
CREATE OR REPLACE PUBLIC SYNONYM INVESTMENT FOR CCLA.INVESTMENT;
CREATE OR REPLACE PUBLIC SYNONYM REF_INVESTMENT_TYPE FOR CCLA.REF_INVESTMENT_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM DONATION FOR CCLA.DONATION;
CREATE OR REPLACE PUBLIC SYNONYM INVESTMENT_FUND_ALLOCATION FOR CCLA.INVESTMENT_FUND_ALLOCATION;
CREATE OR REPLACE PUBLIC SYNONYM DONATION_TTLA_ALLOCATION FOR CCLA.DONATION_TTLA_ALLOCATION;

CREATE OR REPLACE PUBLIC SYNONYM SEQ_INVESTMENT FOR CCLA.SEQ_INVESTMENT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INVESTMENT_FUND_ALLOCATION FOR CCLA.SEQ_INVESTMENT_FUND_ALLOCATION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_DONATION FOR CCLA.SEQ_DONATION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_DONATION_TTLA_ALLOCATION FOR CCLA.SEQ_DONATION_TTLA_ALLOCATION;

GRANT ALL ON INVESTMENT TO UCMADMIN;
GRANT ALL ON REF_INVESTMENT_TYPE TO UCMADMIN;
GRANT ALL ON DONATION TO UCMADMIN;
GRANT ALL ON INVESTMENT_FUND_ALLOCATION TO UCMADMIN;
GRANT ALL ON DONATION_TTLA_ALLOCATION TO UCMADMIN;

GRANT ALL ON SEQ_INVESTMENT TO UCMADMIN;
GRANT ALL ON SEQ_INVESTMENT_FUND_ALLOCATION TO UCMADMIN;
GRANT ALL ON SEQ_DONATION TO UCMADMIN;
GRANT ALL ON SEQ_DONATION_TTLA_ALLOCATION TO UCMADMIN;

-- TM: data import
-- ----------------------------------------------

-- Add new ACCOUNT_TYPE
INSERT INTO REF_ACCOUNT_TYPE VALUES (4, 'Community First', 'Pooled donations for Community First initiative');

-- Add Investment Types
INSERT INTO REF_INVESTMENT_TYPE VALUES (1, 'Qualifies for Gov. Match');
INSERT INTO REF_INVESTMENT_TYPE VALUES (2, 'Gift Aid (added to endowment)');
INSERT INTO REF_INVESTMENT_TYPE VALUES (3, 'Gift Aid (grants and social investments)');

-- Add new TTLA Element Attribute
INSERT INTO REF_ELEMENT_ATTRIBUTES VALUES 
(62, 'Top-Tier LA', 1, 'Top-Tier Local Authority',1,null,null,null,'BOOL',6);

-- Add new Org Category Name/Category
INSERT INTO REF_ORG_CATEGORY_NAME VALUES (306, 'Top-Tier Local Authority');
INSERT INTO REF_ORG_CATEGORY VALUES (1056, null, 'None', null, 306);

-- Set Comm First Eligibility to zero for all Funds
UPDATE FUND SET COMMUNITY_FIRST_IS_ELIGIBLE = 0;
-- Set Comm First Eligibility on all COIF Income Funds
UPDATE FUND SET COMMUNITY_FIRST_IS_ELIGIBLE = 1 WHERE COMPANY_ID = 1 AND INCOME_TYPECODE_ID = 1;

-- New 'Donor' relationships

-- Org-Person Donor
INSERT INTO REF_RELATION_NAMES VALUES (13,1,'Donor','Dnr',0);
-- Org-Org Donor
INSERT INTO REF_RELATION_NAMES VALUES (140, 4, 'Donor','Dnr',0);

-- New CF Fund Code
REM INSERTING into FUND
Insert into FUND (FUND_CODE,COMPANY_ID,FUND_STATUS_ID,FUND_TYPECODE_ID,INCOME_TYPECODE_ID,FUND_NAME,OPENINGDATE,DISPLAYNAME,CHAPSCODE,FUNDGROUPID,LAST_UPDATED,FUND_SHORT_NAME,FUND_DEFCODE_ID,COMMUNITY_FIRST_IS_ELIGIBLE) values ('CF','1',1,2,1,'COMMUNITY FIRST DONATION POOL',null,'Community First Donation Pool',null,null,null,null,1,0);

-- ADD INVESTMENT_ID to form table
ALTER TABLE FORM
ADD INVESTMENT_ID Number(15,0);

CREATE INDEX INVESTMENT_FORM_IX ON FORM (INVESTMENT_ID) 
/
ALTER TABLE FORM ADD CONSTRAINT INVESTMENT_FORM_FK FOREIGN KEY (INVESTMENT_ID) REFERENCES CCLA.INVESTMENT (INVESTMENT_ID)
/


-- New temp table to store TTLA Org Names
CREATE TABLE TTLA_ORGS_TEMP (
  ORGANISATION_NAME VARCHAR2(200 CHAR)
);

CREATE OR REPLACE PUBLIC SYNONYM TTLA_ORGS_TEMP FOR CCLA.TTLA_ORGS_TEMP;
GRANT ALL ON TTLA_ORGS_TEMP TO UCMADMIN;

-- Temp table data fill.
REM INSERTING into TTLA_ORGS_TEMP
SET ESCAPE ON;
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Barking and Dagenham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Barnet');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Barnsley');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bath \& North East Somerset');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bedford');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bexley');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Birmingham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Blackburn with Darwen');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Blackpool');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bolton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bournemouth');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bracknell Forest');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bradford');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Brent');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Brighton and Hove');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bristol, City of');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bromley');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Buckinghamshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Bury');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Calderdale');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Cambridgeshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Camden');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Central Bedfordshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Cheshire East');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Cheshire West and Chester');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('City of London Corporation');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Cornwall');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('County Durham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Coventry');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Croydon');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Cumbria');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Darlington');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Derby');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Derbyshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Devon');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Doncaster');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Dorset');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Dudley');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Ealing');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('East Riding of Yorkshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('East Sussex');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Enfield');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Essex');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Gateshead');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Gloucestershire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Greenwich');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hackney');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Halton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hammersmith and Fulham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hampshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Haringey');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Harrow');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hartlepool');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Havering');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Herefordshire, County of');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hertfordshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hillingdon');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Hounslow');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Isle of Wight');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Isles of Scilly');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Islington');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Kensington and Chelsea');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Kent');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Kingston upon Thames');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Kingston upon Hull, City of');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Kirklees');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Knowsley');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Lambeth');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Lancashire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Leeds');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Leicester');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Leicestershire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Lewisham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Lincolnshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Liverpool');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Luton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Manchester');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Medway');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Merton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Middlesbrough');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Milton Keynes');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Newcastle upon Tyne');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Newham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Norfolk');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('North East Lincolnshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('North Lincolnshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('North Somerset');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('North Tyneside');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('North Yorkshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Northamptonshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Northumberland');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Nottingham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Nottinghamshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Oldham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Oxfordshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Peterborough');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Plymouth');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Poole');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Portsmouth');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Reading');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Redbridge');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Redcar and Cleveland');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Richmond upon Thames');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Rochdale');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Rotherham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Rutland');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Salford');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Sandwell');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Sefton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Sheffield');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Shropshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Slough');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Solihull');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Somerset');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('South Gloucestershire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('South Tyneside');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Southampton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Southend-on-Sea');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Southwark');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('St Helens');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Staffordshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Stockport');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Stockton-on-Tees');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Stoke-on-Trent');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Suffolk');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Sunderland');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Surrey');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Sutton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Swindon');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Tameside');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Telford and Wrekin');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Thurrock');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Torbay');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Tower Hamlets');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Trafford');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wakefield');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Walsall');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Waltham Forest');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wandsworth');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Warrington');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Warwickshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('West Berkshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('West Sussex');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Westminster');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wigan');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wiltshire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Windsor and Maidenhead');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wirral');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wokingham');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Wolverhampton');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('Worcestershire');
Insert into TTLA_ORGS_TEMP (ORGANISATION_NAME) values ('York');
SET ESCAPE OFF;


