-- ---------------------------
-- NOTE: Backup SUBSCRIPTION, CONTRIBUTION, CONTRIBUTION_TTLA_ALLOCATION and CONTRIBUTION_FUND_ALLOCATION
-- before continuing!
-- ---------------------------

-- New table: REF_PRODUCT
CREATE TABLE CCLA.REF_PRODUCT(
  PRODUCT_ID Number(15,0) NOT NULL,
  PRODUCT_NAME Varchar2(50 )
)
/

ALTER TABLE CCLA.REF_PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
/

COMMENT ON TABLE CCLA.REF_PRODUCT IS 'Financial/investment products offered by CCLA'
/

-- Add single Product for now
INSERT INTO REF_PRODUCT VALUES (1, 'Community First');



ALTER TABLE FORM DROP CONSTRAINT SUBSCRIPTION_FORM_FK
/
DROP INDEX SUBSCRIPTION_FORM_IX
/

ALTER TABLE CCLA.CONTRIBUTION DROP CONSTRAINT SUBSCRIPTION_DONATION_FK
/
DROP INDEX IX_INVESTMENT_DONATION_FK
/

ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT SUBTYPE_SUB_FK
/
DROP INDEX IX_INVESTTYPE_INVEST_FK
/

ALTER TABLE CCLA.CONTRIBUTION DROP CONSTRAINT ELEMENT_CONTRIBUTION_FK
/
DROP INDEX IX_ELEMENT_DONATION_FK
/

DROP INDEX CONTRIBFUNDALLOC_UQ_I
/

--ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION DROP CONSTRAINT CONTRIBFUNDALLOC_UQ
--/

ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION DROP CONSTRAINT CONTRIBFUNDALLOC_PK
/

--DROP TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION
--/

ALTER TABLE CCLA.REF_SUBSCRIPTION_TYPE DROP CONSTRAINT INVESTMENT_TYPE_PK
/

--DROP TABLE CCLA.REF_SUBSCRIPTION_TYPE
--/


ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT RPI_SUBSCRIPTION_FK
/



ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION DROP CONSTRAINT USERS_DONtTLAALLOC_FK
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION DROP CONSTRAINT CONTR_CONTRTTLAALLOC_FK
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION DROP CONSTRAINT ELEMENT_CONTRTTLAALLOC_FK
/
CREATE TABLE CCLA.CONTRIBUTION_TTLA_ALLOCAT_EDDB(
  CONTRIB_TTLA_ALLOCATION_ID Number(15,0) NOT NULL,
  CONTRIBUTION_ID Number(15,0) NOT NULL,
  TTLA_ORG_ID Number(15,0),
  PRODUCT_ID Number(15,0),
  INCOME_ALLOCATION_AMOUNT Number(15,2),
  INCOME_ALLOCATION_PERCENT Number(13,10),
  GOV_MATCH_LIMIT_ID Number(15,0),
  GOV_MATCH_RATE_ID Number(15,0),
  GOV_RECOVERY_AMT_EXPECTED Number(15,2),
  GOV_RECOVERY_AMT_ACTUAL Number(15,2),
  START_DATE Timestamp(6),
  END_DATE Timestamp(6),
  DATE_ADDED Timestamp(6),
  LAST_UPDATED Timestamp(6),
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/

--DROP TABLE CONTRIBUTION_TTLA_ALLOCAT_EDDB;

INSERT INTO CCLA.CONTRIBUTION_TTLA_ALLOCAT_EDDB (CONTRIB_TTLA_ALLOCATION_ID, CONTRIBUTION_ID, TTLA_ORG_ID, INCOME_ALLOCATION_AMOUNT, INCOME_ALLOCATION_PERCENT, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY) SELECT CONTRIB_TTLA_ALLOCATION_ID, CONTRIBUTION_ID, TTLA_ORG_ID, INCOME_ALLOCATION_AMOUNT, INCOME_ALLOCATION_PERCENT, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY FROM CCLA.CONTRIBUTION_TTLA_ALLOCATION
/

SELECT * FROM CONTRIBUTION_TTLA_ALLOCAT_EDDB;

DROP INDEX CCLA.CONTRIBUTION_UQ_I
/

ALTER TABLE CCLA.CONTRIBUTION DROP CONSTRAINT SUBSCRIPTION_DONATION_FK
/
ALTER TABLE CCLA.CONTRIBUTION DROP CONSTRAINT USERS_DONATION_FK
/
ALTER TABLE CCLA.CONTRIBUTION_FUND_ALLOCATION DROP CONSTRAINT CONTRIB_CONTRIBFUNDALLOC_FK
/
ALTER TABLE CCLA.CONTRIBUTION DROP CONSTRAINT CONTRIB_MATCHED_CONTRIB_FK
/
CREATE TABLE CCLA.CONTRIBUTION_45FDEB273FEA4FB4B(
  CONTRIBUTION_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_ID Number(15,0),
  CONTRIBUTOR_ID Number(15,0),
  BENEFACTOR_ID Number(15,0),
  CONTRIBUTION_TYPE_ID Number(15,0),
  CONTRIBUTION_PAYMENT_REF Varchar2(18 ),
  CONTRIBUTION_AMOUNT Number(15,2),
  CONTRIBUTION_PERCENT Number(13,10),
  MATCHED_CONTRIBUTION_ID Number(15,0),
  RPI_ID Number(15,0),
  PRODUCT_ID Number(15,0),
  CAMPAIGN_ID Number(15,0),
  FORM_ID Number(15,0),
  DATE_LATEST_CASH_PROCESSED Timestamp(6),
  DATE_COMPLETED Timestamp(6),
  START_DATE Timestamp(6),
  END_DATE Timestamp(6),
  DATE_ADDED Timestamp(6),
  LAST_UPDATED Timestamp(6),
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/
INSERT INTO CCLA.CONTRIBUTION_45FDEB273FEA4FB4B (CONTRIBUTION_ID, SUBSCRIPTION_ID, CONTRIBUTION_AMOUNT, MATCHED_CONTRIBUTION_ID, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY) SELECT CONTRIBUTION_ID, SUBSCRIPTION_ID, CONTRIBUTION_AMOUNT, MATCHED_CONTRIBUTION_ID, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY FROM CCLA.CONTRIBUTION
/

SELECT * FROM CONTRIBUTION_45FDEB273FEA4FB4B;

--ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT INVESTMENT_RPI_CK
--/


ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT ACCOUNT_INVESTMENT_FK
/
ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT USERS_INVESTMENT_FK
/
--ALTER TABLE FORM DROP CONSTRAINT INVESTMENT_FORM_FK
--/
ALTER TABLE CCLA.SUBSCRIPTION DROP CONSTRAINT SUBSTATUS_SUBS_FK
/
CREATE TABLE CCLA.SUBSCRIPTION_50EA232B32FE44908(
  SUBSCRIPTION_ID Number(15,0) NOT NULL,
  ACCOUNT_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_STATUS_ID Number(15,0),
  SUBSCRIPTION_AMOUNT Number(15,2),
  SUBSCRIPTION_DATE Timestamp(6),
  SUBSCRIPTION_PAYMENT_REF Char(18 ),
  DATE_FORM_RECEIVED Timestamp(6),
  DATE_LATEST_CASH_PROCESSED Timestamp(6),
  DATE_COMPLETED Timestamp(6),
  START_DATE Timestamp(6),
  END_DATE Timestamp(6),
  PRODUCT_ID Number(15,0),
  DATE_ADDED Timestamp(6),
  LAST_UPDATED Timestamp(6),
  LAST_UPDATED_BY Varchar2(50 ) NOT NULL
)
/
INSERT INTO CCLA.SUBSCRIPTION_50EA232B32FE44908 (SUBSCRIPTION_ID, ACCOUNT_ID, SUBSCRIPTION_STATUS_ID, SUBSCRIPTION_AMOUNT, SUBSCRIPTION_DATE, SUBSCRIPTION_PAYMENT_REF, DATE_FORM_RECEIVED, DATE_LATEST_CASH_PROCESSED, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY) SELECT SUBSCRIPTION_ID, ACCOUNT_ID, SUBSCRIPTION_STATUS_ID, SUBSCRIPTION_AMOUNT, SUBSCRIPTION_DATE, SUBSCRIPTION_PAYMENT_REF, DATE_FORM_RECEIVED, DATE_CASH_PROCESSED, DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY FROM CCLA.SUBSCRIPTION
/

--DELETE FROM SUBSCRIPTION_50EA232B32FE44908;
SELECT * FROM SUBSCRIPTION_50EA232B32FE44908;

-- Add Contribution Type values to new Contribution table
UPDATE CONTRIBUTION_45FDEB273FEA4FB4B newContrib SET CONTRIBUTION_TYPE_ID = (
  SELECT subs.SUBSCRIPTION_TYPE_ID FROM CONTRIBUTION contrib
  INNER JOIN SUBSCRIPTION subs ON (contrib.SUBSCRIPTION_ID = subs.SUBSCRIPTION_ID)
  WHERE newContrib.CONTRIBUTION_ID = contrib.CONTRIBUTION_ID
);

-- Rename old Subscription table
ALTER TABLE CCLA.SUBSCRIPTION RENAME TO SUBSCRIPTION_OLD
/

-- Remove remaining constraints
ALTER TABLE CCLA.SUBSCRIPTION_OLD DROP CONSTRAINT SUBS_SUBSTATUS_NN;
ALTER TABLE CCLA.SUBSCRIPTION_OLD DROP CONSTRAINT SUBSCRIPTION_PK;
DROP INDEX IX_SUB_SUBREF;

ALTER TABLE CCLA.SUBSCRIPTION_50EA232B32FE44908 RENAME TO SUBSCRIPTION
/

-- Set PRODUCT_ID values against subscriptions
UPDATE CCLA.SUBSCRIPTION SET PRODUCT_ID = 1;

ALTER TABLE CCLA.SUBSCRIPTION MODIFY (SUBSCRIPTION_STATUS_ID CONSTRAINT SUBS_SUBSTATUS_NN NOT NULL)
/
ALTER TABLE CCLA.SUBSCRIPTION MODIFY (DATE_ADDED CONSTRAINT SUBS_DATEADDED_NN NOT NULL)
/
ALTER TABLE CCLA.SUBSCRIPTION MODIFY (LAST_UPDATED CONSTRAINT SUBS_LASTUPDATED_NN NOT NULL)
/

CREATE UNIQUE INDEX CCLA.IX_SUB_SUBREF ON CCLA.SUBSCRIPTION (SUBSCRIPTION_PAYMENT_REF)
/

ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY (SUBSCRIPTION_ID)
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.SUBSCRIPTION_PAYMENT_REF IS 'A Subscription Reference number that can be used to identlfy an Orgs payments (e.g. 12 character OrgAccountCode plus a payment number, such as AWPF00123456-00010'
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.DATE_FORM_RECEIVED IS 'Date/time the subscription form was received or acknowledged'
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.DATE_LATEST_CASH_PROCESSED IS 'Date/time the latest subscription payment was processed. Doesn''t imply the subscription has been fully paid'
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.DATE_COMPLETED IS 'Date that the subscription was fulfilled, i.e. all contribution payments have been made'
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.DATE_ADDED IS 'The Date / Time this entity was added.'
/

COMMENT ON COLUMN CCLA.SUBSCRIPTION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

SELECT * FROM CONTRIBUTION;

ALTER TABLE CCLA.CONTRIBUTION RENAME TO CONTRIBUTION_OLD
/

-- Remove remaining constraints from CONTRIBUTION_OLD
ALTER TABLE CCLA.CONTRIBUTION_OLD DROP CONSTRAINT DONATION_DATEADDED_NN;
ALTER TABLE CCLA.CONTRIBUTION_OLD DROP CONSTRAINT DONATION_LASTUPDATED_NN;
ALTER TABLE CCLA.CONTRIBUTION_OLD DROP CONSTRAINT CONTRIBUTION_PK;

ALTER TABLE CCLA.CONTRIBUTION_45FDEB273FEA4FB4B RENAME TO CONTRIBUTION
/

/* Add missing data to new Contribution columns: 
   -CONTRIBUTOR_ID
   -CONTRIBUTION_PERCENT
   -PRODUCT_ID
   -CAMPAIGN_ID
   -FORM_ID
   -BENEFACTOR_ID
*/

-- Add CONTRIBUTOR_ID values
UPDATE CONTRIBUTION contrib SET CONTRIBUTOR_ID = (
  SELECT DONOR_ID FROM CONTRIBUTION_OLD oldContrib
  WHERE oldContrib.CONTRIBUTION_ID = contrib.CONTRIBUTION_ID
);


-- Sets Product and Campaign values
UPDATE CONTRIBUTION SET PRODUCT_ID = 1, CAMPAIGN_ID = 13;

-- Sets Benefactor value
UPDATE CONTRIBUTION newContrib SET BENEFACTOR_ID = (
  SELECT acc.ORGANISATION_ID FROM CONTRIBUTION contrib 
  INNER JOIN SUBSCRIPTION subs ON (contrib.SUBSCRIPTION_ID = subs.SUBSCRIPTION_ID)
  INNER JOIN V_ACCOUNT_EXTENDED_CLIENT acc ON (subs.ACCOUNT_ID = acc.ACCOUNT_ID)
  WHERE contrib.CONTRIBUTION_ID = newContrib.CONTRIBUTION_ID
);

-- Calculate and set percentage values, as fractions of the parent subscription amount
UPDATE CONTRIBUTION newContrib SET (CONTRIBUTION_PERCENT) = (
  SELECT 
  --contrib.CONTRIBUTION_AMOUNT, 
  --subs.SUBSCRIPTION_AMOUNT,
  TO_NUMBER(TRIM(TO_CHAR(((contrib.CONTRIBUTION_AMOUNT*100)/subs.SUBSCRIPTION_AMOUNT), 
          '9990.9999999999'))) AS CONTRIBUTION_PERCENT 
  FROM CONTRIBUTION contrib
  INNER JOIN SUBSCRIPTION subs ON (subs.SUBSCRIPTION_ID = contrib.SUBSCRIPTION_ID)
  WHERE contrib.CONTRIBUTION_ID = newContrib.CONTRIBUTION_ID
);


ALTER TABLE CCLA.CONTRIBUTION MODIFY (SUBSCRIPTION_ID CONSTRAINT CONTRIB_SUBS_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION MODIFY (BENEFACTOR_ID CONSTRAINT CONTRIB_BEN_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION MODIFY (CONTRIBUTION_TYPE_ID CONSTRAINT CONTRIB_TYPE_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION MODIFY (DATE_ADDED CONSTRAINT DONATION_DATEADDED_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION MODIFY (LAST_UPDATED CONSTRAINT DONATION_LASTUPDATED_NN NOT NULL)
/

CREATE UNIQUE INDEX CCLA.CONTRIBUTION_UQ_I ON CCLA.CONTRIBUTION (CONTRIBUTOR_ID,SUBSCRIPTION_ID)
/

ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CONTRIBUTION_PK PRIMARY KEY (CONTRIBUTION_ID)
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.CONTRIBUTION_PAYMENT_REF IS 'Contribution-specific Payment Reference.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.CONTRIBUTION_AMOUNT IS 'The amount of the donation'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.CONTRIBUTION_PERCENT IS 'Percentage of this contribution with respect to the total Subscription amount'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.MATCHED_CONTRIBUTION_ID IS 'When a government Matched contribution payment is received the reference will be updated to show the original contribution'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.DATE_LATEST_CASH_PROCESSED IS 'Last process date for a cash payment against this Contribution'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.DATE_COMPLETED IS 'Date of full payment fulfillment for the Contribution'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.DATE_ADDED IS 'The Date / Time this entity was added.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/


ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION RENAME TO CONTRIBUTION_TTLA_ALLOC_OLD;
/

-- Drop remaining contraints from CONTRIBUTION_TTLA_ALLOC_OLD
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOC_OLD DROP CONSTRAINT CONTRIBTTLAALLOC_CHQ
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOC_OLD DROP CONSTRAINT INCOME_ALLOCATION_PERCENT_CK
/

ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCAT_EDDB RENAME TO CONTRIBUTION_TTLA_ALLOCATION
/

SELECT * FROM CONTRIBUTION_TTLA_ALLOCATION;

UPDATE CONTRIBUTION_TTLA_ALLOCATION SET PRODUCT_ID = 1;

-- TODO Calculate percentage values, as fractions of the parent contribution amount.
-- Actually don't need to, already has a percentage column ya dingus
/*
UPDATE CONTRIBUTION_TTLA_ALLOCATION ttlaAlloc SET (INCOME_ALLOCATION_PERCENT) = (
  SELECT 
  --ttla.INCOME_ALLOCATION_AMOUNT
  --contrib.CONTRIBUTION_AMOUNT, 
  TO_NUMBER(TRIM(TO_CHAR(((ttla.INCOME_ALLOCATION_AMOUNT*100)/contrib.CONTRIBUTION_AMOUNT), 
          '9990.9999999999'))) AS INCOME_ALLOCATION_PERCENT 
  FROM CONTRIBUTION_TTLA_ALLOCATION ttla
  INNER JOIN CONTRIBUTION contrib ON (ttla.CONTRIBUTION_ID = contrib.CONTRIBUTION_ID)
  WHERE ttla.CONTRIB_TTLA_ALLOCATION_ID = ttlaAlloc.CONTRIB_TTLA_ALLOCATION_ID
);
*/

ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION MODIFY (DATE_ADDED CONSTRAINT CONTTLAALLOC_DATEADDED_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION MODIFY (LAST_UPDATED CONSTRAINT CONTTLAALLOC_LASTUPDATED_NN NOT NULL)
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT CONTRIBTTLAALLOC_CHQ CHECK ((INCOME_ALLOCATION_PERCENT IS NULL
AND
INCOME_ALLOCATION_AMOUNT IS NULL)

OR 

(INCOME_ALLOCATION_PERCENT IS NOT NULL
AND
INCOME_ALLOCATION_AMOUNT IS NOT NULL))
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION MODIFY (INCOME_ALLOCATION_PERCENT CONSTRAINT INCOME_ALLOCATION_PERCENT_CK CHECK (INCOME_ALLOCATION_PERCENT BETWEEN 0 AND 100))
/

ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT CONTTLAALLOC_PK PRIMARY KEY (CONTRIB_TTLA_ALLOCATION_ID)
/

ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT CONTTLAALLOC_UQ UNIQUE (CONTRIBUTION_ID,TTLA_ORG_ID)
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.INCOME_ALLOCATION_AMOUNT IS 'The allocation amount, to the nearest penny.

Users will enter either allocation percentages or amounts, the app layer will convert to the one they haven''t entered.

It is expected that the post-conversion amounts will not neccessarily convert back to stored percentages values due to rounding to the nearest penny.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.INCOME_ALLOCATION_PERCENT IS 'The allocation percentage, stored to a high level of accuracy.

Users will enter either allocation percentages or amounts, the app layer will convert to the one they haven''t entered.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.GOV_RECOVERY_AMT_EXPECTED IS 'The expected amount the government will pay against the value of the investment - i.e. 100%'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.GOV_RECOVERY_AMT_ACTUAL IS 'The actual  amount the government has paid against the total value of the donation.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_TTLA_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/

ALTER TABLE CCLA.REF_RPI ADD CONSTRAINT RPI_START_DATE_UQ UNIQUE (RPI_START_DATE)
/

ALTER TABLE CCLA.REF_RPI ADD CONSTRAINT RPI_END_DATE_UQ UNIQUE (RPI_END_DATE)
/

COMMENT ON TABLE CCLA.REF_RPI IS 'Retail Price indexes, stored by date ranges'
/

--ALTER TABLE CCLA.CCLA_ACCOUNT ADD CONSTRAINT CCLAACCOUNT_PK PRIMARY KEY (CCLA_ACCOUNT_ID)
--/

CREATE TABLE CCLA.REF_CONTRIBUTION_TYPE(
  CONTRIBUTION_TYPE_ID Number(15,0) CONSTRAINT CONTRIBTYPE_ID_NN NOT NULL,
  CONTRIBUTION_TYPE_NAME Varchar2(50 ) CONSTRAINT CONTRIBTYPE_NAME_NN NOT NULL,
  CONTRIBUTION_TYPE_CODE Varchar2(3 )
)
/

ALTER TABLE CCLA.REF_CONTRIBUTION_TYPE ADD CONSTRAINT CONTRBTYPE_PK PRIMARY KEY (CONTRIBUTION_TYPE_ID)
/

COMMENT ON TABLE CCLA.REF_CONTRIBUTION_TYPE IS 'E.G. ENDOWMENT, GIFT AID, GOVERNMENT MATCH'
/

-- Add data from REF_SUBSCRIPTION_TYPE (should be 4 rows inserted)
INSERT INTO REF_CONTRIBUTION_TYPE
(CONTRIBUTION_TYPE_ID, CONTRIBUTION_TYPE_NAME, CONTRIBUTION_TYPE_CODE)
SELECT SUBSCRIPTION_TYPE_ID, SUBSCRIPTION_NAME, NULL FROM REF_SUBSCRIPTION_TYPE;

-- Drop the old table now
DROP TABLE CCLA.REF_SUBSCRIPTION_TYPE
/

CREATE TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION(
  CONTRIB_ASSET_ALLOCATION_ID Number(15,0) CONSTRAINT CONTASSALLOC_ID_NN NOT NULL,
  CONTRIBUTION_ID Number(15,0) CONSTRAINT CONTASSALLOC_CONTR_NN NOT NULL,
  FUND_CODE Varchar2(2 CHAR) CONSTRAINT CONTASSALLOC_FND_NN NOT NULL,
  ACCOUNT_ID Number(15,0),
  CONTRIBUTION_AMOUNT Number(15,2) CONSTRAINT CONTASSALLOC_AMOUNT_NN NOT NULL,
  CONTRIBUTION_PERCENT Number(15,12),
  START_DATE Timestamp(6),
  END_DATE Timestamp(6),
  DATE_ADDED Timestamp(6) CONSTRAINT CONTASSALLOC_DATEADD_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT CONTASSALLOC_LSTUPD_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) CONSTRAINT CONTASSALLOC_LSTUPDBY_NN NOT NULL,
  CONSTRAINT CONTRASSETALLOC_CHK CHECK (NOT (
    (FUND_CODE IS NULL AND ACCOUNT_ID IS NULL)
    OR
    (FUND_CODE IS NOT NULL AND ACCOUNT_ID IS NOT NULL)
)),
  CONSTRAINT CONTRASSETALLOC_PERCENT_CHK CHECK (CONTRIBUTION_PERCENT IS NULL
OR
(CONTRIBUTION_PERCENT >= 0 
AND CONTRIBUTION_PERCENT <= 100))
)
/

-- Insert data from CONTRIBUTION_FUND_ALLOCATION to CONTRIBUTION_ASSET_ALLOCATION
INSERT INTO CONTRIBUTION_ASSET_ALLOCATION
(CONTRIB_ASSET_ALLOCATION_ID, CONTRIBUTION_ID, FUND_CODE, ACCOUNT_ID, 
CONTRIBUTION_AMOUNT, CONTRIBUTION_PERCENT, 
START_DATE, END_DATE,
DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY)

SELECT 
CONTRIB_FUND_ALLOCATION_ID, CONTRIBUTION_ID, FUND_CODE, NULL,
CONTRIBUTION_FUND_AMOUNT, NULL,
NULL, NULL,
DATE_ADDED, LAST_UPDATED, LAST_UPDATED_BY FROM CONTRIBUTION_FUND_ALLOCATION;

-- Calculate and set percentage values.
UPDATE CONTRIBUTION_ASSET_ALLOCATION newCAA SET CONTRIBUTION_PERCENT = (
  SELECT
  --caa.CONTRIB_ASSET_ALLOCATION_ID,
  --contrib.CONTRIBUTION_ID,
  --contrib.CONTRIBUTION_AMOUNT,
  --caa.CONTRIBUTION_AMOUNT,
   TO_NUMBER(TRIM(TO_CHAR(((caa.CONTRIBUTION_AMOUNT*100)/contrib.CONTRIBUTION_AMOUNT), 
          '9990.9999999999'))) AS ALLOC_PERCENT 
  FROM CONTRIBUTION_ASSET_ALLOCATION caa
  INNER JOIN CONTRIBUTION contrib ON (caa.CONTRIBUTION_ID = contrib.CONTRIBUTION_ID)
  WHERE caa.CONTRIB_ASSET_ALLOCATION_ID = newCAA.CONTRIB_ASSET_ALLOCATION_ID
)
/

-- Add NN constraint to percentage column
ALTER TABLE CONTRIBUTION_ASSET_ALLOCATION MODIFY (
  CONTRIBUTION_PERCENT Number(15,12) CONSTRAINT CONTASSALLOC_PERCENT_NN NOT NULL
);

-- -----------------------
-- Rename the old table now
ALTER TABLE CONTRIBUTION_FUND_ALLOCATION RENAME TO CONTRIBUTION_ASSET_ALLOC_OLD
/

CREATE UNIQUE INDEX CONTRIBFUNDALLOC_UQ_I ON CCLA.CONTRIBUTION_ASSET_ALLOCATION (CONTRIBUTION_ID,FUND_CODE,ACCOUNT_ID)
/

ALTER TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION ADD CONSTRAINT CONTRIBFUNDALLOC_PK PRIMARY KEY (CONTRIB_ASSET_ALLOCATION_ID)
/

ALTER TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION ADD CONSTRAINT CONTRIBFUNDALLOC_UQ UNIQUE (CONTRIBUTION_ID,FUND_CODE)
/

COMMENT ON TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION IS 'Amount/Percentage allocations between Contributions and Funds/Accounts (assets).

Each Allocation must have either a Fund or Account reference set, but not both.

It is expected that the Percentage will be calculated in terms of the ratio between the given Allocation Amount and the sum of all Allocation Amounts for a given Subscription'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_ASSET_ALLOCATION.DATE_ADDED IS 'The Date / Time this entity was added.'
/

COMMENT ON COLUMN CCLA.CONTRIBUTION_ASSET_ALLOCATION.LAST_UPDATED IS 'The Date / Time this entity was last updated'
/



CREATE TABLE CCLA.REF_GOV_MATCH_RATE(
  GOV_MATCH_RATE_ID Number(15,0) CONSTRAINT GOVMATCHRATE_ID_NN NOT NULL,
  CONTRIBUTION_TYPE_ID Number(15,0) CONSTRAINT GOVMATCHRATE_CONTRIBTYPE_NN NOT NULL,
  GOV_MATCH_PERCENTAGE Number(7,4) CONSTRAINT GOVMATCHRATE_PERCENTAGE_NN NOT NULL,
  GOV_MATCH_START_DATE Timestamp(6) CONSTRAINT GOVMATCHRATE_STARTDATE_NN NOT NULL,
  GOV_MATCH_END_DATE Timestamp(6) CONSTRAINT GOVMATCHRATE_ENDDATE_NN NOT NULL
)
/

ALTER TABLE CCLA.REF_GOV_MATCH_RATE ADD CONSTRAINT GOVMATCHRATE_PK PRIMARY KEY (GOV_MATCH_RATE_ID)
/

-- Add Government Match rate data
INSERT INTO REF_GOV_MATCH_RATE VALUES (1, 1, 100.00, TO_DATE('01/01/2012', 'dd/mm/yyyy'), TO_DATE('01/05/2012', 'dd/mm/yyyy'));
INSERT INTO REF_GOV_MATCH_RATE VALUES (2, 2, 0.00, TO_DATE('01/01/2012', 'dd/mm/yyyy'), TO_DATE('01/01/2020', 'dd/mm/yyyy'));
INSERT INTO REF_GOV_MATCH_RATE VALUES (3, 3, 0.00, TO_DATE('01/01/2012', 'dd/mm/yyyy'), TO_DATE('01/01/2020', 'dd/mm/yyyy'));
INSERT INTO REF_GOV_MATCH_RATE VALUES (4, 4, 0.00, TO_DATE('01/01/2012', 'dd/mm/yyyy'), TO_DATE('01/01/2020', 'dd/mm/yyyy'));

CREATE TABLE CCLA.REF_APP_PROD_ASSET_INVESTMENT(
  APP_PROD_ASSET_INVEST_ID Number(15,0) NOT NULL,
  PRODUCT_ID Number(15,0) CONSTRAINT APPRODASSET_PRODID_NN NOT NULL,
  ASSET_ID Number(15,0),
  FUND_CODE Varchar2(2 CHAR),
  CONSTRAINT APPRODASSET_ASSSET_CHK CHECK (NOT (
    (ASSET_ID IS NULL AND FUND_CODE IS NULL)
    OR
    (ASSET_ID IS NOT NULL AND FUND_CODE IS NOT NULL)
))
)
/

CREATE UNIQUE INDEX APPPRODASSETINV_UQ_I ON CCLA.REF_APP_PROD_ASSET_INVESTMENT (PRODUCT_ID,ASSET_ID,FUND_CODE)
/

ALTER TABLE CCLA.REF_APP_PROD_ASSET_INVESTMENT ADD CONSTRAINT APPPRODASSETINV_PK PRIMARY KEY (APP_PROD_ASSET_INVEST_ID)
/

COMMENT ON TABLE CCLA.REF_APP_PROD_ASSET_INVESTMENT IS 'Eligible assets/funds for investment by Product.

An Asset or Fund Code must always be specified, but not both.'
/

-- Insert data to REF_APP_PROD_ASSET_INVESTMENT. List of 6 available COIF funds
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (1, 1, NULL, 'T');
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (2, 1, NULL, 'AA');
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (3, 1, NULL, 'U');
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (4, 1, NULL, 'V');
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (5, 1, NULL, 'B');
INSERT INTO REF_APP_PROD_ASSET_INVESTMENT VALUES (6, 1, NULL, 'C');

CREATE TABLE CCLA.REF_APP_PROD_CONTRIB_TYPES(
  PROD_CONTRIB_TYPE_ID Number(15,0) CONSTRAINT APPPPRODCONTRTYPE_ID_NN NOT NULL,
  CONTRIBUTION_TYPE_ID Number(15,0) CONSTRAINT APPPRODCONTRTYPE_CONTR_NN NOT NULL,
  PRODUCT_ID Number(15,0) CONSTRAINT APPPRODCONTRTYPE_PROD_NN NOT NULL
)
/

-- Insert data to REF_APP_PROD_CONTRIB_TYPES.
INSERT INTO REF_APP_PROD_CONTRIB_TYPES VALUES (1, 1, 1);
INSERT INTO REF_APP_PROD_CONTRIB_TYPES VALUES (2, 2, 1);
INSERT INTO REF_APP_PROD_CONTRIB_TYPES VALUES (3, 3, 1);
INSERT INTO REF_APP_PROD_CONTRIB_TYPES VALUES (4, 4, 1);

CREATE UNIQUE INDEX APPPRODCONTRTYPE_UQ_I ON CCLA.REF_APP_PROD_CONTRIB_TYPES (CONTRIBUTION_TYPE_ID,PRODUCT_ID)
/

ALTER TABLE CCLA.REF_APP_PROD_CONTRIB_TYPES ADD CONSTRAINT PRODCONTRTYPE_PK PRIMARY KEY (PROD_CONTRIB_TYPE_ID)
/

COMMENT ON TABLE CCLA.REF_APP_PROD_CONTRIB_TYPES IS 'Available Contribution Types for Products'
/



CREATE TABLE CCLA.SUBSCRIPTION_PAYMENT(
  SUBSCRIPTION_PAYMENT_ID Number(15,0) CONSTRAINT SUBSPAYMENT_ID_NN NOT NULL,
  PAYMENT_ID Number(15,0) CONSTRAINT SUBSPAYMENT_PAYMENTID_NN NOT NULL,
  SUBSCRIPTION_ID Number(15,0) CONSTRAINT SUBSPAYMENT_SUBID_NN NOT NULL,
  SUBSCRIPTION_PAYMENT_AMOUNT Number(15,13) CONSTRAINT SUBSPAYMENT_AMOUNT_NN NOT NULL,
  DATE_ADDED Timestamp(6) CONSTRAINT SUBSCRIPTION_DATEADDED_ID NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT SUBSCRIPTION_LASTUPDATE_ID NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) CONSTRAINT SUBSPAYMENT_LSTUPDBY_NN NOT NULL
)
/

CREATE UNIQUE INDEX CCLA.SUBSPAYMENT_UQ_I ON CCLA.SUBSCRIPTION_PAYMENT (PAYMENT_ID,SUBSCRIPTION_ID)
/

ALTER TABLE CCLA.SUBSCRIPTION_PAYMENT ADD CONSTRAINT SUBSPAYMENT_PK PRIMARY KEY (SUBSCRIPTION_PAYMENT_ID)
/

COMMENT ON TABLE CCLA.SUBSCRIPTION_PAYMENT IS 'Used to link many-to-many relationship between Payments and Subscriptions.

A single payment-subscription pair may only exist once, enforced by a unique index.'
/



CREATE TABLE CCLA.CONTRIBUTION_PAYMENT(
  CONTRIBUTION_PAYMENT_ID Number(15,0) NOT NULL,
  SUBSCRIPTION_PAYMENT_ID Number(15,0),
  CONTRIBUTION_ID Number(15,0),
  CONTRIBUTION_PAYMENT_AMOUNT Number(15,13) CONSTRAINT CONTRPAYMENT_AMOUNT_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT CONTRPAYMENT_LSTUPD_NN NOT NULL,
  DATE_ADDED Timestamp(6) NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) CONSTRAINT CONTRPAYMENT_LSTUPDBY_NN NOT NULL
)
/

CREATE UNIQUE INDEX CONTRIBPAYMENT_UQ_I ON CCLA.CONTRIBUTION_PAYMENT (SUBSCRIPTION_PAYMENT_ID,CONTRIBUTION_ID)
/

ALTER TABLE CCLA.CONTRIBUTION_PAYMENT ADD CONSTRAINT CONTRPAY_PK PRIMARY KEY (CONTRIBUTION_PAYMENT_ID)
/



CREATE TABLE CCLA.PAYMENT(
  PAYMENT_ID Number(15,0) NOT NULL,
  PAYMENT_AMOUNT Number(15,13) NOT NULL,
  PAYMENT_RECEIVED_DATE Timestamp(6) NOT NULL,
  PAYMENT_PROCESSED_DATE Timestamp(6),
  DATE_ADDED Timestamp(6) NOT NULL,
  LAST_UPDATED Timestamp(6) NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) CONSTRAINT PAYMENT_LSTUPDBY_NN NOT NULL
)
/

ALTER TABLE CCLA.PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY (PAYMENT_ID)
/

COMMENT ON TABLE CCLA.PAYMENT IS 'Models individual payments at the bank transaction level'
/



CREATE TABLE CCLA.TTLA_GOV_MATCH_LIMIT(
  GOV_MATCH_LIMIT_ID Number(15,0) NOT NULL,
  LIMIT_AMOUNT Number(15,13) CONSTRAINT GOVMATCHLIMIT_AMOUNT_NN NOT NULL,
  LIMIT_START_DATE Timestamp(6) CONSTRAINT GOVMATCHLIMIT_STARTDATE_NN NOT NULL,
  LIMIT_END_DATE Timestamp(6) CONSTRAINT GOVMATCHLIMIT_ENDDATE_NN NOT NULL,
  DATE_ADDED Timestamp(6) CONSTRAINT GOVMATCHLIMIT_DATE_NN NOT NULL,
  LAST_UPDATED Timestamp(6) CONSTRAINT GOVMATCHLIMIT_LSTUPD_NN NOT NULL,
  LAST_UPDATED_BY Varchar2(50 ) CONSTRAINT GOVMATCHLIMIT_LSTUPDBY_NN NOT NULL
)
/

ALTER TABLE CCLA.TTLA_GOV_MATCH_LIMIT ADD CONSTRAINT GOV_MATCH_LIMIT_PK PRIMARY KEY (GOV_MATCH_LIMIT_ID)
/

CREATE INDEX IX_ELEMENT_DONATION_FK ON CCLA.CONTRIBUTION (CONTRIBUTOR_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT ELEMENT_CONTRIBUTION_FK FOREIGN KEY (CONTRIBUTOR_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/
CREATE INDEX SUBS_CONTRIB_IX ON CCLA.CONTRIBUTION (SUBSCRIPTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT SUBS_CONTRIB_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES CCLA.SUBSCRIPTION (SUBSCRIPTION_ID)
/
CREATE INDEX SUBS_FORM_IX ON FORM (SUBSCRIPTION_ID) 
/
ALTER TABLE FORM ADD CONSTRAINT SUBS_FORM_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES CCLA.SUBSCRIPTION (SUBSCRIPTION_ID)
/
CREATE INDEX CONTRTYPE_GOVMATCHRATE_IX ON CCLA.REF_GOV_MATCH_RATE (CONTRIBUTION_TYPE_ID) 
/
ALTER TABLE CCLA.REF_GOV_MATCH_RATE ADD CONSTRAINT CONTRTYPE_GOVMATCHRATE_FK FOREIGN KEY (CONTRIBUTION_TYPE_ID) REFERENCES CCLA.REF_CONTRIBUTION_TYPE (CONTRIBUTION_TYPE_ID)
/
CREATE INDEX CONTRIBTYPE_CONTRIB_IX ON CCLA.CONTRIBUTION (CONTRIBUTION_TYPE_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CONTRIBTYPE_CONTRIB_FK FOREIGN KEY (CONTRIBUTION_TYPE_ID) REFERENCES CCLA.REF_CONTRIBUTION_TYPE (CONTRIBUTION_TYPE_ID)
/
CREATE INDEX RPI_CONTRIBUTION_IX ON CCLA.CONTRIBUTION (RPI_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT RPI_CONTRIBUTION_FK FOREIGN KEY (RPI_ID) REFERENCES CCLA.REF_RPI (RPI_ID)
/
CREATE INDEX IX_PRODUCT_CONTRIBUTION_FK ON CCLA.CONTRIBUTION (PRODUCT_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT PRODUCT_CONTRIBUTION_FK FOREIGN KEY (PRODUCT_ID) REFERENCES CCLA.REF_PRODUCT (PRODUCT_ID)
/
CREATE INDEX PRODUCT_PRODINVEST_IX ON CCLA.REF_APP_PROD_ASSET_INVESTMENT (PRODUCT_ID) 
/
ALTER TABLE CCLA.REF_APP_PROD_ASSET_INVESTMENT ADD CONSTRAINT PRODUCT_PRODINVEST_FK FOREIGN KEY (PRODUCT_ID) REFERENCES CCLA.REF_PRODUCT (PRODUCT_ID)
/
CREATE INDEX CONTRIBTYPE_PRCONTRIBTYPE_IX ON CCLA.REF_APP_PROD_CONTRIB_TYPES (CONTRIBUTION_TYPE_ID) 
/
ALTER TABLE CCLA.REF_APP_PROD_CONTRIB_TYPES ADD CONSTRAINT CONTRIBTYPE_PRCONTRIBTYPE_FK FOREIGN KEY (CONTRIBUTION_TYPE_ID) REFERENCES CCLA.REF_CONTRIBUTION_TYPE (CONTRIBUTION_TYPE_ID)
/
CREATE INDEX PRODUCT_PRCONTRIBTYPE_IX ON CCLA.REF_APP_PROD_CONTRIB_TYPES (PRODUCT_ID) 
/
ALTER TABLE CCLA.REF_APP_PROD_CONTRIB_TYPES ADD CONSTRAINT PRODUCT_PRCONTRIBTYPE_FK FOREIGN KEY (PRODUCT_ID) REFERENCES CCLA.REF_PRODUCT (PRODUCT_ID)
/
CREATE INDEX FUND_PRODINVEST_IX ON CCLA.REF_APP_PROD_ASSET_INVESTMENT (FUND_CODE) 
/
ALTER TABLE CCLA.REF_APP_PROD_ASSET_INVESTMENT ADD CONSTRAINT FUND_PRODINVEST_FK FOREIGN KEY (FUND_CODE) REFERENCES CCLA.FUND (FUND_CODE)
/
CREATE INDEX PRODUCT_CONTRIBTTLAALLOC_IX ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (PRODUCT_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT PRODUCT_CONTRIBTTLAALLOC_FK FOREIGN KEY (PRODUCT_ID) REFERENCES CCLA.REF_PRODUCT (PRODUCT_ID)
/
CREATE INDEX SUBSPAYMENT_CONTRPAYMENT_IX ON CCLA.CONTRIBUTION_PAYMENT (SUBSCRIPTION_PAYMENT_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_PAYMENT ADD CONSTRAINT SUBSPAYMENT_CONTRPAYMENT_FK FOREIGN KEY (SUBSCRIPTION_PAYMENT_ID) REFERENCES CCLA.SUBSCRIPTION_PAYMENT (SUBSCRIPTION_PAYMENT_ID)
/
CREATE INDEX CONTRIB_CONTRPAYMENT_IX ON CCLA.CONTRIBUTION_PAYMENT (CONTRIBUTION_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_PAYMENT ADD CONSTRAINT CONTRIB_CONTRPAYMENT_FK FOREIGN KEY (CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/
CREATE INDEX SUBS_SUBPAYMENT_IX ON CCLA.SUBSCRIPTION_PAYMENT (SUBSCRIPTION_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION_PAYMENT ADD CONSTRAINT SUBS_SUBPAYMENT_FK FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES CCLA.SUBSCRIPTION (SUBSCRIPTION_ID)
/
CREATE INDEX CAMP_CONTRIB_IX ON CCLA.CONTRIBUTION (CAMPAIGN_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CAMP_CONTRIB_FK FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID)
/
CREATE INDEX FORM_CONTRIB_IX ON CCLA.CONTRIBUTION (FORM_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT FORM_CONTRIB_FK FOREIGN KEY (FORM_ID) REFERENCES FORM (FORM_ID)
/
CREATE INDEX ELEM_CONTRIB_BENEFACTOR_IX ON CCLA.CONTRIBUTION (BENEFACTOR_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT ELEM_CONTRIB_BENEFACTOR_FK FOREIGN KEY (BENEFACTOR_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/
CREATE INDEX TTLAALLOC_GOVMATCHLIMIT_IX ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (GOV_MATCH_LIMIT_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT TTLAALLOC_GOVMATCHLIMIT_FK FOREIGN KEY (GOV_MATCH_LIMIT_ID) REFERENCES CCLA.TTLA_GOV_MATCH_LIMIT (GOV_MATCH_LIMIT_ID)
/
CREATE INDEX ACC_CONTRIBASSETALLOC_IX ON CCLA.CONTRIBUTION_ASSET_ALLOCATION (ACCOUNT_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION ADD CONSTRAINT ACC_CONTRIBASSETALLOC_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES CCLA.ACCOUNT (ACCOUNT_ID)
/
CREATE INDEX PAYMENT_SUBSPAYMENT_IX ON CCLA.SUBSCRIPTION_PAYMENT (PAYMENT_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION_PAYMENT ADD CONSTRAINT PAYMENT_SUBSPAYMENT_FK FOREIGN KEY (PAYMENT_ID) REFERENCES CCLA.PAYMENT (PAYMENT_ID)
/
CREATE INDEX IX_USERS_PAYMENT_FK ON CCLA.PAYMENT (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.PAYMENT ADD CONSTRAINT USERS_PAYMENT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/
CREATE INDEX USERS_SUBSPAYMENT_IX ON CCLA.SUBSCRIPTION_PAYMENT (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.SUBSCRIPTION_PAYMENT ADD CONSTRAINT USERS_SUBSPAYMENT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/
CREATE INDEX USERS_CONTRPAYMENT_IX ON CCLA.CONTRIBUTION_PAYMENT (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.CONTRIBUTION_PAYMENT ADD CONSTRAINT USERS_CONTRPAYMENT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/
CREATE INDEX USERS_GOVMATCHLIMIT_IX ON CCLA.TTLA_GOV_MATCH_LIMIT (LAST_UPDATED_BY) 
/
ALTER TABLE CCLA.TTLA_GOV_MATCH_LIMIT ADD CONSTRAINT USERS_GOVMATCHLIMIT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/
CREATE INDEX GOVMATCHRATE_CONTRTTLAALOC_IX ON CCLA.CONTRIBUTION_TTLA_ALLOCATION (GOV_MATCH_RATE_ID) 
/
ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT GOVMATCHRATE_CONTRTTLAALOC_FK FOREIGN KEY (GOV_MATCH_RATE_ID) REFERENCES CCLA.REF_GOV_MATCH_RATE (GOV_MATCH_RATE_ID)
/
CREATE INDEX PROD_SUBS_IX ON CCLA.SUBSCRIPTION (PRODUCT_ID) 
/
ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT PROD_SUBS_FK FOREIGN KEY (PRODUCT_ID) REFERENCES CCLA.REF_PRODUCT (PRODUCT_ID)
/

/*
COMMENT ON COLUMN CCLA.CCLA_ACCOUNT.CCLA_ACCOUNT_ID IS 'CCLA Account primary key'
/

COMMENT ON COLUMN CCLA.CCLA_ACCOUNT.CCLA_ACCOUNT_CODE IS 'Unique Account code made up of 4 Alpha and 8 Numeric characters'
/

COMMENT ON COLUMN CCLA.CCLA_ACCOUNT.LAST_UPDATED_BY IS 'User who last updated the record'
/

COMMENT ON COLUMN CCLA.CCLA_ACCOUNT.DATE_ADDED IS 'Date record was added
'
/

COMMENT ON COLUMN CCLA.CCLA_ACCOUNT.LAST_UPDATED IS 'Date record was last updated
'
/
*/

ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT ACCOUNT_INVESTMENT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES CCLA.ACCOUNT (ACCOUNT_ID)
/


ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT USERS_INVESTMENT_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/


ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT USERS_DONATION_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/


ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT USERS_DONTTLAALLOC_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CCLA.USERS (DNAME)
/


ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT CONTRIB_CONTRIBTTLAALLOC_FK FOREIGN KEY (CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/


ALTER TABLE CCLA.CONTRIBUTION_TTLA_ALLOCATION ADD CONSTRAINT ELEMENT_CONTRTTLAALLOC_FK FOREIGN KEY (TTLA_ORG_ID) REFERENCES CCLA.ELEMENT (ELEMENT_ID)
/


ALTER TABLE CCLA.SUBSCRIPTION ADD CONSTRAINT SUBSTATUS_SUBS_FK FOREIGN KEY (SUBSCRIPTION_STATUS_ID) REFERENCES CCLA.REF_SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID)
/


ALTER TABLE CCLA.CONTRIBUTION ADD CONSTRAINT CONTRIB_MATCHED_CONTRIB_FK FOREIGN KEY (MATCHED_CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/


--ALTER INDEX IX_ELEMENT_CCLA_ACCOUNT_FK RENAME TO IX_ELEMENT_CCLAACCOUNT_FK
--/

ALTER TABLE CCLA.CONTRIBUTION_ASSET_ALLOCATION ADD CONSTRAINT CONTRIB_CONTRIBFUNDALLOC_FK FOREIGN KEY (CONTRIBUTION_ID) REFERENCES CCLA.CONTRIBUTION (CONTRIBUTION_ID)
/







-- Finally: drop the old tables.
DROP TABLE CONTRIBUTION_ASSET_ALLOC_OLD;
DROP TABLE CONTRIBUTION_TTLA_ALLOC_OLD;
DROP TABLE CONTRIBUTION_OLD;
DROP TABLE SUBSCRIPTION_OLD;




-- New Form stuff

-- Form statuses
Insert into REF_FORM_STATUS (FORM_STATUS_ID,FORM_STATUS_NAME,FORM_STATUS_DESCRIPTION) values (7,'Cancelled','Form has been invalidated');
Insert into REF_FORM_STATUS (FORM_STATUS_ID,FORM_STATUS_NAME,FORM_STATUS_DESCRIPTION) values (8,'Old','Form has been superseded by a newer version');
-- Campaign Activities
INSERT INTO REF_CAMPAIGN_ACTIVITY_TYPE VALUES (100015, 'FORM STATUS UPDATE', 'Form status updated');
INSERT INTO REF_CAMPAIGN_ACTIVITY_TYPE VALUES (100016, 'FORM CANCELLED', 'Form cancelled');

 -- Set all 'old' subscription forms to 'Old' status.
 UPDATE FORM SET FORM_STATUS_ID = 8
 WHERE SUBSCRIPTION_ID IS NOT NULL AND FORM_ID NOT IN (
  -- Select most recent form for each subscription.
  SELECT MAX(FORM_ID) AS LATEST_FORM_ID FROM FORM
  WHERE SUBSCRIPTION_ID IS NOT NULL
  GROUP BY SUBSCRIPTION_ID
 );