-- MUST BE EXECUTED AFTER DATAPUMP
--RUN AS UCMADMIN
RENAME CCLA_FORM TO CCLA_FORM_OLD;
RENAME CCLA_FORM_CONFIG TO CCLA_FORM_CONFIG_OLD;
RENAME CCLA_FORM_ACCOUNT_MAP TO CCLA_FORM_ACCOUNT_MAP_OLD;
RENAME CCLA_CAMPAIGNS TO CCLA_CAMPAIGNS_OLD;
RENAME CCLA_PROCESS TO CCLA_PROCESS_OLD;
RENAME CCLA_ACTIVITY TO CCLA_ACTIVITY_OLD;
RENAME CCLA_AML_CHECKLIST TO CCLA_AML_CHECKLIST_OLD;
RENAME CCLA_ACCOUNT_AML_STATUS TO CCLA_ACCOUNT_AML_STATUS_OLD;	
RENAME SDAUDIT TO SDAUDIT_OLD;
RENAME SDAUDIT_DATA TO SDAUDIT_DATA_OLD;
RENAME SDAUDIT_RELATIONS TO SDAUDIT_RELATIONS_OLD;
RENAME REF_CROCKFORDS TO REF_CROCKFORDS_OLD;
RENAME CCLA_INTERACTION TO CCLA_INTERACTION_OLD;
RENAME CCLA_INTERACTION_CATEGORY TO CCLA_INTERACTION_CATEGORY_OLD;
RENAME CCLA_INTERACTION_GROUP TO CCLA_INTERACTION_GROUP_OLD;
RENAME CCLA_INTERACTION_OUTCOME TO CCLA_INTERACTION_OUTCOME_OLD;
RENAME CCLA_INTERACTION_OUTCOME_TYPE TO CCLA_INTERACT_OUTCOME_TYPE_OLD;
RENAME CCLA_INTERACTION_SUBJECT TO CCLA_INTERACTION_SUBJECT_OLD;

REVOKE ALL ON REVISIONS FROM CCLA CASCADE CONSTRAINTS;
REVOKE ALL ON DOCMETA FROM CCLA CASCADE CONSTRAINTS;
REVOKE ALL ON USERS FROM CCLA CASCADE CONSTRAINTS;

DROP VIEW UCMADMIN.V_ACTIVITY_NOTE;
DROP VIEW UCMADMIN.V_CLIENTS_AML_CAMPAIGN;   
DROP VIEW UCMADMIN.V_PROCESS_ACTIVITY;
DROP VIEW UCMADMIN.V_PROCESS_LAST_ACTIVITY;

-- copy/paste then execute as CCLA user.
SELECT 'CREATE SEQUENCE CCLA.SEQ_JOB MINVALUE 0 START WITH '||UCMADMIN.SEQ_JOB.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL;
SELECT 'CREATE SEQUENCE CCLA.SEQ_ENVELOPE MINVALUE 0 START WITH '||UCMADMIN.SEQ_ENVELOPE.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL;

DROP SEQUENCE UCMADMIN.SEQ_ENVELOPE;
DROP SEQUENCE UCMADMIN.SEQ_JOB;


