-- MUST BE EXECUTED AFTER DATAPUMP
--RUN AS CCLA

-- CREATE VIEWS
CREATE OR REPLACE FORCE VIEW "CCLA"."V_PROCESS_LAST_ACTIVITY" ("PROCESS_ID", "ACTIVITY_ID", "PERSON_ID", "ORGANISATION_ID", "USER_ID", "ACTIVITY_DATE", "ACTIVITY_TYPE", "ACTIVITY_ACTION", "ERROR", "PROCESS_STATUS", "PROCESS_DATE", "LAST_ACTION", "PROCESS_ENTITY_ID", "CAMPAIGN_ID", "CAMPAIGN_NAME")
AS
  SELECT pr."PROCESS_ID",
    act."ACTIVITY_ID",
    act."PERSON_ID",
    act."ORGANISATION_ID",
    act."USER_ID",
    act."ACTIVITY_DATE",
    act."ACTIVITY_TYPE",
    act."ACTIVITY_ACTION",
    act."ERROR",
    pr.PROCESS_STATUS,
    pr.PROCESS_DATE,
    pr.LAST_ACTION,
    pr.ORGANISATION_ID AS PROCESS_ENTITY_ID,
    pr.CAMPAIGN_ID,
    cam.NAME AS CAMPAIGN_NAME
  FROM CCLA_PROCESS pr
  LEFT JOIN CCLA_ACTIVITY act
  ON (act.PROCESS_ID=pr.PROCESS_ID)
  INNER JOIN CCLA_CAMPAIGNS cam
  ON (pr.CAMPAIGN_ID = cam.CAMPAIGN_ID)
  WHERE ACTIVITY_ID  =
    (SELECT MAX(ACTIVITY_ID)
    FROM CCLA_ACTIVITY
    WHERE CCLA_ACTIVITY.PROCESS_ID = pr.PROCESS_ID
);  
	
CREATE OR REPLACE FORCE VIEW "CCLA"."V_PROCESS_ACTIVITY" ("PROCESS_ID", "ACTIVITY_ID", "PERSON_ID", "ORGANISATION_ID", "USER_ID", "ACTIVITY_DATE", "ACTIVITY_TYPE", "ACTIVITY_ACTION", "ERROR", "PROCESS_STATUS", "PROCESS_DATE", "LAST_ACTION", "PROCESS_ENTITY_ID", "CAMPAIGN_NAME")
AS
  SELECT pr."PROCESS_ID",
    act."ACTIVITY_ID",
    act."PERSON_ID",
    act."ORGANISATION_ID",
    act."USER_ID",
    act."ACTIVITY_DATE",
    act."ACTIVITY_TYPE",
    act."ACTIVITY_ACTION",
    act."ERROR",
    pr.PROCESS_STATUS,
    pr.PROCESS_DATE,
    pr.LAST_ACTION,
    pr.ORGANISATION_ID AS PROCESS_ENTITY_ID,
    cam.NAME           AS CAMPAIGN_NAME
  FROM CCLA_ACTIVITY act
  LEFT JOIN CCLA_PROCESS pr
  ON (act.PROCESS_ID=pr.PROCESS_ID)
  LEFT JOIN CCLA_CAMPAIGNS cam
  ON (pr.CAMPAIGN_ID = cam.CAMPAIGN_ID);	
  
  
CREATE OR REPLACE FORCE VIEW "CCLA"."V_CLIENTS_AML_CAMPAIGN" ("CLIENT_NUMBER", "COMPANY_CODE", "ORGANISATION_NAME", "DATE_ENROLLED", "AML_ID", "CORRESPONDENT_STATUS", "PROPOSED_DISTRIBUTION", "DISTRIBUTION_DATE", "DISTRIBUTION_TYPE", "CORRESPONDENT_RESPONSE_TYPE", "CORRESPONDENT_OVERRIDE", "CORRESPONDENT_RESPONDED", "CORRESPONDENT_ONHOLD", "CORRESPONDENT_ONHOLD_DATE", "CORRESPONDENT_IVS_PRE1207", "CORRESPONDENT_IVS_CHECK_DATE", "CORRESPONDENT_QRS_CLIENT", "CORRESPONDENT_REQUESTED", "CORRESPONDENT_ACCOUNT_CLOSED", "NOMINEE_CLIENT")
AS
  SELECT cm.client_number,
    rc.COMPANY_CODE,
    cl.organisation_name,
    cl.date_enrolled,
    aml.AML_ID,
    aml.CORRESPONDENT_STATUS,
    aml.PROPOSED_DISTRIBUTION,
    aml.DISTRIBUTION_DATE,
    aml.DISTRIBUTION_TYPE,
    aml.CORRESPONDENT_RESPONSE_TYPE,
    aml.CORRESPONDENT_OVERRIDE,
    aml.CORRESPONDENT_RESPONDED,
    aml.CORRESPONDENT_ONHOLD,
    aml.CORRESPONDENT_ONHOLD_DATE,
    aml.CORRESPONDENT_IVS_PRE1207,
    aml.CORRESPONDENT_IVS_CHECK_DATE,
    aml.CORRESPONDENT_QRS_CLIENT,
    aml.CORRESPONDENT_REQUESTED,
    aml.CORRESPONDENT_ACCOUNT_CLOSED,
    DECODE(INSTR(UPPER(cl.ORGANISATION_NAME), 'NOMINEE'), 0, 0, 1) NOMINEE_CLIENT
  FROM ORGANISATION cl
  INNER JOIN CLIENT_AURORA_MAP cm
  ON (cm.organisation_id = cl.organisation_id)
  INNER JOIN ref_company rc
  ON (rc.company_id = cm.company_id)
  INNER JOIN CCLA_AML_CHECKLIST aml
  ON (cm.CLIENT_NUMBER = aml.CLIENT_NUMBER
  AND rc.COMPANY_CODE  = aml.COMPANY)
  WHERE NOT EXISTS
    (SELECT cl.organisation_id
    FROM CCLA_PROCESS pr
    WHERE cl.organisation_id = pr.organisation_id
    AND PR.CAMPAIGN_ID       = 2
    );    
	
	
CREATE OR REPLACE FORCE VIEW "CCLA"."V_TRANSACTIONS_DISTINCT" ("INSTRUCTION_STATUS_NAME", "INSTRUCTION_ID", "INSTRUCTION_STATUS_ID", "PROCESS_DATE", "ACTUAL_PROCESS_DATE", "INSTRUCTION_TYPE_ID", "SPP_JOB_ID", "LAST_UPDATED", "DATE_ADDED", "LAST_UPDATED_BY", "DEPENDENT_INSTRUCTION_ID", "COMM_ID", "INSTRUCTION_TYPE_NAME", "INSTRUCTION_DESCRIPTION", "IS_FINANCIAL_TRANSACTION", "SUBMIT_TO_SPP", "TRANSACTION_TYPE_NAME", "INSTRUCTION_DOC_GUID", "PRIORITY")
AS
  SELECT ris.INSTRUCTION_STATUS_NAME,
    ins."INSTRUCTION_ID",
    ins."INSTRUCTION_STATUS_ID",
    ins."PROCESS_DATE",
    ins."ACTUAL_PROCESS_DATE",
    ins."INSTRUCTION_TYPE_ID",
    ins."SPP_JOB_ID",
    ins."LAST_UPDATED",
    ins."DATE_ADDED",
    ins."LAST_UPDATED_BY",
    ins."DEPENDENT_INSTRUCTION_ID",
    ins."COMM_ID",
    RIT.INSTRUCTION_TYPE_NAME,
    rit.INSTRUCTION_DESCRIPTION,
    RIT.IS_FINANCIAL_TRANSACTION,
    rit.SUBMIT_TO_SPP,
    rts.transaction_type_name,
    ins.INSTRUCTION_DOC_GUID,
    ins.PRIORITY
  FROM instruction ins
  INNER JOIN ref_instruction_type rit
  ON (rit.instruction_type_id = ins.instruction_type_id)
  INNER JOIN ref_transaction_type rts
  ON (rts.transaction_type_id = rit.transaction_type_id)
  INNER JOIN ref_instruction_status ris
  ON (ris.instruction_status_id = ins.instruction_status_id);
	
CREATE OR REPLACE FORCE VIEW "CCLA"."V_INSTRUCTIONS_LISTED" ("INSTRUCTION_ID", "COMM_ID", "COMM_SOURCE_ID", "COMM_SOURCE_NAME", "INTERACTION_ID", "COMM_TYPE_NAME", "DATE_COMM_ADDED", "CREATED_BY", "ORGANISATION_ID", "ORGANISATION_NAME", "CLIENT_NUMBER", "PADDED_CLIENT_NUMBER", "COMPANY_CODE", "ACCOUNT_ID", "FUND_CODE", "ACCOUNTNUMBER", "COMM_GROUP_ID", "UCM_BATCH_REF", "SPP_BATCH_REF", "INSTRUCTION_STATUS_ID", "INSTRUCTION_STATUS_NAME", "PROCESS_DATE", "ACTUAL_PROCESS_DATE", "INSTRUCTION_TYPE_ID", "SPP_JOB_ID", "LAST_UPDATED", "DATE_ADDED", "LAST_UPDATED_BY", "DEPENDENT_INSTRUCTION_ID", "INSTRUCTION_DOC_GUID", "PRIORITY", "INSTRUCTION_TYPE_NAME", "IS_FINANCIAL_TRANSACTION", "IS_SUSPENDED")
AS
  SELECT ins.INSTRUCTION_ID,
    com.comm_id,
    com.comm_source_id,
    src.comm_source_name,
    com.interaction_id,
    rct.comm_type_name,
    com.date_added AS DATE_COMM_ADDED,
    com.created_by,
    org.organisation_id,
    org.ORGANISATION_NAME,
    cli.CLIENT_NUMBER,
    CASE
      WHEN (cli.CLIENT_NUMBER IS NULL)
      THEN NULL
      WHEN (cli.CLIENT_NUMBER >= 100000)
      THEN (TO_CHAR(cli.CLIENT_NUMBER))
      ELSE LPAD(cli.CLIENT_NUMBER, 5, '0')
    END AS PADDED_CLIENT_NUMBER,
    cmp.COMPANY_CODE,
    acc.ACCOUNT_ID,
    acc.FUND_CODE,
    acc.ACCOUNTNUMBER,
    grp.comm_group_id,
    grp.ucm_batch_ref,
    grp.spp_batch_ref,
    ins.INSTRUCTION_STATUS_ID,
    ist.INSTRUCTION_STATUS_NAME,
    ins.PROCESS_DATE,
    ins.ACTUAL_PROCESS_DATE,
    ins.INSTRUCTION_TYPE_ID,
    ins.SPP_JOB_ID,
    ins.LAST_UPDATED,
    ins.DATE_ADDED,
    ins.LAST_UPDATED_BY,
    ins.DEPENDENT_INSTRUCTION_ID,
    ins.instruction_doc_guid,
    ins.priority,
    typ.INSTRUCTION_TYPE_NAME,
    typ.IS_FINANCIAL_TRANSACTION,
    lok.is_suspended
  FROM instruction ins
  INNER JOIN COMM com
  ON (ins.COMM_ID = com.COMM_ID)
  INNER JOIN REF_COMM_SOURCE src
  ON (com.COMM_SOURCE_ID = src.COMM_SOURCE_ID)
  INNER JOIN REF_COMM_TYPE rct
  ON (com.COMM_TYPE_ID = rct.COMM_TYPE_ID)
  INNER JOIN COMM_GROUP grp
  ON (com.COMM_GROUP_ID = grp.COMM_GROUP_ID)
  INNER JOIN ref_instruction_type typ
  ON (typ.instruction_type_id = ins.instruction_type_id)
  INNER JOIN ref_instruction_status ist
  ON (ins.instruction_status_id = ist.instruction_status_id)
    -- Company data value
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_comp
  ON (ins.INSTRUCTION_ID           = idv_comp.INSTRUCTION_ID
  AND idv_comp.INSTRUCTION_DATA_ID = 50)
  LEFT JOIN REF_COMPANY cmp
  ON (idv_comp.INSTRUCTION_NUM_VALUE = cmp.COMPANY_ID)
    -- Org data value
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_org
  ON (ins.INSTRUCTION_ID          = idv_org.INSTRUCTION_ID
  AND idv_org.INSTRUCTION_DATA_ID = 9)
    -- Source Account data value
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_acc
  ON (ins.INSTRUCTION_ID          = idv_acc.INSTRUCTION_ID
  AND idv_acc.INSTRUCTION_DATA_ID = 1)
  LEFT JOIN ACCOUNT acc
  ON (idv_acc.INSTRUCTION_NUM_VALUE = acc.ACCOUNT_ID)
  LEFT JOIN ORGANISATION org
  ON (org.ORGANISATION_ID = idv_org.INSTRUCTION_NUM_VALUE)
    -- Client Aurora Map. Group by CLIENT_NUMBER values to avoid duplicate rows
  LEFT JOIN
    (SELECT cli.CLIENT_NUMBER,
      cli.ORGANISATION_ID
    FROM CLIENT_AURORA_MAP cli
    GROUP BY cli.ORGANISATION_ID,
      cli.CLIENT_NUMBER
    ) cli
  ON (org.ORGANISATION_ID = cli.ORGANISATION_ID)
  LEFT JOIN INSTRUCTION_LOCK lok
  ON (ins.INSTRUCTION_ID = lok.INSTRUCTION_ID);  
  
  
CREATE OR REPLACE FORCE VIEW "CCLA"."V_INSTRUCTIONS_DISTINCT" ("INSTRUCTION_STATUS_NAME", "INSTRUCTION_ID", "INSTRUCTION_STATUS_ID", "PROCESS_DATE", "ACTUAL_PROCESS_DATE", "INSTRUCTION_TYPE_ID", "SPP_JOB_ID", "LAST_UPDATED", "DATE_ADDED", "LAST_UPDATED_BY", "DEPENDENT_INSTRUCTION_ID", "COMM_ID", "INSTRUCTION_TYPE_NAME", "INSTRUCTION_DESCRIPTION", "IS_FINANCIAL_TRANSACTION", "SUBMIT_TO_SPP", "INSTRUCTION_DOC_GUID", "PRIORITY")
AS
  SELECT ris.INSTRUCTION_STATUS_NAME,
    ins."INSTRUCTION_ID",
    ins."INSTRUCTION_STATUS_ID",
    ins."PROCESS_DATE",
    ins."ACTUAL_PROCESS_DATE",
    ins."INSTRUCTION_TYPE_ID",
    ins."SPP_JOB_ID",
    ins."LAST_UPDATED",
    ins."DATE_ADDED",
    ins."LAST_UPDATED_BY",
    ins."DEPENDENT_INSTRUCTION_ID",
    ins."COMM_ID",
    RIT.INSTRUCTION_TYPE_NAME,
    rit.INSTRUCTION_DESCRIPTION,
    RIT.IS_FINANCIAL_TRANSACTION,
    rit.SUBMIT_TO_SPP,
    ins.instruction_doc_guid,
    ins.priority
  FROM instruction ins
  INNER JOIN ref_instruction_type rit
  ON (rit.instruction_type_id = ins.instruction_type_id)
  INNER JOIN ref_instruction_status ris
  ON (ris.instruction_status_id = ins.instruction_status_id);
  
  
CREATE OR REPLACE FORCE VIEW "CCLA".V_INSTRUCTIONS_EXTENDED_DATA AS
SELECT ins.INSTRUCTION_ID,
  com.comm_id,
  com.comm_source_id,
  src.comm_source_name,
  com.interaction_id,
  rct.comm_type_name,
  com.date_added AS DATE_COMM_ADDED,
  com.created_by,
  org.organisation_id,
  org.ORGANISATION_NAME,
  cli.CLIENT_NUMBER,
  CASE
    WHEN (cli.CLIENT_NUMBER IS NULL)
    THEN NULL
    WHEN (cli.CLIENT_NUMBER >= 100000)
    THEN (TO_CHAR(cli.CLIENT_NUMBER))
    ELSE LPAD(cli.CLIENT_NUMBER, 5, '0')
  END                                                                            AS PADDED_CLIENT_NUMBER,
  DECODE(acc_cmp.COMPANY_CODE, NULL, org_cmp.COMPANY_CODE, acc_cmp.COMPANY_CODE) AS COMPANY_CODE,
  grp.comm_group_id,
  grp.ucm_batch_ref,
  grp.spp_batch_ref,
  ins.INSTRUCTION_STATUS_ID,
  ist.INSTRUCTION_STATUS_NAME,
  ins.PROCESS_DATE,
  ins.ACTUAL_PROCESS_DATE,
  ins.INSTRUCTION_TYPE_ID,
  ins.SPP_JOB_ID,
  ins.LAST_UPDATED,
  ins.DATE_ADDED,
  ins.LAST_UPDATED_BY,
  ins.DEPENDENT_INSTRUCTION_ID,
  ins.INSTRUCTION_DOC_GUID,
  ins.priority,
  typ.INSTRUCTION_TYPE_NAME,
  typ.IS_FINANCIAL_TRANSACTION,
  lok.is_suspended,
  TO_CHAR(idv_cash.instruction_num_value, 'fm999G999G999G990d00')  AS CASH,
  TO_CHAR(idv_units.instruction_num_value, 'fm999G999G999G990d00') AS UNITS,
  srcaccount.ACCOUNT_ID                                            AS SOURCE_ACCOUNT_ID,
  srcaccount.FUND_CODE                                             AS SOURCE_FUND_CODE,
  srcaccount.ACCOUNTNUMBER                                         AS SOURCE_ACCOUNTNUMBER,
  CASE
    WHEN (acc_cmp.COMPANY_CODE IS NULL)
    THEN NULL
    WHEN (acc_cmp.COMPANY_CODE = 'CBF')
    THEN LPAD(srcaccount.ACCOUNTNUMBER, 3, '0')
      || srcaccount.FUND_CODE
    ELSE LPAD(srcaccount.ACCOUNTNUMBER, 4, '0')
      || srcaccount.FUND_CODE
  END AS SOURCE_ACCOUNTNUMBER_STRING
FROM instruction ins
INNER JOIN COMM com
ON (ins.COMM_ID = com.COMM_ID)
INNER JOIN REF_COMM_SOURCE src
ON (com.COMM_SOURCE_ID = src.COMM_SOURCE_ID)
INNER JOIN REF_COMM_TYPE rct
ON (com.COMM_TYPE_ID = rct.COMM_TYPE_ID)
INNER JOIN COMM_GROUP grp
ON (com.COMM_GROUP_ID = grp.COMM_GROUP_ID)
INNER JOIN ref_instruction_type typ
ON (typ.instruction_type_id = ins.instruction_type_id)
INNER JOIN ref_instruction_status ist
ON (ins.instruction_status_id = ist.instruction_status_id)
LEFT JOIN INSTRUCTION_LOCK lok
ON (ins.INSTRUCTION_ID = lok.INSTRUCTION_ID)
LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_org
ON (idv_org.instruction_id      = ins.instruction_id
AND idv_org.instruction_type_id = ins.instruction_type_id
AND idv_org.instruction_data_id = 9)
LEFT JOIN ORGANISATION org
ON (idv_org.instruction_num_value = org.ORGANISATION_ID)
LEFT JOIN CLIENT_AURORA_MAP cli
ON (org.ORGANISATION_ID = cli.ORGANISATION_ID)
LEFT JOIN REF_COMPANY org_cmp
ON (cli.COMPANY_ID = org_cmp.COMPANY_ID)
LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_cash
ON (idv_cash.instruction_id      = ins.instruction_id
AND idv_cash.instruction_type_id = ins.instruction_type_id
AND idv_cash.instruction_data_id = 3)
LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_units
ON (idv_units.instruction_id      = ins.instruction_id
AND idv_units.instruction_type_id = ins.instruction_type_id
AND idv_units.instruction_data_id = 4)
LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_srcaccount
ON (idv_srcaccount.instruction_id      = ins.instruction_id
AND idv_srcaccount.instruction_type_id = ins.instruction_type_id
AND idv_srcaccount.instruction_data_id = 1)
LEFT JOIN ACCOUNT srcaccount
ON (idv_srcaccount.instruction_num_value = srcaccount.ACCOUNT_ID)
LEFT JOIN FUND acc_fnd
ON (srcaccount.FUND_CODE = acc_fnd.FUND_CODE)
LEFT JOIN REF_COMPANY acc_cmp
ON (acc_fnd.COMPANY_ID = acc_cmp.COMPANY_ID);  


CREATE OR REPLACE FORCE VIEW "CCLA"."V_INSTRUCTIONS_EXTENDED" ("INSTRUCTION_ID", "COMM_ID", "COMM_SOURCE_ID", "COMM_SOURCE_NAME", "INTERACTION_ID", "COMM_TYPE_NAME", "DATE_COMM_ADDED", "CREATED_BY", "ORGANISATION_ID", "ORGANISATION_NAME", "CLIENT_NUMBER", "PADDED_CLIENT_NUMBER", "COMPANY_CODE", "ACCOUNT_ID", "FUND_CODE", "ACCOUNTNUMBER", "COMM_GROUP_ID", "UCM_BATCH_REF", "SPP_BATCH_REF", "INSTRUCTION_STATUS_ID", "INSTRUCTION_STATUS_NAME", "PROCESS_DATE", "ACTUAL_PROCESS_DATE", "INSTRUCTION_TYPE_ID", "SPP_JOB_ID", "LAST_UPDATED", "DATE_ADDED", "LAST_UPDATED_BY", "DEPENDENT_INSTRUCTION_ID", "INSTRUCTION_DOC_GUID", "PRIORITY", "INSTRUCTION_TYPE_NAME", "IS_FINANCIAL_TRANSACTION", "IS_SUSPENDED")
AS
  SELECT ins.INSTRUCTION_ID,
    com.comm_id,
    com.comm_source_id,
    src.comm_source_name,
    com.interaction_id,
    rct.comm_type_name,
    com.date_added AS DATE_COMM_ADDED,
    com.created_by,
    org.organisation_id,
    org.ORGANISATION_NAME,
    cli.CLIENT_NUMBER,
    CASE
      WHEN (cli.CLIENT_NUMBER IS NULL)
      THEN NULL
      WHEN (cli.CLIENT_NUMBER >= 100000)
      THEN (TO_CHAR(cli.CLIENT_NUMBER))
      ELSE LPAD(cli.CLIENT_NUMBER, 5, '0')
    END AS PADDED_CLIENT_NUMBER,
    cmp.COMPANY_CODE,
    acc.ACCOUNT_ID,
    acc.FUND_CODE,
    acc.ACCOUNTNUMBER,
    grp.comm_group_id,
    grp.ucm_batch_ref,
    grp.spp_batch_ref,
    ins.INSTRUCTION_STATUS_ID,
    ist.INSTRUCTION_STATUS_NAME,
    ins.PROCESS_DATE,
    ins.ACTUAL_PROCESS_DATE,
    ins.INSTRUCTION_TYPE_ID,
    ins.SPP_JOB_ID,
    ins.LAST_UPDATED,
    ins.DATE_ADDED,
    ins.LAST_UPDATED_BY,
    ins.DEPENDENT_INSTRUCTION_ID,
    ins.INSTRUCTION_DOC_GUID,
    ins.priority,
    typ.INSTRUCTION_TYPE_NAME,
    typ.IS_FINANCIAL_TRANSACTION,
    lok.is_suspended
  FROM instruction ins
  INNER JOIN COMM com
  ON (ins.COMM_ID = com.COMM_ID)
  INNER JOIN REF_COMM_SOURCE src
  ON (com.COMM_SOURCE_ID = src.COMM_SOURCE_ID)
  INNER JOIN REF_COMM_TYPE rct
  ON (com.COMM_TYPE_ID = rct.COMM_TYPE_ID)
  INNER JOIN COMM_GROUP grp
  ON (com.COMM_GROUP_ID = grp.COMM_GROUP_ID)
  INNER JOIN ref_instruction_type typ
  ON (typ.instruction_type_id = ins.instruction_type_id)
  INNER JOIN ref_instruction_status ist
  ON (ins.instruction_status_id = ist.instruction_status_id)
    -- Company data value
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_comp
  ON (ins.INSTRUCTION_ID           = idv_comp.INSTRUCTION_ID
  AND idv_comp.INSTRUCTION_DATA_ID = 50)
  LEFT JOIN REF_COMPANY cmp
  ON (idv_comp.INSTRUCTION_NUM_VALUE = cmp.COMPANY_ID)
    -- Org data value (may not always match the COMM's Org ID)
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_org
  ON (ins.INSTRUCTION_ID          = idv_org.INSTRUCTION_ID
  AND idv_org.INSTRUCTION_DATA_ID = 9)
    -- Source Account data value
  LEFT JOIN V_INSTRUCTION_DATA_VALUE idv_acc
  ON (ins.INSTRUCTION_ID          = idv_acc.INSTRUCTION_ID
  AND idv_acc.INSTRUCTION_DATA_ID = 1)
  LEFT JOIN ACCOUNT acc
  ON (idv_acc.INSTRUCTION_NUM_VALUE = acc.ACCOUNT_ID)
  LEFT JOIN ORGANISATION org
  ON (org.ORGANISATION_ID = DECODE(idv_org.INSTRUCTION_NUM_VALUE, NULL, com.ORGANISATION_ID, idv_org.INSTRUCTION_NUM_VALUE))
    -- Client Aurora Map. Group by CLIENT_NUMBER values to avoid duplicate rows
  LEFT JOIN
    (SELECT cli.CLIENT_NUMBER,
      cli.ORGANISATION_ID
    FROM CLIENT_AURORA_MAP cli
    GROUP BY cli.ORGANISATION_ID,
      cli.CLIENT_NUMBER
    ) cli
  ON (org.ORGANISATION_ID = cli.ORGANISATION_ID)
  LEFT JOIN INSTRUCTION_LOCK lok
  ON (ins.INSTRUCTION_ID = lok.INSTRUCTION_ID);
  
CREATE OR REPLACE FORCE VIEW "CCLA"."V_ACTIVITY_NOTE" ("ACTIVITY_ID", "PROCESS_ID", "INTERACTION_ID", "PERSON_ID", "ORGANISATION_ID", "USER_ID", "ACTIVITY_DATE", "ACTIVITY_TYPE", "ACTIVITY_ACTION", "ERROR", "NOTE_ID", "NOTE")
AS (
  SELECT act."ACTIVITY_ID",
    act."PROCESS_ID",
    act."INTERACTION_ID",
    act."PERSON_ID",
    act."ORGANISATION_ID",
    act."USER_ID",
    act."ACTIVITY_DATE",
    act."ACTIVITY_TYPE",
    act."ACTIVITY_ACTION",
    act."ERROR",
    note.note_id,
    note.note_content
  FROM CCLA_ACTIVITY act
  LEFT JOIN NOTE note ON (act.NOTE_ID = note.NOTE_ID)
  WHERE act.INTERACTION_ID IS NULL

  UNION 

  SELECT act."ACTIVITY_ID",
    null,
    act."INTERACTION_ID",
    act."PERSON_ID",
    act."ORGANISATION_ID",
    act."USER_ID",
    act."ACTIVITY_DATE",
    act."ACTIVITY_TYPE",
    act."ACTIVITY_ACTION",
    act."ERROR",
    note.note_id,
    note.note_content
  FROM INTERACTION_ACTIVITY act
  LEFT JOIN NOTE note ON (act.NOTE_ID = note.NOTE_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM V_ACTIVITY_NOTE FOR CCLA.V_ACTIVITY_NOTE;  
CREATE OR REPLACE PUBLIC SYNONYM V_PROCESS_LAST_ACTIVITY FOR CCLA.V_PROCESS_LAST_ACTIVITY;  
CREATE OR REPLACE PUBLIC SYNONYM V_PROCESS_ACTIVITY FOR CCLA.V_PROCESS_ACTIVITY;  
CREATE OR REPLACE PUBLIC SYNONYM V_CLIENTS_AML_CAMPAIGN FOR CCLA.V_CLIENTS_AML_CAMPAIGN;  

REVOKE ALL ON SEQ_ADDRESS FROM UCMADMIN;
REVOKE ALL ON SEQ_ACCOUNT_VALUE_AUDIT FROM UCMADMIN;
REVOKE ALL ON SEQ_USER_WORK_GROUP FROM UCMADMIN;
REVOKE ALL ON SEQ_SHARE_CLASS_GROUP FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTRUCTION_CONDITION FROM UCMADMIN;
REVOKE ALL ON SEQ_INCOME_EXPENSE_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_AUDIT FROM UCMADMIN;
REVOKE ALL ON SEQ_COMM_SIGNATURE FROM UCMADMIN;
REVOKE ALL ON SEQ_AURORA_CORRNUMBER FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTR_PROCESS_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_COMM FROM UCMADMIN;
REVOKE ALL ON SEQ_CONTRIBUTION FROM UCMADMIN;
REVOKE ALL ON SEQ_CONTRIB_FUND_ALLOCATION FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_NAV_AUDIT FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_EOD FROM UCMADMIN;
REVOKE ALL ON SEQ_ELEMENT FROM UCMADMIN;
REVOKE ALL ON SEQ_TRANSACTION_BATCH FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTRUCTION_AUDIT FROM UCMADMIN;
REVOKE ALL ON SEQ_CAMPAIGN_ENROLMENT FROM UCMADMIN;
REVOKE ALL ON SEQ_CONTRIB_TTLA_ALLOCATION FROM UCMADMIN;
REVOKE ALL ON SEQ_RELATIONS FROM UCMADMIN;
REVOKE ALL ON SEQ_LOAN_ACCOUNTNUMBER FROM UCMADMIN;
REVOKE ALL ON SEQ_CONTACT_POINT FROM UCMADMIN;
REVOKE ALL ON SEQ_ACCOUNT_FLAG_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_ENROLMENT_ATTR_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_IDENTITY_CHECK_AUDIT FROM UCMADMIN;
REVOKE ALL ON SEQ_SHARE_CLASS_MOVEMENT FROM UCMADMIN;
REVOKE ALL ON SEQ_NOTE FROM UCMADMIN;
REVOKE ALL ON SEQ_RELATION_PROPERTY_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_INCOME_EXPENSE FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_PRICE_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTRUCTION_RULE FROM UCMADMIN;
REVOKE ALL ON SEQ_AURORA_CLIENTNUMBER FROM UCMADMIN;
REVOKE ALL ON SEQ_PUBLIC_HOLIDAY FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTRUCTION_DATA_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_COMM_GROUP FROM UCMADMIN;
REVOKE ALL ON SEQ_PERSON_AURORA_MAP FROM UCMADMIN;
REVOKE ALL ON SEQ_SHARE_CLASS FROM UCMADMIN;
REVOKE ALL ON SEQ_SUBSCRIPTION FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_PRICE FROM UCMADMIN;
REVOKE ALL ON SEQ_CAMPAIGN FROM UCMADMIN;
REVOKE ALL ON SEQ_FORM FROM UCMADMIN;
REVOKE ALL ON SEQ_ENROLMENT_ACTION_QUEUE FROM UCMADMIN;
REVOKE ALL ON SEQ_FUND_INVESTMENT_INTENTION FROM UCMADMIN;
REVOKE ALL ON SEQ_SHARE_CLASS_GROUP_APPLIED FROM UCMADMIN;
REVOKE ALL ON SEQ_CAMPAIGN_ACTIVITY FROM UCMADMIN;
REVOKE ALL ON SEQ_INSTRUCTION FROM UCMADMIN;
REVOKE ALL ON SEQ_CLIENT_AURORA_MAP FROM UCMADMIN;
REVOKE ALL ON SEQ_SDAUDIT FROM UCMADMIN;

REVOKE ALL ON REF_MARKETING_GROUP FROM UCMADMIN;
REVOKE ALL ON REF_SHARE_CLASS_GROUP FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_PROCESS FROM UCMADMIN;
REVOKE ALL ON REF_INVESTMENT_INTENT_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_FUND_EOD_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_UCM_METADATA_TRANSLATION FROM UCMADMIN;
REVOKE ALL ON REF_INCOME_EXPENSE_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_SHARE_CLASS FROM UCMADMIN;
REVOKE ALL ON REF_LOAN_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_CAMPAIGN_SUBJECT_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_FORM_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_CAMPAIGN_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_COMM_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_TITLE FROM UCMADMIN;
REVOKE ALL ON REF_INCOME_DIST_METHOD FROM UCMADMIN;
REVOKE ALL ON REF_DEP_PROJECT_CODES FROM UCMADMIN;
REVOKE ALL ON REF_VERIFICATION_SOURCE FROM UCMADMIN;
REVOKE ALL ON REF_ELEMENT_ATTRIBUTES FROM UCMADMIN;
REVOKE ALL ON REF_RELATION_PROPERTY FROM UCMADMIN;
REVOKE ALL ON REF_PUBLIC_HOLIDAY FROM UCMADMIN;
REVOKE ALL ON REF_DEAL_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_DATA FROM UCMADMIN;
REVOKE ALL ON REF_TRANSACTION_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_REGULAR_SCHEDULE_LIST FROM UCMADMIN;
REVOKE ALL ON REF_FUND_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_TITLE_CATEGORY FROM UCMADMIN;
REVOKE ALL ON REF_ACCOUNT_GROUP FROM UCMADMIN;
REVOKE ALL ON REF_COST_CENTRES FROM UCMADMIN;
REVOKE ALL ON REF_SUBSCRIPTION_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_STATIC_DATA_UPDATE FROM UCMADMIN;
REVOKE ALL ON REF_ENROLMENT_ATTRIBUTE FROM UCMADMIN;
REVOKE ALL ON REF_GENERAL_LEDGER FROM UCMADMIN;
REVOKE ALL ON REF_SUBSCRIPTION_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_TRANS_BATCH_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_ACTION FROM UCMADMIN;
REVOKE ALL ON REF_COMM_SOURCE FROM UCMADMIN;
REVOKE ALL ON REF_FUND_DEFINITION_CODE FROM UCMADMIN;
REVOKE ALL ON REF_DATA_SOURCE FROM UCMADMIN;
REVOKE ALL ON REF_COUNTRY FROM UCMADMIN;
REVOKE ALL ON REF_ORG_CATEGORY FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_ACCOUNT_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_AGREEMENT_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_CAMPAIGN_ACTIVITY_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_ORG_CATEGORY_NAME FROM UCMADMIN;
REVOKE ALL ON REF_ACCOUNT_FLAG FROM UCMADMIN;
REVOKE ALL ON REF_SERVICE_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_ACCOUNT_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_GENDER FROM UCMADMIN;
REVOKE ALL ON REF_CONTACT_METHOD FROM UCMADMIN;
REVOKE ALL ON REF_MARKETING_SUBGROUP FROM UCMADMIN;
REVOKE ALL ON REF_WORK_GROUP FROM UCMADMIN;
REVOKE ALL ON REF_INSTRUCTION_CONDITION_OP FROM UCMADMIN;
REVOKE ALL ON REF_ELEMENT_ATTRIBUTE_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_FORM_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_CAMPAIGN_ENROLMENT_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_INCOME_EXPENSE FROM UCMADMIN;
REVOKE ALL ON REF_SHARE_CLASS_MOVE_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_ELEMENT_IDENTIFIERS FROM UCMADMIN;
REVOKE ALL ON REF_CCLA_CLASSIFICATION FROM UCMADMIN;
REVOKE ALL ON REF_COMPANY FROM UCMADMIN;
REVOKE ALL ON REF_RELATION_NAMES_SYNC FROM UCMADMIN;
REVOKE ALL ON REF_CAMPAIGN_ENROLMENT_ACTION FROM UCMADMIN;
REVOKE ALL ON REF_GSS_LOCATION FROM UCMADMIN;
REVOKE ALL ON REF_DATA_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_COMM_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_ELEMENT_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_PROPERTY FROM UCMADMIN;
REVOKE ALL ON REF_FUND_TYPECODE FROM UCMADMIN;
REVOKE ALL ON REF_AUTH_STATUS FROM UCMADMIN;
REVOKE ALL ON REF_ORG_CATEGORY_CBF_TEMP FROM UCMADMIN;
REVOKE ALL ON REF_RELATION_TYPES FROM UCMADMIN;
REVOKE ALL ON REF_INCOME_TYPECODE FROM UCMADMIN;
REVOKE ALL ON REF_RELATION_NAMES FROM UCMADMIN;
REVOKE ALL ON REF_CONTACT_SUBMETHOD FROM UCMADMIN;

REVOKE ALL ON V_INSTRUCTIONS_LISTED FROM UCMADMIN;
REVOKE ALL ON V_SDU_INSTRUCTION_DATA FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_AUDIT FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_VALUES FROM UCMADMIN;
REVOKE ALL ON V_TRANSACTIONS_DISTINCT FROM UCMADMIN;
REVOKE ALL ON V_TRANSACTIONS_ALL FROM UCMADMIN;
REVOKE ALL ON V_ACCOUNT_EXTENDED_CLIENT FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTIONS_EXTENDED FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTIONS_DISTINCT FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_EOD FROM UCMADMIN;
REVOKE ALL ON V_PSDF_ENROLMENT_ACTIVITY_LAST FROM UCMADMIN;
REVOKE ALL ON V_ORG_CATEGORY FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_SOURCE_ACCOUNTS FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_DEST_ACCOUNTS FROM UCMADMIN;
REVOKE ALL ON V_FUND_COMPLETED_END_OF_DAY FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTION_DATA_VALUE FROM UCMADMIN;


REVOKE ALL ON ENROLMENT_ATTRIBUTE_APPLIED FROM UCMADMIN;
REVOKE ALL ON HELP_MAPPING FROM UCMADMIN;
REVOKE ALL ON STATIC_DATA_UPDATE_APPLIED FROM UCMADMIN;
REVOKE ALL ON USER_WORK_GROUP FROM UCMADMIN;
REVOKE ALL ON IDENTITY_VALIDATION_CHECK FROM UCMADMIN;
REVOKE ALL ON SERVICE_DELIVERY_FUND FROM UCMADMIN;
REVOKE ALL ON FUND FROM UCMADMIN;
REVOKE ALL ON ORGANISATION FROM UCMADMIN;
REVOKE ALL ON BANK_ACCOUNT FROM UCMADMIN;
REVOKE ALL ON APPLICABLE_INSTRUCTION_DATA FROM UCMADMIN;
REVOKE ALL ON RULE_FIELDS_APPLIED FROM UCMADMIN;
REVOKE ALL ON RULES FROM UCMADMIN;
REVOKE ALL ON INSTR_RULE_PRIORITY_APPLIED FROM UCMADMIN;
REVOKE ALL ON REF_INSTR_AUDIT_ACTION FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_PROCESS_APPLIED FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_CONDITION FROM UCMADMIN;
REVOKE ALL ON PSDF_FORM_LOADER_TEMP FROM UCMADMIN;
REVOKE ALL ON FORM_ELEMENT_APPLIED FROM UCMADMIN;
REVOKE ALL ON FUND_INVESTMENT_INTENTION FROM UCMADMIN;
REVOKE ALL ON FUND_EOD FROM UCMADMIN;
REVOKE ALL ON INCOME_EXPENSE_APPLIED FROM UCMADMIN;
REVOKE ALL ON FUND_VALUATION FROM UCMADMIN;
REVOKE ALL ON RELATIONS FROM UCMADMIN;
REVOKE ALL ON RELATION_PROPERTY_APPLIED FROM UCMADMIN;
REVOKE ALL ON FORM_CONTACT_APPLIED FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_AUDIT FROM UCMADMIN;
REVOKE ALL ON IRMODULE_INSTR_RULE_APPLIED FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_RULE FROM UCMADMIN;
REVOKE ALL ON FORM FROM UCMADMIN;
REVOKE ALL ON CAMPAIGN FROM UCMADMIN;
REVOKE ALL ON FUND_NAV_AUDIT FROM UCMADMIN;
REVOKE ALL ON SUBSCRIPTION FROM UCMADMIN;
REVOKE ALL ON COMM_GROUP FROM UCMADMIN;
REVOKE ALL ON PERSON_SIGNATURE FROM UCMADMIN;
REVOKE ALL ON FUND_DEALING_DATES FROM UCMADMIN;
REVOKE ALL ON ASSET FROM UCMADMIN;
REVOKE ALL ON PERSON FROM UCMADMIN;
REVOKE ALL ON ELEMENT FROM UCMADMIN;
REVOKE ALL ON FUND_PROCESS_DETAILS FROM UCMADMIN;
REVOKE ALL ON CAMPAIGN_ENROLMENT FROM UCMADMIN;
REVOKE ALL ON SHARE_CLASS_MOVEMENT FROM UCMADMIN;
REVOKE ALL ON SHARE_CLASS_OVERRIDE FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION FROM UCMADMIN;
REVOKE ALL ON INSTR_RULE_CONDITION_APPLIED FROM UCMADMIN;
REVOKE ALL ON ELEMENT_ATTRIBUTE_APPLIED FROM UCMADMIN;
REVOKE ALL ON ACCOUNT_VALUE FROM UCMADMIN;
REVOKE ALL ON PERSON_AURORA_MAP FROM UCMADMIN;
REVOKE ALL ON ACCOUNT FROM UCMADMIN;
REVOKE ALL ON APPLICABLE_ENROLMENT_ATTR FROM UCMADMIN;
REVOKE ALL ON TRANSACTION_BATCH FROM UCMADMIN;
REVOKE ALL ON SHARE_CLASS_GROUP_APPLIED FROM UCMADMIN;
REVOKE ALL ON INSTR_PROCESS_ACTION_APPLIED FROM UCMADMIN;
REVOKE ALL ON ENROLMENT_ACTION_QUEUE FROM UCMADMIN;
REVOKE ALL ON FUND_PRICE FROM UCMADMIN;
REVOKE ALL ON IDENTITY_CHECK FROM UCMADMIN;
REVOKE ALL ON SYSTEM_CONFIG FROM UCMADMIN;
REVOKE ALL ON FUND_ELIGIBILITY FROM UCMADMIN;
REVOKE ALL ON ENROLMENT_ACTIVITY_LAST FROM UCMADMIN;
REVOKE ALL ON INDIRECT_CONTACT_POINTS FROM UCMADMIN;
REVOKE ALL ON CONTRIBUTION_TTLA_ALLOCATION FROM UCMADMIN;
REVOKE ALL ON CONTACT_POINT FROM UCMADMIN;
REVOKE ALL ON ADDRESS FROM UCMADMIN;
REVOKE ALL ON FUND_INVESTMENT FROM UCMADMIN;
REVOKE ALL ON SERVICE_DELIVERY_ELEMENT FROM UCMADMIN;
REVOKE ALL ON SERVICE_DELIVERY_METHOD FROM UCMADMIN;
REVOKE ALL ON ACCOUNT_VALUE_AUDIT FROM UCMADMIN;
REVOKE ALL ON COMM FROM UCMADMIN;
REVOKE ALL ON IDENTITY_CHECK_LOOKUP FROM UCMADMIN;
REVOKE ALL ON SYSTEM_CONFIG_VAR FROM UCMADMIN;
REVOKE ALL ON CONTRIBUTION FROM UCMADMIN;
REVOKE ALL ON CONTRIBUTION_FUND_ALLOCATION FROM UCMADMIN;
REVOKE ALL ON ENROLMENT_STATUS_ACTION_APPL FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_TYPE_DATA_LOADER FROM UCMADMIN;
REVOKE ALL ON FUND_PRICE_APPLIED FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_DATA_APPLIED FROM UCMADMIN;
REVOKE ALL ON ACCOUNT_FLAG_APPLIED FROM UCMADMIN;
REVOKE ALL ON RULE_FIELDS FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_LOCK FROM UCMADMIN;
REVOKE ALL ON INSTR_VERIFICATION_AUDIT FROM UCMADMIN;
REVOKE ALL ON INSTRUCTION_ROUTING_MODULE FROM UCMADMIN;
REVOKE ALL ON NOTE FROM UCMADMIN;
REVOKE ALL ON CAMPAIGN_ACTIVITY FROM UCMADMIN;
REVOKE ALL ON IDENTITY_CHECK_AUDIT FROM UCMADMIN;
REVOKE ALL ON FUND_AUDIT FROM UCMADMIN;
REVOKE ALL ON COMM_SIGNATURE FROM UCMADMIN;
REVOKE ALL ON ELEMENT_IDENTIFIERS_APPLIED FROM UCMADMIN;
REVOKE ALL ON SERVICE_DISTRIBUTION FROM UCMADMIN;
REVOKE ALL ON SERVICE FROM UCMADMIN;
REVOKE ALL ON CLIENT_AURORA_MAP FROM UCMADMIN;



REVOKE ALL ON SDAUDIT_DATA FROM UCMADMIN;
REVOKE ALL ON SDAUDIT_RELATIONS FROM UCMADMIN;
REVOKE ALL ON SDAUDIT FROM UCMADMIN;

REVOKE ALL ON CCLA_FORM_ACCOUNT_MAP FROM UCMADMIN;
REVOKE ALL ON CCLA_AML_CHECKLIST FROM UCMADMIN;
REVOKE ALL ON CCLA_CAMPAIGNS FROM UCMADMIN;
REVOKE ALL ON CCLA_FORM FROM UCMADMIN;
REVOKE ALL ON CCLA_PROCESS FROM UCMADMIN;
REVOKE ALL ON CCLA_ACTIVITY FROM UCMADMIN;
REVOKE ALL ON CCLA_FORM_CONFIG FROM UCMADMIN;
REVOKE ALL ON CCLA_ACCOUNT_AML_STATUS FROM UCMADMIN;
REVOKE ALL ON INTERACTION_ACTIVITY FROM UCMADMIN;
REVOKE ALL ON TRANSACTION FROM UCMADMIN;
REVOKE ALL ON TTLA_ORGS_TEMP FROM UCMADMIN;
REVOKE ALL ON COMMUNICATION FROM UCMADMIN;
REVOKE ALL ON COMM_RULE FROM UCMADMIN;
REVOKE ALL ON INTERACTION FROM UCMADMIN;
REVOKE ALL ON INTERACTION_GROUP FROM UCMADMIN;

REVOKE ALL ON REF_INTERACTION_OUTCOME_TYPE FROM UCMADMIN;
REVOKE ALL ON REF_INTERACTION_CATEGORY FROM UCMADMIN;
REVOKE ALL ON REF_POSTCODE_LOOKUP FROM UCMADMIN;
REVOKE ALL ON REF_INTERACTION_OUTCOME FROM UCMADMIN;
REVOKE ALL ON REF_INTERACTION_SUBJECT FROM UCMADMIN;
REVOKE ALL ON REF_RPI FROM UCMADMIN;
REVOKE ALL ON REF_REGION_LOOKUP FROM UCMADMIN;

REVOKE ALL ON V_ORG_CATEGORY_APPLIED FROM UCMADMIN;
REVOKE ALL ON V_ORG_ACC_PER FROM UCMADMIN;
REVOKE ALL ON V_INSTRUCTIONS_EXTENDED_DATA FROM UCMADMIN;
REVOKE ALL ON V_ACTIVITY_NOTE FROM UCMADMIN;
REVOKE ALL ON V_INTERACTIONS_EXT FROM UCMADMIN;
REVOKE ALL ON V_PREADVICE_DICONDINS_LOOKUP FROM UCMADMIN;

REVOKE ALL ON SEQ_PROCESS FROM UCMADMIN;
REVOKE ALL ON SEQ_INTERACTION_GROUP FROM UCMADMIN;
REVOKE ALL ON SEQ_INTERACTION FROM UCMADMIN;
REVOKE ALL ON SEQ_PROCESS_ACTION FROM UCMADMIN;
REVOKE ALL ON SEQ_ACTIVITY FROM UCMADMIN;