UPDATE ACCOUNT acc SET ACCNUMEXT = (
  SELECT TRIM(TO_CHAR(CLIENT_NUMBER, '00000')) || TRIM(TO_CHAR(ACCOUNTNUMBER, '0000')) || FUND_CODE AS NEW_ACCNUMEXT 
  FROM V_ACCOUNT_EXTENDED_CLIENT axc
  WHERE (axc.ACCOUNT_ID = acc.ACCOUNT_ID)
) WHERE acc.ACCOUNT_ID IN (
  SELECT ACCOUNT_ID FROM V_ACCOUNT_EXTENDED_CLIENT WHERE CLIENT_NUMBER = ???
);