ALTER TABLE FUND 
ADD (
	IS_INTEREST_BAC NUMBER(1,0),
	IS_INTEREST_RETAINED NUMBER(1,0),
	IS_INTEREST_TRANSFERABLE NUMBER(1,0),
	IS_DIV_BAC NUMBER(1,0),
	IS_DIV_TRANSFER_TO_DEPOSIT NUMBER(1,0),
	IS_DIV_REINVESTED NUMBER(1,0),
	IS_DIV_REINVESTED_ACCOUNT NUMBER(1,0),
	IS_DIV_REINVESTED_OTHER_FUNDS NUMBER(1,0),
	IS_SHARE_CLASS NUMBER(1,0),
	IS_DIV_REINVESTED_CAP_BAL NUMBER(1,0)
);

COMMENT ON COLUMN FUND.IS_INTEREST_BAC IS 'Fund allows an account in this deposit fund to be set up so that the interest is paid to bank.';
COMMENT ON COLUMN FUND.IS_INTEREST_RETAINED IS 'Fund allows an account in this deposit fund to be set up so that the interest is retained in the account.';
COMMENT ON COLUMN FUND.IS_INTEREST_TRANSFERABLE IS 'Fund allows an account in this deposit fund to be set up so that the interest is transferred to an account in a deposit fund.';
COMMENT ON COLUMN FUND.IS_DIV_BAC IS 'Fund allows an account in this unitised fund to be set up so that the dividend is paid to bank.';
COMMENT ON COLUMN FUND.IS_DIV_TRANSFER_TO_DEPOSIT IS 'Fund allows an account in this unitised fund to be set up so that the dividend is transferred to an account in a deposit fund.';
COMMENT ON COLUMN FUND.IS_DIV_REINVESTED IS 'Fund allows an account in this unitised fund to be set up so that the dividend is retained in the account.';
COMMENT ON COLUMN FUND.IS_DIV_REINVESTED_ACCOUNT IS 'Fund allows an account in this unitised fund to be set up so that the dividend is retained in another unitised account in the same unitised fund.';
COMMENT ON COLUMN FUND.IS_DIV_REINVESTED_OTHER_FUNDS IS 'Fund allows an account in this unitised fund to be set up so that the dividend is retained in another unitised account in a different unitised fund.';
COMMENT ON COLUMN FUND.IS_SHARE_CLASS IS 'Is Fund a share class fund';
COMMENT ON COLUMN FUND.IS_DIV_REINVESTED_CAP_BAL IS '';


UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'A';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'AA';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'AB';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'B';
UPDATE FUND SET IS_INTEREST_BAC=1, IS_INTEREST_RETAINED=1, IS_INTEREST_TRANSFERABLE=1, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'C';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'R';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'T';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'U';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'V';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'W';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'Z';
UPDATE FUND SET IS_INTEREST_BAC=1, IS_INTEREST_RETAINED=1, IS_INTEREST_TRANSFERABLE=1, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'D';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=1, IS_DIV_REINVESTED_ACCOUNT=1, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'F';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'J';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'K';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'L';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'M';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'N';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'P';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=1, IS_DIV_REINVESTED_ACCOUNT=1, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'S';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=1, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'X';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'Y';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=0, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = '62';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=0, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=1, IS_SHARE_CLASS=1, IS_DIV_REINVESTED_CAP_BAL=0 WHERE FUND_CODE = 'PC';
UPDATE FUND SET IS_INTEREST_BAC=0, IS_INTEREST_RETAINED=0, IS_INTEREST_TRANSFERABLE=0, IS_DIV_BAC=1, IS_DIV_TRANSFER_TO_DEPOSIT=0, IS_DIV_REINVESTED=0, IS_DIV_REINVESTED_ACCOUNT=0, IS_DIV_REINVESTED_OTHER_FUNDS=1, IS_SHARE_CLASS=0, IS_DIV_REINVESTED_CAP_BAL=1 WHERE FUND_CODE = 'PI';
