ALTER TABLE FUND 
DROP (
	IS_INTEREST_BAC,
	IS_INTEREST_RETAINED,
	IS_INTEREST_TRANSFERABLE,
	IS_DIV_BAC,
	IS_DIV_TRANSFER_TO_DEPOSIT,
	IS_DIV_REINVESTED,
	IS_DIV_REINVESTED_ACCOUNT,
	IS_DIV_REINVESTED_OTHER_FUNDS,
	IS_SHARE_CLASS,
	IS_DIV_REINVESTED_CAP_BAL
);

ALTER TABLE FUND 
ADD (
	ALLOW_PAYA NUMBER(1,0),
	ALLOW_TXRI NUMBER(1,0),
	ALLOW_RETN NUMBER(1,0),
	ALLOW_REIN NUMBER(1,0),
	ALLOW_SAME_MANDATED_ACC_FUND NUMBER(1,0),
	ALLOW_REIN_MAND_ACC_OTH_FUND NUMBER(1,0)
);

COMMENT ON COLUMN FUND.ALLOW_PAYA IS 'State whether Income Distribution Method PAYA can be used for this fund';
COMMENT ON COLUMN FUND.ALLOW_REIN IS 'State whether Income Distribution Method RETN can be used for this fund';
COMMENT ON COLUMN FUND.ALLOW_RETN IS 'State whether Income Distribution Method REIN can be used for this fund';
COMMENT ON COLUMN FUND.ALLOW_TXRI IS 'State whether Income Distribution Method TXRI can be used for this fund';
COMMENT ON COLUMN FUND.ALLOW_SAME_MANDATED_ACC_FUND IS 'State whether the mandated account can be the same fund or account';
COMMENT ON COLUMN FUND.ALLOW_REIN_MAND_ACC_OTH_FUND IS 'State whether mandated account can be from other account and funds for REIN distribution';

UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='62';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='A';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='AA';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='AB';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='B';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=1, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='C';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='CF';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=1, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='D';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='F';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='J';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='K';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='L';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='M';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='N';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='P';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=1 WHERE FUND_CODE='PC';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=1 WHERE FUND_CODE='PI';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='R';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='S';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='T';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='U';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='V';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='W';
UPDATE FUND SET ALLOW_PAYA=1, ALLOW_REIN=0, ALLOW_RETN=0, ALLOW_TXRI=1, ALLOW_SAME_MANDATED_ACC_FUND=0, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='X';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='Y';
UPDATE FUND SET ALLOW_PAYA=0, ALLOW_REIN=1, ALLOW_RETN=0, ALLOW_TXRI=0, ALLOW_SAME_MANDATED_ACC_FUND=1, ALLOW_REIN_MAND_ACC_OTH_FUND=0 WHERE FUND_CODE='Z';





CREATE TABLE INTER_FUND_TRANSACTIONS
(
	SOURCE_FUND_CODE VARCHAR2(2 CHAR) NOT NULL,
	DESTINATION_FUND_CODE VARCHAR2(2 CHAR) NOT NULL,
    CONSTRAINT "FUND_INTERFUNDSOURCEFUND_FK" FOREIGN KEY ("SOURCE_FUND_CODE") REFERENCES "CCLA"."FUND" ("FUND_CODE") ENABLE,
	CONSTRAINT "FUND_INTERFUNDDESTFUND_FK" FOREIGN KEY ("DESTINATION_FUND_CODE") REFERENCES "CCLA"."FUND" ("FUND_CODE") ENABLE
);

CREATE INDEX "CCLA"."FUND_INTERFUNDSOURCEFUND_IX" ON "CCLA"."INTER_FUND_TRANSACTIONS" ("SOURCE_FUND_CODE");
CREATE INDEX "CCLA"."FUND_INTERFUNDDESTFUND_IX" ON "CCLA"."INTER_FUND_TRANSACTIONS" ("DESTINATION_FUND_CODE");
  
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('D','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('F','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('J','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('K','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('L','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('M','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('N','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('P','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('S','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','Y');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('X','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','L');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','M');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','N');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','S');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','X');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Y','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('A','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AA','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('AB','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('B','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','F');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','J');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','K');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','P');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('C','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('R','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('T','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('U','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('V','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('W','Z');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','D');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','A');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','AA');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','AB');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','B');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','C');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','R');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','T');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','U');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','V');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('Z','W');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('PC','PC');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('PC','PI');
INSERT INTO INTER_FUND_TRANSACTIONS (SOURCE_FUND_CODE, DESTINATION_FUND_CODE) VALUES ('PI','PC');

  