

-- Table CCLA.USERS
CREATE TABLE CCLA.USERS(
  DNAME Varchar2(50) CONSTRAINT USERS_DNAME_NN NOT NULL
);
/
-- Add keys for table CCLA.USERS
ALTER TABLE CCLA.USERS ADD CONSTRAINT CCLA_USERS_PK PRIMARY KEY (DNAME)
/

-- Table REF_INTERACTION_SUBJECT
CREATE TABLE REF_INTERACTION_SUBJECT(
  INTERACTION_SUBJECT_ID Number(15,0) CONSTRAINT INTERACTSUBJ_ID_NN NOT NULL,
  SUBJECT Varchar2(40 CHAR)
);
/

-- Table REF_INTERACTION_CATEGORY
CREATE TABLE REF_INTERACTION_CATEGORY(
  INTERACTION_CATEGORY_ID Number(15,0) CONSTRAINT INTERACTCAT_ID_NN NOT NULL,
  INTERACTION_SUBJECT_ID Number(15,0),
  CATEGORY Varchar2(100 CHAR)
);
/

-- Table REF_INTERACTION_OUTCOME
CREATE TABLE REF_INTERACTION_OUTCOME(
  OUTCOME_ID Number(15,0) NOT NULL,
  OUTCOME Varchar2(50 CHAR) NOT NULL
);
/

-- Table REF_INTERACTION_OUTCOME_TYPE
CREATE TABLE REF_INTERACTION_OUTCOME_TYPE(
  OUTCOME_TYPE_ID Number(15,0) NOT NULL,
  OUTCOME_TYPE Varchar2(50 CHAR) NOT NULL,
  OUTCOME_ID Number(15,0) NOT NULL
);
/

-- Table INTERACTION
CREATE TABLE INTERACTION(
  INTERACTION_ID Number(10,0) NOT NULL,
  USER_ID Varchar2(50 ),
  INTERACTION_DATE Timestamp(6),
  ORGANISATION_ID Number(15,0),
  PERSON_ID Number(15,0),
  ACCOUNT_ID Number(15,0),
  CONFIRM_TYPES Varchar2(48 CHAR),
  CONFIRM_OTHER Varchar2(48 CHAR),
  INTERACTION_TYPE Varchar2(48 CHAR),
  SUBJECT_ID Number(15,0),
  CATEGORY_ID Number(15,0),
  IS_QUERY Varchar2(1 CHAR),
  IS_COMPLAINT Varchar2(1 CHAR),
  IS_BREACH Varchar2(1 CHAR),
  IS_ERROR Varchar2(1 CHAR),
  CAMPAIGN_ID Number(15,0),
  JOB_ID Varchar2(20 CHAR),
  INTERACTION_STATUS Varchar2(96 CHAR),
  ASSIGNEE Varchar2(96 CHAR),
  DEADLINE Timestamp(6),
  LAST_UPDATED Timestamp(6),  
  FUND_CODE Varchar2(2 CHAR),
  OUTCOME_ID Number(15,0),
  OUTCOME_TYPE_ID Number(15,0),
  OUTCOME_TEXT Varchar2(500 CHAR),
  CLOSED_BY Number(15,0)
);
/

-- Table INTERACTION_GROUP
CREATE TABLE INTERACTION_GROUP(
  GROUP_ID Number(15,0) CONSTRAINT INTERACTGROUP_ID_NN NOT NULL,
  LAST_UPDATED Timestamp(6),
  INTERACTION_ID Number(10,0),
  USER_ID Varchar2(50 )
);
/


-- Table CCLA.INTERACTION_ACTIVITY

CREATE TABLE CCLA.INTERACTION_ACTIVITY(
  ACTIVITY_ID Number(15,0) NOT NULL,
  ACTIVITY_DATE Timestamp(6),
  ACTIVITY_TYPE Varchar2(50 CHAR),
  ACTIVITY_ACTION Varchar2(150 CHAR),
  NOTE_ID Number(15,0),
  ERROR Number(1,0),
  PERSON_ID Number(15,0),
  USER_ID Varchar2(50 ),
  ORGANISATION_ID Number(15,0),
  INTERACTION_ID Number(10,0)
);
/

-- Add keys for table CCLA.INTERACTION_ACTIVITY

ALTER TABLE CCLA.INTERACTION_ACTIVITY ADD CONSTRAINT INTER_ACTIVITY_PK PRIMARY KEY (ACTIVITY_ID)
/

-- Table NOTE_MAPPING
--CREATE TABLE NOTE_MAPPING(
--  NOTE_MAPPING_ID Char(20 ) NOT NULL,
--  NOTE_ID Number(15,0),
--  INTERACTION_ID Number(10,0)
--);
/


-- Add keys for table REF_INTERACTION_SUBJECT
ALTER TABLE REF_INTERACTION_SUBJECT ADD CONSTRAINT INTERACTION_SUBJ_PK PRIMARY KEY (INTERACTION_SUBJECT_ID);
/
-- Table and Columns comments section 
COMMENT ON TABLE REF_INTERACTION_SUBJECT IS 'Subject of an Interaction, e.g. General Inquiry, Mandate Backlog';
/

-- Add keys for table REF_INTERACTION_CATEGORY
ALTER TABLE REF_INTERACTION_CATEGORY ADD CONSTRAINT INTERACTION_CAT_PK PRIMARY KEY (INTERACTION_CATEGORY_ID);
/
-- Table and Columns comments section 
COMMENT ON TABLE REF_INTERACTION_CATEGORY IS 'Categories, related to the parent Subject';
/

-- Add keys for table REF_INTERACTION_OUTCOME
ALTER TABLE REF_INTERACTION_OUTCOME ADD CONSTRAINT REF_INTER_OUTCOME_PK PRIMARY KEY (OUTCOME_ID);
/

-- Add keys for table REF_INTERACTION_OUTCOME_TYPE
ALTER TABLE REF_INTERACTION_OUTCOME_TYPE ADD CONSTRAINT REF_INTER_OUTCOME_TYPE_PK PRIMARY KEY (OUTCOME_TYPE_ID);
/

-- Add keys for table INTERACTION
ALTER TABLE INTERACTION ADD CONSTRAINT INTERACTION_PK PRIMARY KEY (INTERACTION_ID);
/
-- Table and Columns comments section 
COMMENT ON TABLE INTERACTION IS 'Each entry relates to a client/person Interaction, generally logged manually by Client Services. This includes telephone calls, emails etc.
Each Interaction must link to a Person entity at the minimum. Organisation/Account/Fund references are optional.
As the COMM table has an Interaction reference, it is possible to generate Instructions which are linked to a particular Interaction via the COMM table.';
/
COMMENT ON COLUMN INTERACTION.USER_ID IS 'User who initially logged the interaction';
/


/
-- Table and Columns comments section  
COMMENT ON TABLE INTERACTION_GROUP IS 'Grouping ID for sets of related Interactions.';
/


-- INDEXES AND FOREIGN KEYS
CREATE INDEX CATEGORY_INTERACTION_IX ON INTERACTION (CATEGORY_ID);
/
ALTER TABLE INTERACTION ADD CONSTRAINT CATEGORY_INTERACTION_FK FOREIGN KEY (CATEGORY_ID) REFERENCES REF_INTERACTION_CATEGORY (INTERACTION_CATEGORY_ID);
/
CREATE INDEX INTERACTSUBJ_INTERACTCAT_IX ON REF_INTERACTION_CATEGORY (INTERACTION_SUBJECT_ID) ;
/
ALTER TABLE REF_INTERACTION_CATEGORY ADD CONSTRAINT INTERACTSUBJ_INTERACTCAT_FK FOREIGN KEY (INTERACTION_SUBJECT_ID) REFERENCES REF_INTERACTION_SUBJECT (INTERACTION_SUBJECT_ID);
/
CREATE INDEX SUBJECT_INTERACTION_IX ON INTERACTION (SUBJECT_ID);
/
ALTER TABLE INTERACTION ADD CONSTRAINT SUBJECT_INTERACTION_FK FOREIGN KEY (SUBJECT_ID) REFERENCES REF_INTERACTION_SUBJECT (INTERACTION_SUBJECT_ID);
/
CREATE INDEX FUND_INTERACTION_IX ON INTERACTION (FUND_CODE); 
/
ALTER TABLE INTERACTION ADD CONSTRAINT FUND_INTERACTION_FK FOREIGN KEY (FUND_CODE) REFERENCES CCLA.FUND (FUND_CODE);
/
CREATE INDEX ACCOUNT_INTERACTION_IX ON INTERACTION (ACCOUNT_ID); 
/
ALTER TABLE INTERACTION ADD CONSTRAINT ACCOUNT_INTERACTION_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES CCLA.ACCOUNT (ACCOUNT_ID);
/
CREATE INDEX PERSON_INTERACTION_IX ON INTERACTION (PERSON_ID); 
/
ALTER TABLE INTERACTION ADD CONSTRAINT PERSON_INTERACTION_FK FOREIGN KEY (PERSON_ID) REFERENCES CCLA.PERSON (PERSON_ID);
/
CREATE INDEX INTERACTION_COMM_IX ON COMM (INTERACTION_ID); 
/
ALTER TABLE COMM ADD CONSTRAINT INTERACTION_COMM_FK FOREIGN KEY (INTERACTION_ID) REFERENCES INTERACTION (INTERACTION_ID);
/
CREATE INDEX OUTCOME_OUTCOMETYPE_IX ON REF_INTERACTION_OUTCOME_TYPE (OUTCOME_ID); 
/
ALTER TABLE REF_INTERACTION_OUTCOME_TYPE ADD CONSTRAINT OUTCOME_OUTCOMETYPE_FK FOREIGN KEY (OUTCOME_ID) REFERENCES REF_INTERACTION_OUTCOME (OUTCOME_ID);
/
CREATE INDEX OUTCOMETYPE_INTERACTION_IX ON INTERACTION (OUTCOME_TYPE_ID); 
/
ALTER TABLE INTERACTION ADD CONSTRAINT OUTCOMETYPE_INTERACTION_FK FOREIGN KEY (OUTCOME_TYPE_ID) REFERENCES REF_INTERACTION_OUTCOME_TYPE (OUTCOME_TYPE_ID);
/
CREATE INDEX OUTCOME_INTERACTION_IX ON INTERACTION (OUTCOME_ID); 
/
ALTER TABLE INTERACTION ADD CONSTRAINT OUTCOME_INTERACTION_FK FOREIGN KEY (OUTCOME_ID) REFERENCES REF_INTERACTION_OUTCOME (OUTCOME_ID);
/
CREATE INDEX INTER_INTERGROUP_IX ON INTERACTION_GROUP (INTERACTION_ID); 
/
ALTER TABLE INTERACTION_GROUP ADD CONSTRAINT INTER_INTERGROUP_FK FOREIGN KEY (INTERACTION_ID) REFERENCES INTERACTION (INTERACTION_ID);
/
--CREATE INDEX INTERACTION_NOTEMAPPING_IX ON NOTE_MAPPING (INTERACTION_ID); 
/
--ALTER TABLE NOTE_MAPPING ADD CONSTRAINT INTERACTION_NOTEMAPPING_FK FOREIGN KEY (INTERACTION_ID) REFERENCES INTERACTION (INTERACTION_ID);
/
--CREATE INDEX NOTE_NOTEMAPPING_IX ON NOTE_MAPPING (NOTE_ID); 
/
--ALTER TABLE NOTE_MAPPING ADD CONSTRAINT NOTE_NOTEMAPPING_FK FOREIGN KEY (NOTE_ID) REFERENCES NOTE (NOTE_ID);
/

CREATE INDEX INTER_INTERACTIVITY_IX ON CCLA.INTERACTION_ACTIVITY (INTERACTION_ID); 
/
ALTER TABLE CCLA.INTERACTION_ACTIVITY ADD CONSTRAINT INTER_INTERACTIVITY_FK FOREIGN KEY (INTERACTION_ID) REFERENCES INTERACTION (INTERACTION_ID);
/
CREATE INDEX USERS_INTER_ACTIVITY_IX ON CCLA.INTERACTION_ACTIVITY (USER_ID); 
/
ALTER TABLE CCLA.INTERACTION_ACTIVITY ADD CONSTRAINT USERS_INTER_ACTIVITY_FK FOREIGN KEY (USER_ID) REFERENCES CCLA.USERS (DNAME);
/
CREATE INDEX PERSON_INTER_ACTIVITY_IX ON CCLA.INTERACTION_ACTIVITY (PERSON_ID); 
/
ALTER TABLE CCLA.INTERACTION_ACTIVITY ADD CONSTRAINT PERSON_INTER_ACTIVITY_FK FOREIGN KEY (PERSON_ID) REFERENCES CCLA.PERSON (PERSON_ID);
/
CREATE INDEX ORG_INTER_ACTIVITY_IX ON CCLA.INTERACTION_ACTIVITY (ORGANISATION_ID); 
/
ALTER TABLE CCLA.INTERACTION_ACTIVITY ADD CONSTRAINT ORG_INTER_ACTIVITY_FK FOREIGN KEY (ORGANISATION_ID) REFERENCES CCLA.ORGANISATION (ORGANISATION_ID);
/


CREATE OR REPLACE PUBLIC SYNONYM INTERACTION_ACTIVITY FOR CCLA.INTERACTION_ACTIVITY;
CREATE OR REPLACE PUBLIC SYNONYM INTERACTION FOR CCLA.INTERACTION;
CREATE OR REPLACE PUBLIC SYNONYM REF_INTERACTION_SUBJECT FOR CCLA.REF_INTERACTION_SUBJECT;
CREATE OR REPLACE PUBLIC SYNONYM REF_INTERACTION_OUTCOME FOR CCLA.REF_INTERACTION_OUTCOME;
CREATE OR REPLACE PUBLIC SYNONYM REF_INTERACTION_OUTCOME_TYPE FOR CCLA.REF_INTERACTION_OUTCOME_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM INTERACTION_GROUP FOR CCLA.INTERACTION_GROUP;
CREATE OR REPLACE PUBLIC SYNONYM INTERACTION_ACTIVITY FOR CCLA.INTERACTION_ACTIVITY;
CREATE OR REPLACE PUBLIC SYNONYM REF_INTERACTION_CATEGORY FOR CCLA.REF_INTERACTION_CATEGORY;

/* Grant Access */
GRANT ALL ON INTERACTION_ACTIVITY TO UCMADMIN;
GRANT ALL ON INTERACTION TO UCMADMIN;
GRANT ALL ON REF_INTERACTION_SUBJECT TO UCMADMIN;
GRANT ALL ON REF_INTERACTION_OUTCOME TO UCMADMIN;
GRANT ALL ON REF_INTERACTION_OUTCOME_TYPE TO UCMADMIN;
GRANT ALL ON INTERACTION_GROUP TO UCMADMIN;
GRANT ALL ON REF_INTERACTION_CATEGORY TO UCMADMIN;

-- OLD SEQUENCE
DROP SEQUENCE UCMADMIN.SEQ_INTERACTION;
DROP SEQUENCE UCMADMIN.SEQ_INTERACTION_GROUP;
DROP SEQUENCE UCMADMIN.SEQ_ACTIVITY_ID;
--DROP SEQUENCE UCMADMIN.SEQ_NOTE_MAPPING_ID;
DROP SEQUENCE UCMADMIN.SEQ_PROCESS_ACTION_ID; -- LASTNUMBER 35147 (LIVE)
DROP SEQUENCE UCMADMIN.SEQ_PROCESS_ID -- LASTNUMBER 45761 (LIVE)
  
-- NEW SEQUENCE
CREATE SEQUENCE "CCLA"."SEQ_INTERACTION" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ; 
CREATE SEQUENCE "CCLA"."SEQ_INTERACTION_GROUP" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 300 CACHE 20 NOORDER NOCYCLE ; 
CREATE SEQUENCE "CCLA"."SEQ_ACTIVITY" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100000 CACHE 20 NOORDER NOCYCLE ; 
--CREATE SEQUENCE "CCLA"."SEQ_NOTE_MAPPING" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2000 CACHE 20 NOORDER NOCYCLE ; 
CREATE SEQUENCE "CCLA"."SEQ_PROCESS_ACTION" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 35500 CACHE 20 NOORDER NOCYCLE ; 
CREATE SEQUENCE "CCLA"."SEQ_PROCESS" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 46000 CACHE 20 NOORDER NOCYCLE ; 


CREATE OR REPLACE PUBLIC SYNONYM SEQ_INTERACTION FOR CCLA.SEQ_INTERACTION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INTERACTION_GROUP FOR CCLA.SEQ_INTERACTION_GROUP;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ACTIVITY FOR CCLA.SEQ_ACTIVITY;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PROCESS_ACTION FOR CCLA.SEQ_PROCESS_ACTION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PROCESS FOR CCLA.SEQ_PROCESS;

GRANT ALL ON SEQ_INTERACTION TO UCMADMIN;
GRANT ALL ON SEQ_INTERACTION_GROUP TO UCMADMIN;
GRANT ALL ON SEQ_ACTIVITY TO UCMADMIN;
GRANT ALL ON SEQ_PROCESS_ACTION TO UCMADMIN;
GRANT ALL ON SEQ_PROCESS TO UCMADMIN;

--GRANT ALL ON SEQUENCE SEQ_NOTE_MAPPING TO UCMADMIN;


--CREATE INDEX USERS_INTERACTION_IX ON INTERACTION (USER_ID) 
--/
--ALTER TABLE INTERACTION ADD CONSTRAINT USERS_INTERACTION_FK FOREIGN KEY (USER_ID) REFERENCES CCLA.USERS (DNAME)
--/
--CREATE INDEX CAMPAIGN_INTERACTION_IX ON INTERACTION (CAMPAIGN_ID) 
--/
--ALTER TABLE INTERACTION ADD CONSTRAINT CAMPAIGN_INTERACTION_FK FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID)
--/


----------------------------------- INTERACTION LISTING VIEW ------------------------------------------------

DROP VIEW UCMADMIN.V_INTERACTIONS_EXT;


CREATE OR REPLACE FORCE VIEW "CCLA"."V_INTERACTIONS_EXT" ("INTERACTION_ID", "USER_ID", "JOB_ID", "INTERACTION_DATE", "ORGANISATION_ID", "PERSON_ID", "CONFIRM_TYPES", "CONFIRM_OTHER", "INTERACTION_TYPE", "SUBJECT", "CATEGORY", "IS_QUERY", "IS_COMPLAINT", "IS_BREACH", "IS_ERROR", "CAMPAIGN_ID", "OUTCOME", "INTERACTION_STATUS", "ASSIGNEE", "DEADLINE", "LAST_UPDATED", "NAME", "FULL_NAME", "TITLE", "FIRST_NAME", "SECOND_NAME", "ORG_ACCOUNT_CODE", "PERSON_ACCOUNT_CODE")
AS
  SELECT I."INTERACTION_ID",
    I."USER_ID",
    I."JOB_ID",
    I."INTERACTION_DATE",
    I."ORGANISATION_ID",
    I."PERSON_ID",
    I."CONFIRM_TYPES",
    I."CONFIRM_OTHER",
    I."INTERACTION_TYPE",
    S."SUBJECT",
    C."CATEGORY",
    I."IS_QUERY",
    I."IS_COMPLAINT",
    I."IS_BREACH",
    I."IS_ERROR",
    I."CAMPAIGN_ID",
    IO."OUTCOME",
    I."INTERACTION_STATUS",
    I."ASSIGNEE",
    I."DEADLINE",
    I."LAST_UPDATED",
    O.ORGANISATION_NAME,
    P.FULL_NAME,
    T.TITLE,
    P.FIRST_NAME,
    P.LAST_NAME,
    O.ORG_ACCOUNT_CODE,
    P.PERSON_ACCOUNT_CODE
  FROM INTERACTION I
  LEFT JOIN ORGANISATION O
  ON (I.ORGANISATION_ID = O.ORGANISATION_ID)
  LEFT JOIN PERSON P
  ON (I.PERSON_ID = P.PERSON_ID)
  LEFT JOIN REF_INTERACTION_CATEGORY C
  ON (I.CATEGORY_ID = C.INTERACTION_CATEGORY_ID)
  LEFT JOIN REF_INTERACTION_SUBJECT S
  ON (I.SUBJECT_ID = S.INTERACTION_SUBJECT_ID)
  LEFT JOIN REF_TITLE T
  ON (P.TITLE_ID = T.TITLE_ID)
  LEFT JOIN REF_INTERACTION_OUTCOME IO
  ON (I.OUTCOME_ID = IO.OUTCOME_ID);

CREATE OR REPLACE PUBLIC SYNONYM V_INTERACTIONS_EXT FOR CCLA.V_INTERACTIONS_EXT;  
GRANT ALL ON V_INTERACTIONS_EXT TO UCMADMIN;
