
-- THESE SEQUENCE BELOW ARE NOT USED AND ARE ONLY ON LIVE DB
DROP SEQUENCE UCMADMIN.SEQ_INTERACTION_OUTCOME_ID; --LASTNUMBER 392 
DROP SEQUENCE UCMADMIN.SEQ_INTER_OUTCOME_TYPE_ID; --LASTNUMBER 392
DROP SEQUENCE UCMADMIN.SEQ_APPROVED_SIG; --LASTNUMBER 4688;
DROP SEQUENCE UCMADMIN.SEQ_ADDRESSID; -- LASTNUMBER 1581
DROP SEQUENCE SEQ_PROPERTY_ID -- LASTNUMBER 2000000