-- Exposing SDAUDIT tables to CCLA user.
-- Run the below as UCMADMIN.
CREATE OR REPLACE PUBLIC SYNONYM SDAUDIT FOR UCMADMIN.SDAUDIT;
CREATE OR REPLACE PUBLIC SYNONYM SDAUDIT_RELATIONS FOR UCMADMIN.SDAUDIT_RELATIONS;
CREATE OR REPLACE PUBLIC SYNONYM SDAUDIT_DATA FOR UCMADMIN.SDAUDIT_DATA;
    
GRANT ALL ON SDAUDIT TO CCLA;
GRANT ALL ON SDAUDIT_RELATIONS TO CCLA;
GRANT ALL ON SDAUDIT_DATA TO CCLA;