-- DB updates required to support Seg Client campaign

-- Campaign
INSERT INTO CAMPAIGN VALUES 
(12, 'Segregated Client', 'Segregated Client registration AKA Big Local', 'sysadmin', 
TO_DATE('01/12/2011', 'dd/mm/yyyy'), TO_DATE('01/01/2015', 'dd/mm/yyyy'),
TO_DATE('01/12/2011', 'dd/mm/yyyy'), TO_DATE('01/01/2015', 'dd/mm/yyyy'),
1,
'com.ecs.stellent.ccla.clientservices.campaign.SegregatedClientEnrolmentHandler',
'seg_client',
SYSDATE, SYSDATE, 'sysadmin', 1);

-- Form
INSERT INTO REF_FORM_TYPE VALUES 
(16, 'Segregated Client Registration', 3, 3, 
'com.ecs.stellent.ccla.clientservices.form.SegregatedClientRegistrationFormHandler',
'SEG-APP',
1, 1);

-- Generate Forms action at status 'Enrolled'
INSERT INTO ENROLMENT_STATUS_ACTION_APPL VALUES (12, 1, 10);

-- New Element Attributes
REM INSERTING into REF_ELEMENT_ATTRIBUTES
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (60,'Reg. as Limited Company',1,'Registered as Limited Company',1,null,null,null,'BOOL',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (59,'Fund ownership at least 2m Eur',1,'Own funds of at least 2m Euros',1,null,null,null,'BOOL',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (58,'Net turnover at least 40m Eur',1,'Net turnover at least 40m Euros',1,null,null,null,'BOOL',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (57,'Bal. sheet at least 20m Eur',1,'Balance sheet total of at least 20m Euros',1,null,null,null,'BOOL',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (56,'Latest Financial Accounts URL',1,'URL of latest set of financial accounts on website',1,null,null,null,'STRING',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (55,'Accounts subject to audit',1,'Are the organisation''s accounts subject to statutory audit or independent examination?',1,null,null,null,'BOOL',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (54,'Financial Year End',1,null,1,null,null,null,'DATE',6);
Insert into REF_ELEMENT_ATTRIBUTES (ELEMENT_ATTRIBUTE_ID,ELEMENT_ATTRIBUTE_NAME,ELEMENT_TYPE_ID,ELEMENT_ATTRIBUTE_DESCRIPTION,SET_BY_USER,VERIFICATION_SOURCE_ID,ELEMENT_IDENTIFIER_ID,USER_GROUPS,ELEMENT_ATTRIBUTE_DATA_TYPE,ELEMENT_ATTRIBUTE_TYPE_ID) values (61,'Limited Company Name',1,'Official name of the Limited Company. Must be specified for Limited Companies even if it matches the Organisation Name',1,null,null,null,'STRING',6);

-- New address contact submethod
INSERT INTO REF_CONTACT_SUBMETHOD VALUES (6, 'Limited Company address', 1);

-- New Enrolment Attribute stuff
-- ----------------------------

-- Table REF_ENROLMENT_ATTRIBUTE
CREATE SEQUENCE SEQ_ENROLATTRAPPL_ID;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ENROLATTRAPPL_ID FOR CCLA.SEQ_ENROLATTRAPPL_ID;
GRANT ALL ON SEQ_ENROLATTRAPPL_ID TO UCMADMIN;

CREATE TABLE REF_ENROLMENT_ATTRIBUTE(
  ENROLMENT_ATTRIBUTE_ID Integer CONSTRAINT ENROLATTRIB_ID_NN NOT NULL,
  ENROLMENT_ATTRIBUTE_NAME Varchar2(60 ) CONSTRAINT ENROLATTRIB_NAME_NN NOT NULL
)
/

-- Add keys for table REF_ENROLMENT_ATTRIBUTE

ALTER TABLE REF_ENROLMENT_ATTRIBUTE ADD CONSTRAINT ENROLATTRIB_PK PRIMARY KEY (ENROLMENT_ATTRIBUTE_ID)
/

-- Table and Columns comments section
  
COMMENT ON TABLE REF_ENROLMENT_ATTRIBUTE IS 'Stores attributes that can be linked to Campaign Enrolments.

The attributes available to each Campaign Enrolment are stored in the mapping table APPLICABLE_ENROLMENT_ATTRIBUTES.

The actual mapped attribute values are stored in ENROLMENT_ATTRIBUTE_APPLIED'
/

-- Table APPLICABLE_ENROLMENT_ATTR

CREATE TABLE APPLICABLE_ENROLMENT_ATTR(
  APPLENROLATTR_ID Integer NOT NULL,
  ENROLMENT_ATTRIBUTE_ID Integer,
  CAMPAIGN_ID Number(15,0)
)
/

-- Add keys for table APPLICABLE_ENROLMENT_ATTR

ALTER TABLE APPLICABLE_ENROLMENT_ATTR ADD CONSTRAINT APPLENROLATTRIB_PK PRIMARY KEY (APPLENROLATTR_ID)
/

-- Table and Columns comments section
  
COMMENT ON TABLE APPLICABLE_ENROLMENT_ATTR IS 'Allowable enrolment attributes for each Campaign.'
/

-- Table ENROLMENT_ATTRIBUTE_APPLIED

-- Table ENROLMENT_ATTRIBUTE_APPLIED

CREATE TABLE ENROLMENT_ATTRIBUTE_APPLIED(
  ENROLATTRAPPL_ID Integer CONSTRAINT ENROLATTRAPPL_ID_NN NOT NULL,
  APPLENROLATTR_ID Integer CONSTRAINT ENROLATTRAPPL_AEA_NN NOT NULL,
  CAMPAIGN_ENROLMENT_ID Number(15,0) CONSTRAINT ENROLATTRAPPL_EID_NN NOT NULL,
  ATTRIBUTE_VALUE Varchar2(100 ) CONSTRAINT ENROLATTRAPPL_VAL_NN NOT NULL
)
/

-- Add keys for table ENROLMENT_ATTRIBUTE_APPLIED

ALTER TABLE ENROLMENT_ATTRIBUTE_APPLIED ADD CONSTRAINT ENROLATTRAPPL_PK PRIMARY KEY (ENROLATTRAPPL_ID)
/

-- Table and Columns comments section
  
COMMENT ON TABLE ENROLMENT_ATTRIBUTE_APPLIED IS 'Stores attribute values mapped against enrolments.'
/


CREATE INDEX ENROLATTR_APPENROLATTR_IX ON APPLICABLE_ENROLMENT_ATTR (ENROLMENT_ATTRIBUTE_ID) 
/
ALTER TABLE APPLICABLE_ENROLMENT_ATTR ADD CONSTRAINT ENROLATTR_APPENROLATTR_FK FOREIGN KEY (ENROLMENT_ATTRIBUTE_ID) REFERENCES REF_ENROLMENT_ATTRIBUTE (ENROLMENT_ATTRIBUTE_ID)
/

CREATE INDEX CAMPAIGN_APPENROLATTR_IX ON APPLICABLE_ENROLMENT_ATTR (CAMPAIGN_ID) 
/
ALTER TABLE APPLICABLE_ENROLMENT_ATTR ADD CONSTRAINT CAMPAIGN_APPENROLATTR_FK FOREIGN KEY (CAMPAIGN_ID) REFERENCES CAMPAIGN (CAMPAIGN_ID)
/

CREATE INDEX APPENROLATTR_ENROLATTRAPPL_IX ON ENROLMENT_ATTRIBUTE_APPLIED (APPLENROLATTR_ID) 
/
ALTER TABLE ENROLMENT_ATTRIBUTE_APPLIED ADD CONSTRAINT APPENROLATTR_ENROLATTRAPPL_FK FOREIGN KEY (APPLENROLATTR_ID) REFERENCES APPLICABLE_ENROLMENT_ATTR (APPLENROLATTR_ID)
/

CREATE INDEX CAMPENROL_ENROLATTRAPPL_IX ON ENROLMENT_ATTRIBUTE_APPLIED (CAMPAIGN_ENROLMENT_ID) 
/
ALTER TABLE ENROLMENT_ATTRIBUTE_APPLIED ADD CONSTRAINT CAMPENROL_ENROLATTRAPPL_FK FOREIGN KEY (CAMPAIGN_ENROLMENT_ID) REFERENCES CAMPAIGN_ENROLMENT (CAMPAIGN_ENROLMENT_ID)
/

CREATE OR REPLACE PUBLIC SYNONYM REF_ENROLMENT_ATTRIBUTE FOR CCLA.REF_ENROLMENT_ATTRIBUTE;
CREATE OR REPLACE PUBLIC SYNONYM APPLICABLE_ENROLMENT_ATTR FOR CCLA.APPLICABLE_ENROLMENT_ATTR;
CREATE OR REPLACE PUBLIC SYNONYM ENROLMENT_ATTRIBUTE_APPLIED FOR CCLA.ENROLMENT_ATTRIBUTE_APPLIED;

GRANT ALL ON REF_ENROLMENT_ATTRIBUTE TO UCMADMIN;
GRANT ALL ON APPLICABLE_ENROLMENT_ATTR TO UCMADMIN;
GRANT ALL ON ENROLMENT_ATTRIBUTE_APPLIED TO UCMADMIN;

-- Attribute Data

-- Add 'Bank Account' attribute to new campaign
INSERT INTO REF_ENROLMENT_ATTRIBUTE VALUES (1, 'Bank Account');
INSERT INTO APPLICABLE_ENROLMENT_ATTR VALUES (1, 1, 12);
-- Add 'Number of Signatures' attribute to new campaign
INSERT INTO REF_ENROLMENT_ATTRIBUTE VALUES (2, 'Number of Signatures');
INSERT INTO APPLICABLE_ENROLMENT_ATTR VALUES (2, 2, 12);
-- Add 'Min Auth Persons' attribute to new campaign
INSERT INTO REF_ENROLMENT_ATTRIBUTE VALUES (3, 'Min Auth Persons');
INSERT INTO APPLICABLE_ENROLMENT_ATTR VALUES (3, 3, 12);
-- Add 'Min Signatories' attribute to new campaign
INSERT INTO REF_ENROLMENT_ATTRIBUTE VALUES (4, 'Min Signatories');
INSERT INTO APPLICABLE_ENROLMENT_ATTR VALUES (4, 4, 12);

-- TODO Enrol Org ID 2020389, Person ID 4400333 to new campaign.
-- Form ID: 251011


