-- Bank Account
ALTER TABLE CCLA.BANK_ACCOUNT 
  ADD BUILDING_SOCIETY_ROLL_NUMBER Varchar2(20);

DROP INDEX CCLA.BANKACCOUNT_ACCOUNT_UQ;
  
CREATE UNIQUE INDEX CCLA.BANKACCOUNT_ACCOUNT_UQ ON CCLA.BANK_ACCOUNT (ACCOUNT_NO,SORT_CODE,BUILDING_SOCIETY_ROLL_NUMBER);


-- Account Value
ALTER TABLE ACCOUNT_VALUE ADD (
  INCOME_FOR_DISTRIBUTION Number(38,6),
  INTEREST_DIVIDEND_ACCRUED Number(38,6),
  MANAGEMENT_EXPENSE_ACCRUED Number(38,6)
);


-- Person Aurora Map
ALTER TABLE CCLA.PERSON_AURORA_MAP ADD
(
   REPORT_USAGE Integer                 CONSTRAINT CK_PAM_REPORTUSAGE CHECK (REPORT_USAGE IN (0,1)),
   REPORT_MAIL_INDICATOR Integer        CONSTRAINT CK_PAM_MAIL CHECK (REPORT_MAIL_INDICATOR IN (0,1)),
   REPORT_EMAIL_INDICATOR Integer       CONSTRAINT CK_PAM_EMAIL CHECK (REPORT_EMAIL_INDICATOR IN (0,1))
);

alter table PERSON_AURORA_MAP modify REPORT_USAGE default 0;
alter table PERSON_AURORA_MAP modify REPORT_MAIL_INDICATOR default 0;
alter table PERSON_AURORA_MAP modify REPORT_EMAIL_INDICATOR default 0;

-- Client Aurora Map
ALTER TABLE CCLA.CLIENT_AURORA_MAP ADD
(
   CONTRIBUTER_TYPE_CODE Char(20 ),
   SUBDIVISION_CODE Varchar2(30 ),
   CONTRIBUTER_CODE Varchar2(30 ),
   INCOME_DIST_REPORT_IND Integer              CONSTRAINT CK_CAM_INCDISTREP CHECK (INCOME_DIST_REPORT_IND IN (0,1)),
   INCOME_DIST_REPORT_PAPER_IND Integer        CONSTRAINT CK_CAM_INCDISTREPPAP CHECK (INCOME_DIST_REPORT_PAPER_IND IN (0,1)),
   DEPOSIT_NO_OF_STATEMENTS Integer,
   UNITISED_NO_OF_STATEMENTS Integer,
   STATEMENTS_MONTH_1 Integer                  CONSTRAINT CK_CAM_STAT1 CHECK (STATEMENTS_MONTH_1 IN (0,1,2,3,4,5,6,7,8,9,10,11,12)),
   STATEMENTS_MONTH_2 Integer                  CONSTRAINT CK_CAM_STAT2 CHECK (STATEMENTS_MONTH_2 IN (0,1,2,3,4,5,6,7,8,9,10,11,12)),
   STATEMENTS_MONTH_3 Integer                  CONSTRAINT CK_CAM_STAT3 CHECK (STATEMENTS_MONTH_3 IN (0,1,2,3,4,5,6,7,8,9,10,11,12)),
   STATEMENTS_MONTH_4 Integer                  CONSTRAINT CK_CAM_STAT4 CHECK (STATEMENTS_MONTH_4 IN (0,1,2,3,4,5,6,7,8,9,10,11,12)),
   STATEMENTS_MONTH_ALL Integer                CONSTRAINT CK_CAM_STATALL CHECK (STATEMENTS_MONTH_ALL IN (0,1)),
   BULK_DEPOSIT_STATEMENT_IND Integer          CONSTRAINT CK_CAM_BULKDEP CHECK (BULK_DEPOSIT_STATEMENT_IND IN (0,1)),
   DEPOSIT_WITHDRAW_BOOKS_IND Integer          CONSTRAINT CK_CAM_DEPWITHBOOK CHECK (DEPOSIT_WITHDRAW_BOOKS_IND IN (0,1)),
   AUTO_STATIONARY_ORDERED_IND Integer         CONSTRAINT CK_CAM_AUTOSTATORDER CHECK (AUTO_STATIONARY_ORDERED_IND IN (0,1)),
   QUARTERLY_RPT_CLIENT_IND Integer            CONSTRAINT CK_CAM_QRTRREP CHECK (QUARTERLY_RPT_CLIENT_IND IN (0,1)),
   QUARTERLY_RPT_MANAGER_INITS Varchar2(30 ),
   MARKETING_GROUP_ID Integer,
   MARKETING_SUBGROUP_ID Integer,
   ACCOUNT_GROUP_ID Integer
);

alter table CCLA.CLIENT_AURORA_MAP modify INCOME_DIST_REPORT_IND default 0;
alter table CCLA.CLIENT_AURORA_MAP modify INCOME_DIST_REPORT_PAPER_IND default 0;
alter table CCLA.CLIENT_AURORA_MAP modify STATEMENTS_MONTH_1 default 0;
alter table CCLA.CLIENT_AURORA_MAP modify STATEMENTS_MONTH_2 default 0;
alter table CCLA.CLIENT_AURORA_MAP modify STATEMENTS_MONTH_3 default 0;
alter table CCLA.CLIENT_AURORA_MAP modify STATEMENTS_MONTH_4 default 0;
alter table CCLA.CLIENT_AURORA_MAP modify QUARTERLY_RPT_CLIENT_IND default 0;

alter table CCLA.CLIENT_AURORA_MAP modify DEPOSIT_NO_OF_STATEMENTS default 1;
alter table CCLA.CLIENT_AURORA_MAP modify UNITISED_NO_OF_STATEMENTS default 1;
alter table CCLA.CLIENT_AURORA_MAP modify STATEMENTS_MONTH_ALL default 1;
alter table CCLA.CLIENT_AURORA_MAP modify AUTO_STATIONARY_ORDERED_IND default 1;


CREATE TABLE CCLA.REF_MARKETING_GROUP(
  MARKETING_GROUP_ID Integer NOT NULL,
  MARKETING_GROUP_NAME Varchar2(30 ) NOT NULL
);


ALTER TABLE CCLA.REF_MARKETING_GROUP ADD CONSTRAINT MARKETING_GROUP_PK PRIMARY KEY (MARKETING_GROUP_ID);



CREATE TABLE CCLA.REF_MARKETING_SUBGROUP(
  MARKETING_SUBGROUP_ID Integer NOT NULL,
  MARKETING_SUBGROUP_NAME Varchar2(30 ) NOT NULL
);

ALTER TABLE CCLA.REF_MARKETING_SUBGROUP ADD CONSTRAINT MARKETING_SUBGROUP_PK PRIMARY KEY (MARKETING_SUBGROUP_ID);



CREATE TABLE CCLA.REF_ACCOUNT_GROUP(
  ACCOUNT_GROUP_ID Integer NOT NULL,
  ACCOUNT_GROUP_NAME Varchar2(30 ) NOT NULL
);

ALTER TABLE CCLA.REF_ACCOUNT_GROUP ADD CONSTRAINT ACCOUNT_GROUP_PK PRIMARY KEY (ACCOUNT_GROUP_ID);



CREATE INDEX IX_MG_CAM_FK ON CCLA.CLIENT_AURORA_MAP (MARKETING_GROUP_ID); 
ALTER TABLE CCLA.CLIENT_AURORA_MAP ADD CONSTRAINT MG_CAM_FK FOREIGN KEY (MARKETING_GROUP_ID) REFERENCES CCLA.REF_MARKETING_GROUP (MARKETING_GROUP_ID);


CREATE INDEX IX_MSG_CAM_FK ON CCLA.CLIENT_AURORA_MAP (MARKETING_SUBGROUP_ID) ;
ALTER TABLE CCLA.CLIENT_AURORA_MAP ADD CONSTRAINT MSG_CAM_FK FOREIGN KEY (MARKETING_SUBGROUP_ID) REFERENCES CCLA.REF_MARKETING_SUBGROUP (MARKETING_SUBGROUP_ID);


CREATE INDEX IX_AG_CAM_FK ON CCLA.CLIENT_AURORA_MAP (ACCOUNT_GROUP_ID);
ALTER TABLE CCLA.CLIENT_AURORA_MAP ADD CONSTRAINT AG_CAM_FK FOREIGN KEY (ACCOUNT_GROUP_ID) REFERENCES CCLA.REF_ACCOUNT_GROUP (ACCOUNT_GROUP_ID);

