-- Add ORGANISATION_ID and ACCOUNT_ID as applicable data fields
-- for CREATE_CORR and UPDATE_CORR instructions (both optional)

-- CREATE_CORR
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 1, 128, 1);
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 9, 128, 1);

-- UPDATE_CORR
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 1, 129, 1);
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 9, 129, 1);

-- Add ACCOUNT_ID as applicable data field for CREATE_CLIENT and
-- UPDATE_CLIENT instructions (both optional)
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 1, 126, 1);
INSERT INTO APPLICABLE_INSTRUCTION_DATA
VALUES (SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 1, 127, 1);

-- Add ERROR_MESSAGE field to all SDU generator instructions
INSERT INTO APPLICABLE_INSTRUCTION_DATA
SELECT SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 49, INSTRUCTION_TYPE_ID, 1
FROM (SELECT INSTRUCTION_TYPE_ID FROM STATIC_DATA_UPDATE_APPLIED
      GROUP BY INSTRUCTION_TYPE_ID);

-- Amend unique constraint on CORR_ID, to ensure CORR_IDs are only unique
-- per Company.
DROP INDEX PERSONAURORAMAP_CORR_UQ;

UPDATE PERSON_AURORA_MAP SET CORR_ID = PERSON_ID WHERE CORR_ID IS NULL;

CREATE UNIQUE INDEX PERSONAURORAMAP_CORR_UQ ON PERSON_AURORA_MAP
  (CORR_ID, COMPANY_ID);

-- Re-add NN constraint
ALTER TABLE PERSON_AURORA_MAP MODIFY (
  CORR_ID NUMBER(15,0)  CONSTRAINT PAM_CORRID_NN NOT NULL
);  

-- New field: EXECUTION_DATE
-- This will be added against all SDU instructions and set when the instruction
-- is successfully executed in Aurora
INSERT INTO REF_INSTRUCTION_DATA VALUES
(53, 'EXECUTION_DATE', 'DATE', 'Date Executed', 'Date and time the instruction was executed');

INSERT INTO APPLICABLE_INSTRUCTION_DATA
SELECT SEQ_APPLICABLE_INSTR_DATA.NEXTVAL, 53, INSTRUCTION_TYPE_ID, 1
FROM REF_INSTRUCTION_TYPE WHERE IS_STATIC_DATA_UPDATE = 1;