-- Alter the transaction batch table
ALTER TABLE TRANSACTION_BATCH 
DROP COLUMN FUND_CODE; 

ALTER TABLE TRANSACTION_BATCH 
MODIFY (
	TRANS_BATCH_SEQUENCE Number(3,0)
); 

ALTER TABLE TRANSACTION_BATCH 
ADD (
  BANK_ACCOUNT_ID Number(15,0) NOT NULL
);

CREATE INDEX BANKACC_TRANSBATCH_IX ON TRANSACTION_BATCH (BANK_ACCOUNT_ID); 
/
ALTER TABLE TRANSACTION_BATCH ADD CONSTRAINT BANKACC_TRANSBATCH_FK FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT (BANK_ACCOUNT_ID);
/
