-- Drop old unused UCMADMIN triggers, if they still exist.
DROP TRIGGER UCMADMIN.CCLA_ID_CHECK_LOOKUP_TRIG;
DROP TRIGGER UCMADMIN.CCLA_IDENTITY_CHECK_AUDIT_TRIG;

-- Drop newer CCLA trigger on IDENTITY_CHECK_AUDIT table.
-- Sequence allocation is now in line with the other tables.
DROP TRIGGER CCLA.IDENTITY_CHECK_AUDIT_TRIG;

-- Unused UCMADMIN sequences
DROP SEQUENCE UCMADMIN.CCLA_IDENTITY_CHECK_AUDIT_SEQ;
DROP SEQUENCE UCMADMIN.CCLA_IDENTITY_CHECK_LOOKUP_SEQ;
DROP SEQUENCE UCMADMIN.CS_CORRESPONDENT_QUESTION_ID;
DROP SEQUENCE UCMADMIN.CS_FUND_TRANSFER_ID;
DROP SEQUENCE UCMADMIN.CS_PROCESS_NOTE_ID;
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_ACTION_ID;
DROP SEQUENCE UCMADMIN.CCLA_ADDRESS_ID_SEQ;
DROP SEQUENCE UCMADMIN.CCLA_PERSON_ID_SEQ;

DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_ACTIONS_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_AUDIT_ID;
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_INTENTION_ID;

DROP SEQUENCE UCMADMIN.SEQ_BANK_ACC_RELATION_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_BANK_ACCOUNT_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_BANK_ACCOUNT_ID;
DROP SEQUENCE UCMADMIN.SEQ_BANK_ACCOUNT_RELATION_ID;
DROP SEQUENCE UCMADMIN.SEQ_BANKING_DETAILS_ID;

DROP SEQUENCE UCMADMIN.SEQ_ADDRESS_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_CLIENT_AURORA_MAP_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_CONTACT_MAP_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_DDDRESS_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_ENTITY_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_PERSON_AURORA_MAP_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_RELATION_AUDIT;
DROP SEQUENCE UCMADMIN.SEQ_PERSON_AUDIT;

DROP SEQUENCE UCMADMIN.SDAUDIT_SEQ;
DROP SEQUENCE UCMADMIN.SEQ_COMMID;
DROP SEQUENCE UCMADMIN.SEQ_CORRESPONDENCE_GROUP_ID;
DROP SEQUENCE UCMADMIN.SEQ_CORRESPONDENCE_ID;
DROP SEQUENCE UCMADMIN.SEQ_INSTRUCTION_ID;
DROP SEQUENCE UCMADMIN.SEQ_QUEUED_ITEM_ID;
DROP SEQUENCE UCMADMIN.BUNDLEREF;
DROP SEQUENCE UCMADMIN.SEQ_NOTE_MAPPING_ID;
DROP SEQUENCE SEQ_DUAL_INDEX_ID;

-- UCMADMIN sequence renaming
-- (Run as UCMADMIN)
-- ---------------------------
RENAME SEQ_INTERACTION_GROUP_ID TO SEQ_INTERACTION_GROUP;
RENAME SEQ_INTERACTION_ID TO SEQ_INTERACTION;
RENAME ENVELOPEID TO SEQ_ENVELOPE;
RENAME SEQ_JOBID TO SEQ_JOB;
RENAME SEQ_DOCMETA_AUDIT_ID TO SEQ_DOCMETA_AUDIT;

-- CCLA sequence renaming
-- (Run as CCLA)
-- ----------------------
RENAME SEQ_CAMPAIGN_ACTIVITY_ID TO SEQ_CAMPAIGN_ACTIVITY;
RENAME SEQ_CAMPAIGN_ENROLMENT_ID TO SEQ_CAMPAIGN_ENROLMENT;
RENAME SEQ_ENROLATTRAPPL_ID TO SEQ_ENROLMENT_ATTR_APPLIED;
RENAME SEQ_ENROLMENT_ACTION_QUEUE_ID TO SEQ_ENROLMENT_ACTION_QUEUE;
RENAME SEQ_FORM_ID TO SEQ_FORM;
RENAME SEQ_HOLIDAY_ID TO SEQ_PUBLIC_HOLIDAY;
RENAME SEQ_INSTRUCTION_CONDITION_ID TO SEQ_INSTRUCTION_CONDITION;
RENAME SEQ_INSTRUCTION_RULE_ID TO SEQ_INSTRUCTION_RULE;
RENAME SEQ_INVESTMENT_INTENTION_ID TO SEQ_FUND_INVESTMENT_INTENTION;
RENAME SEQ_SC_GROUP_APPLIED_ID TO SEQ_SHARE_CLASS_GROUP_APPLIED;
RENAME SEQ_SC_GROUP_ID TO SEQ_SHARE_CLASS_GROUP;
RENAME SEQ_SHARE_CLASS_ID TO SEQ_SHARE_CLASS;

-- Remove Public Holiday trigger (replaced by seq. allocation in app layer)
DROP TRIGGER REF_PUBLIC_HOLIDAY_TRIGGER;

-- Drop old synonyms
DROP PUBLIC SYNONYM SEQ_CAMPAIGN_ACTIVITY_ID;
DROP PUBLIC SYNONYM SEQ_CAMPAIGN_ENROLMENT_ID;
DROP PUBLIC SYNONYM SEQ_ENROLATTRAPPL_ID;
DROP PUBLIC SYNONYM SEQ_ENROLMENT_ACTION_QUEUE_ID;
DROP PUBLIC SYNONYM SEQ_FORM_ID;
DROP PUBLIC SYNONYM SEQ_HOLIDAY_ID;
DROP PUBLIC SYNONYM SEQ_INSTRUCTION_CONDITION_ID;
DROP PUBLIC SYNONYM SEQ_INSTRUCTION_RULE_ID;
DROP PUBLIC SYNONYM SEQ_INVESTMENT_INTENTION_ID;
DROP PUBLIC SYNONYM SEQ_SC_GROUP_APPLIED_ID;
DROP PUBLIC SYNONYM SEQ_SC_GROUP_ID;
DROP PUBLIC SYNONYM SEQ_SHARE_CLASS_ID;

-- Create updated synonyms and grant all rights to UCMADMIN
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CAMPAIGN_ACTIVITY FOR CCLA.SEQ_CAMPAIGN_ACTIVITY;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CAMPAIGN_ENROLMENT FOR CCLA.SEQ_CAMPAIGN_ENROLMENT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ENROLMENT_ATTR_APPLIED FOR CCLA.SEQ_ENROLMENT_ATTR_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ENROLMENT_ACTION_QUEUE FOR CCLA.SEQ_ENROLMENT_ACTION_QUEUE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FORM FOR CCLA.SEQ_FORM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PUBLIC_HOLIDAY FOR CCLA.SEQ_PUBLIC_HOLIDAY;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INSTRUCTION_CONDITION FOR CCLA.SEQ_INSTRUCTION_CONDITION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INSTRUCTION_RULE FOR CCLA.SEQ_INSTRUCTION_RULE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_INVESTMENT_INTENTION FOR CCLA.SEQ_FUND_INVESTMENT_INTENTION;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SHARE_CLASS_GROUP_APPLIED FOR CCLA.SEQ_SHARE_CLASS_GROUP_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SHARE_CLASS_GROUP FOR CCLA.SEQ_SHARE_CLASS_GROUP;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SHARE_CLASS FOR CCLA.SEQ_SHARE_CLASS;

GRANT ALL ON SEQ_CAMPAIGN_ACTIVITY TO UCMADMIN;
GRANT ALL ON SEQ_CAMPAIGN_ENROLMENT TO UCMADMIN;
GRANT ALL ON SEQ_ENROLMENT_ATTR_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_ENROLMENT_ACTION_QUEUE TO UCMADMIN;
GRANT ALL ON SEQ_FORM TO UCMADMIN;
GRANT ALL ON SEQ_PUBLIC_HOLIDAY TO UCMADMIN;
GRANT ALL ON SEQ_INSTRUCTION_CONDITION TO UCMADMIN;
GRANT ALL ON SEQ_INSTRUCTION_RULE TO UCMADMIN;
GRANT ALL ON SEQ_FUND_INVESTMENT_INTENTION TO UCMADMIN;
GRANT ALL ON SEQ_SHARE_CLASS_GROUP_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_SHARE_CLASS_GROUP TO UCMADMIN;
GRANT ALL ON SEQ_SHARE_CLASS TO UCMADMIN;

-- -------------------------------
-- Run these lines together to generate the required CREATE SEQUENCE sql statements, 
-- copy/paste then execute as CCLA user.
SELECT 'CREATE SEQUENCE CCLA.SEQ_ACCOUNT_FLAG_APPLIED MINVALUE 0 START WITH '||UCMADMIN.SEQ_ACCOUNT_FLAG_APPLIED_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_ACCOUNT_VALUE_AUDIT MINVALUE 0 START WITH '||UCMADMIN.SEQ_ACCOUNT_VALUE_AUDIT_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_ADDRESS MINVALUE 0 START WITH '||UCMADMIN.SEQ_ADDRESS_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_CAMPAIGN MINVALUE 0 START WITH '||UCMADMIN.SEQ_CAMPAIGN_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_SDAUDIT MINVALUE 0 START WITH '||UCMADMIN.SEQ_SDAUDIT.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_COMM_SIGNATURE MINVALUE 0 START WITH '||UCMADMIN.SEQ_APPROVED_SIG.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_CLIENT_AURORA_MAP MINVALUE 0 START WITH '||UCMADMIN.SEQ_CLIENT_AURORA_MAP_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_PERSON_AURORA_MAP MINVALUE 0 START WITH '||UCMADMIN.SEQ_PERSON_AURORA_MAP_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_CONTACT_POINT MINVALUE 0 START WITH '||UCMADMIN.SEQ_CONTACT_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_ELEMENT MINVALUE 0 START WITH '||UCMADMIN.SEQ_ELEMENT_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_RELATIONS MINVALUE 0 START WITH '||UCMADMIN.SEQ_ELEMENT_RELATION_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_FUND_AUDIT MINVALUE 0 START WITH '||UCMADMIN.SEQ_FUND_AUDIT_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_FUND_EOD MINVALUE 0 START WITH '||UCMADMIN.SEQ_FUND_EOD_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_FUND_NAV_AUDIT MINVALUE 0 START WITH '||UCMADMIN.SEQ_FUND_NAV_AUDIT_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_FUND_PRICE_APPLIED MINVALUE 0 START WITH '||UCMADMIN.SEQ_FUND_PRICE_APPLIED_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_FUND_PRICE MINVALUE 0 START WITH '||UCMADMIN.SEQ_FUND_PRICE_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_INCOME_EXPENSE_APPLIED MINVALUE 0 START WITH '||UCMADMIN.SEQ_INCOME_EXPENSE_APPLIED_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_INCOME_EXPENSE MINVALUE 0 START WITH '||UCMADMIN.SEQ_INCOME_EXPENSE_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_RELATION_PROPERTY_APPLIED MINVALUE 0 START WITH '||UCMADMIN.SEQ_PROPERTY_APPLIED_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_NOTE MINVALUE 0 START WITH '||UCMADMIN.SEQ_NOTE_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/
SELECT 'CREATE SEQUENCE CCLA.SEQ_SHARE_CLASS_MOVEMENT MINVALUE 0 START WITH '||UCMADMIN.SEQ_SHARE_CLASS_MOVE_ID.NEXTVAL||' INCREMENT BY 1 CACHE 20;' FROM DUAL
/


-- RUN GENERATED LINES ABOVE BEFORE CONTINUING!!
-- -------------------------------------------

-- Drop the old sequences as UCMADMIN
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_FLAG_APPLIED_ID;
DROP SEQUENCE UCMADMIN.SEQ_ACCOUNT_VALUE_AUDIT_ID;
DROP SEQUENCE UCMADMIN.SEQ_ADDRESS_ID;
DROP SEQUENCE UCMADMIN.SEQ_CAMPAIGN_ID;
DROP SEQUENCE UCMADMIN.SEQ_SDAUDIT;
DROP SEQUENCE UCMADMIN.SEQ_CLIENT_AURORA_MAP_ID;
DROP SEQUENCE UCMADMIN.SEQ_PERSON_AURORA_MAP_ID;
DROP SEQUENCE UCMADMIN.SEQ_CONTACT_ID;
DROP SEQUENCE UCMADMIN.SEQ_ELEMENT_ID;
DROP SEQUENCE UCMADMIN.SEQ_ELEMENT_RELATION_ID;
DROP SEQUENCE UCMADMIN.SEQ_FUND_AUDIT_ID;
DROP SEQUENCE UCMADMIN.SEQ_FUND_EOD_ID;
DROP SEQUENCE UCMADMIN.SEQ_FUND_NAV_AUDIT_ID;
DROP SEQUENCE UCMADMIN.SEQ_FUND_PRICE_APPLIED_ID;
DROP SEQUENCE UCMADMIN.SEQ_FUND_PRICE_ID;
DROP SEQUENCE UCMADMIN.SEQ_INCOME_EXPENSE_APPLIED_ID;
DROP SEQUENCE UCMADMIN.SEQ_INCOME_EXPENSE_ID;
DROP SEQUENCE UCMADMIN.SEQ_PROPERTY_APPLIED_ID;
DROP SEQUENCE UCMADMIN.SEQ_NOTE_ID;
DROP SEQUENCE UCMADMIN.SEQ_SHARE_CLASS_MOVE_ID;

-- Run as CCLA
-- You may get errors about some of these not existing, ignore these.
DROP PUBLIC SYNONYM SEQ_ACCOUNT_FLAG_APPLIED_ID;
DROP PUBLIC SYNONYM SEQ_ACCOUNT_VALUE_AUDIT_ID;
DROP PUBLIC SYNONYM SEQ_ADDRESS_ID;
DROP PUBLIC SYNONYM SEQ_CAMPAIGN_ID;
DROP PUBLIC SYNONYM SEQ_CLIENT_AURORA_MAP_ID;
DROP PUBLIC SYNONYM SEQ_PERSON_AURORA_MAP_ID;
DROP PUBLIC SYNONYM SEQ_CONTACT_ID;
DROP PUBLIC SYNONYM SEQ_ELEMENT_ID;
DROP PUBLIC SYNONYM SEQ_ELEMENT_RELATION_ID;
DROP PUBLIC SYNONYM SEQ_FUND_AUDIT_ID;
DROP PUBLIC SYNONYM SEQ_FUND_EOD_ID;
DROP PUBLIC SYNONYM SEQ_FUND_NAV_AUDIT_ID;
DROP PUBLIC SYNONYM SEQ_FUND_PRICE_APPLIED_ID;
DROP PUBLIC SYNONYM SEQ_FUND_PRICE_ID;
DROP PUBLIC SYNONYM SEQ_INCOME_EXPENSE_APPLIED_ID;
DROP PUBLIC SYNONYM SEQ_INCOME_EXPENSE_ID;
DROP PUBLIC SYNONYM SEQ_INSTRUCTION_ID;
DROP PUBLIC SYNONYM SEQ_PROPERTY_APPLIED_ID;
DROP PUBLIC SYNONYM SEQ_NOTE_ID;
DROP PUBLIC SYNONYM SEQ_SHARE_CLASS_MOVE_ID;

-- Public synonyms and grants.
-- These will be removed once the tablespaces are separated. Adding
-- now for consistency with current architecture.
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ACCOUNT_FLAG_APPLIED FOR CCLA.SEQ_ACCOUNT_FLAG_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ACCOUNT_VALUE_AUDIT FOR CCLA.SEQ_ACCOUNT_VALUE_AUDIT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ADDRESS FOR CCLA.SEQ_ADDRESS;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CAMPAIGN FOR CCLA.SEQ_CAMPAIGN;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SDAUDIT FOR CCLA.SEQ_SDAUDIT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_COMM_SIGNATURE FOR CCLA.SEQ_COMM_SIGNATURE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CLIENT_AURORA_MAP FOR CCLA.SEQ_CLIENT_AURORA_MAP;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PERSON_AURORA_MAP FOR CCLA.SEQ_PERSON_AURORA_MAP;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_CONTACT_POINT FOR CCLA.SEQ_CONTACT_POINT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_ELEMENT FOR CCLA.SEQ_ELEMENT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_RELATIONS FOR CCLA.SEQ_RELATIONS;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_AUDIT FOR CCLA.SEQ_FUND_AUDIT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_EOD FOR CCLA.SEQ_FUND_EOD;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_NAV_AUDIT FOR CCLA.SEQ_FUND_NAV_AUDIT;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_PRICE_APPLIED FOR CCLA.SEQ_FUND_PRICE_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_FUND_PRICE FOR CCLA.SEQ_FUND_PRICE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INCOME_EXPENSE_APPLIED FOR CCLA.SEQ_INCOME_EXPENSE_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_INCOME_EXPENSE FOR CCLA.SEQ_INCOME_EXPENSE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_RELATION_PROPERTY_APPLIED FOR CCLA.SEQ_RELATION_PROPERTY_APPLIED;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_NOTE FOR CCLA.SEQ_NOTE;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_SHARE_CLASS_MOVEMENT FOR CCLA.SEQ_SHARE_CLASS_MOVEMENT;


GRANT ALL ON SEQ_ACCOUNT_FLAG_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_ACCOUNT_VALUE_AUDIT TO UCMADMIN;
GRANT ALL ON SEQ_ADDRESS TO UCMADMIN;
GRANT ALL ON SEQ_CAMPAIGN TO UCMADMIN;
GRANT ALL ON SEQ_SDAUDIT TO UCMADMIN;
GRANT ALL ON SEQ_COMM_SIGNATURE TO UCMADMIN;
GRANT ALL ON SEQ_CLIENT_AURORA_MAP TO UCMADMIN;
GRANT ALL ON SEQ_PERSON_AURORA_MAP TO UCMADMIN;
GRANT ALL ON SEQ_CONTACT_POINT TO UCMADMIN;
GRANT ALL ON SEQ_ELEMENT TO UCMADMIN;
GRANT ALL ON SEQ_RELATIONS TO UCMADMIN;
GRANT ALL ON SEQ_FUND_AUDIT TO UCMADMIN;
GRANT ALL ON SEQ_FUND_EOD TO UCMADMIN;
GRANT ALL ON SEQ_FUND_NAV_AUDIT TO UCMADMIN;
GRANT ALL ON SEQ_FUND_PRICE_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_FUND_PRICE TO UCMADMIN;
GRANT ALL ON SEQ_INCOME_EXPENSE_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_INCOME_EXPENSE TO UCMADMIN;
GRANT ALL ON SEQ_INSTRUCTION TO UCMADMIN;
GRANT ALL ON SEQ_RELATION_PROPERTY_APPLIED TO UCMADMIN;
GRANT ALL ON SEQ_NOTE TO UCMADMIN;
GRANT ALL ON SEQ_SHARE_CLASS_MOVEMENT TO UCMADMIN;
