package com.ecs.stellent.spp.data;

/** Container for values that are generated/returned as a result of triggering a
 *  job in SPP.
 *  
 * @author Tom
 *
 */
public class WorkflowJobResponse {

	/** Unique Job ID generated by UCM when a job is triggered. */
	private Integer ucmJobId;
	
	/** Unique GUID returned by SPP when a job is triggered. Apparently this refers
	 *  to a 'Map ID' in SPP and can't be used to uniquely identify the job.
	 */
	private String returnId;
	
	public WorkflowJobResponse(Integer ucmJobId, String returnId) {
		this.ucmJobId = ucmJobId;
		this.returnId = returnId;
	}
	
	public Integer getUcmJobId() {
		return ucmJobId;
	}
	public String getReturnId() {
		return returnId;
	}
	
	public String toString() {
		return "[UCM Job ID: " + ucmJobId + ", SPP Return ID: " + returnId + "]";
	}
}
